--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(83)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create PageView_1
local PageView_1 = ccui.PageView:create()
PageView_1:ignoreContentAdaptWithSize(false)
PageView_1:setClippingEnabled(true)
PageView_1:setBackGroundColorOpacity(102)
PageView_1:setTouchEnabled(false);
PageView_1:setLayoutComponentEnabled(true)
PageView_1:setName("PageView_1")
PageView_1:setTag(83)
PageView_1:setCascadeColorEnabled(true)
PageView_1:setCascadeOpacityEnabled(true)
PageView_1:setAnchorPoint(0.5000, 0.5000)
PageView_1:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PageView_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
layout:setVerticalEdge(2)
Layer:addChild(PageView_1)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("Image/UI/MenuUI/back.png",0)
Button_back:loadTexturePressed("Image/UI/MenuUI/back2.png",0)
Button_back:loadTextureDisabled("Default/Button_Disable.png",0)
Button_back:setTitleFontSize(14)
Button_back:setTitleColor({r = 65, g = 65, b = 70})
Button_back:setScale9Enabled(true)
Button_back:setCapInsets({x = 15, y = 11, width = 145, height = 56})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(137)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(117.5000, 1864.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.1088)
layout:setPositionPercentY(0.9708)
layout:setPercentWidth(0.1620)
layout:setPercentHeight(0.0406)
layout:setSize({width = 175.0000, height = 78.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(875.0000)
layout:setTopMargin(17.0002)
layout:setBottomMargin(1825.0000)
Layer:addChild(Button_back)

--Create Text_changItem
local Text_changItem = ccui.Text:create()
Text_changItem:ignoreContentAdaptWithSize(true)
Text_changItem:setTextAreaSize({width = 0, height = 0})
Text_changItem:setFontName("Font/default.ttf")
Text_changItem:setFontSize(48)
Text_changItem:setString([[可点击左右键切换道具]])
Text_changItem:enableOutline({r = 0, g = 0, b = 0, a = 255}, 4)
Text_changItem:setLayoutComponentEnabled(true)
Text_changItem:setName("Text_changItem")
Text_changItem:setTag(133)
Text_changItem:setCascadeColorEnabled(true)
Text_changItem:setCascadeOpacityEnabled(true)
Text_changItem:setPosition(540.0003, 222.1440)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_changItem)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1157)
layout:setPercentWidth(0.4491)
layout:setPercentHeight(0.0323)
layout:setSize({width = 485.0000, height = 62.0000})
layout:setLeftMargin(297.5003)
layout:setRightMargin(297.4997)
layout:setTopMargin(1666.8560)
layout:setBottomMargin(191.1440)
Layer:addChild(Text_changItem)

--Create Panel_left
local Panel_left = ccui.Layout:create()
Panel_left:ignoreContentAdaptWithSize(false)
Panel_left:setClippingEnabled(false)
Panel_left:setBackGroundColorOpacity(102)
Panel_left:setTouchEnabled(true);
Panel_left:setLayoutComponentEnabled(true)
Panel_left:setName("Panel_left")
Panel_left:setTag(134)
Panel_left:setCascadeColorEnabled(true)
Panel_left:setCascadeOpacityEnabled(true)
Panel_left:setAnchorPoint(1.0000, 0.5000)
Panel_left:setPosition(285.0000, 220.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_left)
layout:setPositionPercentX(0.2639)
layout:setPositionPercentY(0.1146)
layout:setPercentWidth(0.2361)
layout:setPercentHeight(0.1042)
layout:setSize({width = 255.0000, height = 200.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(795.0000)
layout:setTopMargin(1600.0000)
layout:setBottomMargin(120.0000)
Layer:addChild(Panel_left)

--Create Image_row
local Image_row = ccui.ImageView:create()
Image_row:ignoreContentAdaptWithSize(false)
Image_row:loadTexture("Image/UI/MaskUI/anniuArrow.png",0)
Image_row:setLayoutComponentEnabled(true)
Image_row:setName("Image_row")
Image_row:setTag(132)
Image_row:setCascadeColorEnabled(true)
Image_row:setCascadeOpacityEnabled(true)
Image_row:setPosition(140.0000, 99.9999)
Image_row:setRotationSkewX(-90.0000)
Image_row:setRotationSkewY(-90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_row)
layout:setPositionPercentX(0.5490)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3294)
layout:setPercentHeight(0.3450)
layout:setSize({width = 84.0000, height = 69.0000})
layout:setLeftMargin(98.0000)
layout:setRightMargin(73.0000)
layout:setTopMargin(65.5001)
layout:setBottomMargin(65.4999)
Panel_left:addChild(Image_row)

--Create Panel_right
local Panel_right = ccui.Layout:create()
Panel_right:ignoreContentAdaptWithSize(false)
Panel_right:setClippingEnabled(false)
Panel_right:setBackGroundColorOpacity(102)
Panel_right:setTouchEnabled(true);
Panel_right:setLayoutComponentEnabled(true)
Panel_right:setName("Panel_right")
Panel_right:setTag(135)
Panel_right:setCascadeColorEnabled(true)
Panel_right:setCascadeOpacityEnabled(true)
Panel_right:setAnchorPoint(1.0000, 0.5000)
Panel_right:setPosition(1050.0000, 220.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_right)
layout:setPositionPercentX(0.9722)
layout:setPositionPercentY(0.1146)
layout:setPercentWidth(0.2361)
layout:setPercentHeight(0.1042)
layout:setSize({width = 255.0000, height = 200.0000})
layout:setLeftMargin(795.0000)
layout:setRightMargin(30.0000)
layout:setTopMargin(1600.0000)
layout:setBottomMargin(120.0000)
Layer:addChild(Panel_right)

--Create Image_row
local Image_row = ccui.ImageView:create()
Image_row:ignoreContentAdaptWithSize(false)
Image_row:loadTexture("Image/UI/MaskUI/anniuArrow.png",0)
Image_row:setLayoutComponentEnabled(true)
Image_row:setName("Image_row")
Image_row:setTag(136)
Image_row:setCascadeColorEnabled(true)
Image_row:setCascadeOpacityEnabled(true)
Image_row:setPosition(115.0000, 99.9998)
Image_row:setRotationSkewX(90.0000)
Image_row:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_row)
layout:setPositionPercentX(0.4510)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3294)
layout:setPercentHeight(0.3450)
layout:setSize({width = 84.0000, height = 69.0000})
layout:setLeftMargin(73.0000)
layout:setRightMargin(98.0000)
layout:setTopMargin(65.5002)
layout:setBottomMargin(65.4998)
Panel_right:addChild(Image_row)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000