--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Sprite_table
local Sprite_table = cc.Sprite:create("Image/UI/SkinUI/Skin_1/4.png")
Sprite_table:setName("Sprite_table")
Sprite_table:setTag(176)
Sprite_table:setCascadeColorEnabled(true)
Sprite_table:setCascadeOpacityEnabled(true)
Sprite_table:setPosition(540.0000, 1754.0550)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_table)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9136)
layout:setPercentWidth(0.9389)
layout:setPercentHeight(0.0563)
layout:setSize({width = 1014.0000, height = 108.0000})
layout:setLeftMargin(33.0000)
layout:setRightMargin(33.0000)
layout:setTopMargin(111.9449)
layout:setBottomMargin(1700.0550)
Sprite_table:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_table)

--Create Image_roleAttr
local Image_roleAttr = ccui.ImageView:create()
Image_roleAttr:ignoreContentAdaptWithSize(false)
Image_roleAttr:loadTexture("Image/UI/SkinUI/Skin_1/5.png",0)
Image_roleAttr:setScale9Enabled(true)
Image_roleAttr:setCapInsets({x = -47, y = 11, width = 122, height = 7})
Image_roleAttr:setLayoutComponentEnabled(true)
Image_roleAttr:setName("Image_roleAttr")
Image_roleAttr:setTag(184)
Image_roleAttr:setCascadeColorEnabled(true)
Image_roleAttr:setCascadeOpacityEnabled(true)
Image_roleAttr:setPosition(170.0000, 49.2985)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_roleAttr)
layout:setPositionPercentX(0.1677)
layout:setPositionPercentY(0.4565)
layout:setPercentWidth(0.2170)
layout:setPercentHeight(0.5185)
layout:setSize({width = 220.0000, height = 56.0000})
layout:setLeftMargin(60.0000)
layout:setRightMargin(734.0000)
layout:setTopMargin(30.7015)
layout:setBottomMargin(21.2985)
Sprite_table:addChild(Image_roleAttr)

--Create Image_jianghuAttr
local Image_jianghuAttr = ccui.ImageView:create()
Image_jianghuAttr:ignoreContentAdaptWithSize(false)
Image_jianghuAttr:loadTexture("Image/UI/SkinUI/Skin_1/5.png",0)
Image_jianghuAttr:setScale9Enabled(true)
Image_jianghuAttr:setCapInsets({x = -44, y = 11, width = 116, height = 7})
Image_jianghuAttr:setLayoutComponentEnabled(true)
Image_jianghuAttr:setName("Image_jianghuAttr")
Image_jianghuAttr:setTag(185)
Image_jianghuAttr:setCascadeColorEnabled(true)
Image_jianghuAttr:setCascadeOpacityEnabled(true)
Image_jianghuAttr:setPosition(508.0000, 49.2985)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_jianghuAttr)
layout:setPositionPercentX(0.5010)
layout:setPositionPercentY(0.4565)
layout:setPercentWidth(0.2170)
layout:setPercentHeight(0.5185)
layout:setSize({width = 220.0000, height = 56.0000})
layout:setLeftMargin(398.0000)
layout:setRightMargin(396.0000)
layout:setTopMargin(30.7015)
layout:setBottomMargin(21.2985)
Sprite_table:addChild(Image_jianghuAttr)

--Create Image_bag
local Image_bag = ccui.ImageView:create()
Image_bag:ignoreContentAdaptWithSize(false)
Image_bag:loadTexture("Image/UI/SkinUI/Skin_1/5.png",0)
Image_bag:setScale9Enabled(true)
Image_bag:setCapInsets({x = -44, y = 11, width = 116, height = 7})
Image_bag:setLayoutComponentEnabled(true)
Image_bag:setName("Image_bag")
Image_bag:setTag(186)
Image_bag:setCascadeColorEnabled(true)
Image_bag:setCascadeOpacityEnabled(true)
Image_bag:setPosition(848.0000, 49.2985)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bag)
layout:setPositionPercentX(0.8363)
layout:setPositionPercentY(0.4565)
layout:setPercentWidth(0.2170)
layout:setPercentHeight(0.5185)
layout:setSize({width = 220.0000, height = 56.0000})
layout:setLeftMargin(738.0000)
layout:setRightMargin(56.0000)
layout:setTopMargin(30.7015)
layout:setBottomMargin(21.2985)
Sprite_table:addChild(Image_bag)

--Create Text_roleAttr
local Text_roleAttr = ccui.Text:create()
Text_roleAttr:ignoreContentAdaptWithSize(true)
Text_roleAttr:setTextAreaSize({width = 0, height = 0})
Text_roleAttr:setFontName("Font/default.ttf")
Text_roleAttr:setFontSize(48)
Text_roleAttr:setString([[人物属性]])
Text_roleAttr:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_roleAttr:setLayoutComponentEnabled(true)
Text_roleAttr:setName("Text_roleAttr")
Text_roleAttr:setTag(177)
Text_roleAttr:setCascadeColorEnabled(true)
Text_roleAttr:setCascadeOpacityEnabled(true)
Text_roleAttr:setPosition(170.0000, 50.0000)
Text_roleAttr:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_roleAttr)
layout:setPositionPercentX(0.1677)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.1953)
layout:setPercentHeight(0.5926)
layout:setSize({width = 198.0000, height = 64.0000})
layout:setLeftMargin(71.0000)
layout:setRightMargin(745.0000)
layout:setTopMargin(26.0000)
layout:setBottomMargin(18.0000)
Sprite_table:addChild(Text_roleAttr)

--Create Text_jianghuAttr
local Text_jianghuAttr = ccui.Text:create()
Text_jianghuAttr:ignoreContentAdaptWithSize(true)
Text_jianghuAttr:setTextAreaSize({width = 0, height = 0})
Text_jianghuAttr:setFontName("Font/default.ttf")
Text_jianghuAttr:setFontSize(48)
Text_jianghuAttr:setString([[江湖属性]])
Text_jianghuAttr:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_jianghuAttr:setLayoutComponentEnabled(true)
Text_jianghuAttr:setName("Text_jianghuAttr")
Text_jianghuAttr:setTag(178)
Text_jianghuAttr:setCascadeColorEnabled(true)
Text_jianghuAttr:setCascadeOpacityEnabled(true)
Text_jianghuAttr:setPosition(508.0000, 50.0000)
Text_jianghuAttr:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_jianghuAttr)
layout:setPositionPercentX(0.5010)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.1953)
layout:setPercentHeight(0.5926)
layout:setSize({width = 198.0000, height = 64.0000})
layout:setLeftMargin(409.0000)
layout:setRightMargin(407.0000)
layout:setTopMargin(26.0000)
layout:setBottomMargin(18.0000)
Sprite_table:addChild(Text_jianghuAttr)

--Create Text_bag
local Text_bag = ccui.Text:create()
Text_bag:ignoreContentAdaptWithSize(true)
Text_bag:setTextAreaSize({width = 0, height = 0})
Text_bag:setFontName("Font/default.ttf")
Text_bag:setFontSize(48)
Text_bag:setString([[    背包    ]])
Text_bag:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_bag:setLayoutComponentEnabled(true)
Text_bag:setName("Text_bag")
Text_bag:setTag(179)
Text_bag:setCascadeColorEnabled(true)
Text_bag:setCascadeOpacityEnabled(true)
Text_bag:setPosition(848.0000, 50.0000)
Text_bag:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_bag)
layout:setPositionPercentX(0.8363)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.2051)
layout:setPercentHeight(0.5926)
layout:setSize({width = 208.0000, height = 64.0000})
layout:setLeftMargin(744.0000)
layout:setRightMargin(62.0000)
layout:setTopMargin(26.0000)
layout:setBottomMargin(18.0000)
Sprite_table:addChild(Text_bag)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000000