--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:setTitleFontSize(14)
Button_back:setTitleColor({r = 65, g = 65, b = 70})
Button_back:setScale9Enabled(true)
Button_back:setCapInsets({x = 13, y = 4, width = 16, height = 6})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(129)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Button_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/TaskUI/tanchuk.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(126)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1118.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5823)
layout:setPercentWidth(0.9315)
layout:setPercentHeight(0.5521)
layout:setSize({width = 1006.0000, height = 1060.0000})
layout:setLeftMargin(37.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(272.0000)
layout:setBottomMargin(588.0000)
Layer:addChild(Image_back)

--Create Button_stopGuaji
local Button_stopGuaji = ccui.Button:create()
Button_stopGuaji:ignoreContentAdaptWithSize(false)
Button_stopGuaji:loadTextureNormal("Image/UI/TaskUI/guaji2.png",0)
Button_stopGuaji:setTitleFontSize(14)
Button_stopGuaji:setTitleText("Button")
Button_stopGuaji:setTitleColor({r = 65, g = 65, b = 70})
Button_stopGuaji:setScale9Enabled(true)
Button_stopGuaji:setCapInsets({x = 15, y = 11, width = 175, height = 121})
Button_stopGuaji:setLayoutComponentEnabled(true)
Button_stopGuaji:setName("Button_stopGuaji")
Button_stopGuaji:setTag(127)
Button_stopGuaji:setCascadeColorEnabled(true)
Button_stopGuaji:setCascadeOpacityEnabled(true)
Button_stopGuaji:setPosition(145.0000, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_stopGuaji)
layout:setPositionPercentX(0.1441)
layout:setPositionPercentY(0.1132)
layout:setPercentWidth(0.2038)
layout:setPercentHeight(0.1349)
layout:setSize({width = 205.0000, height = 143.0000})
layout:setLeftMargin(42.5000)
layout:setRightMargin(758.5000)
layout:setTopMargin(868.5000)
layout:setBottomMargin(48.5000)
Image_back:addChild(Button_stopGuaji)

--Create Panel_print
local Panel_print = ccui.Layout:create()
Panel_print:ignoreContentAdaptWithSize(false)
Panel_print:setClippingEnabled(false)
Panel_print:setBackGroundColorOpacity(102)
Panel_print:setTouchEnabled(true);
Panel_print:setLayoutComponentEnabled(true)
Panel_print:setName("Panel_print")
Panel_print:setTag(128)
Panel_print:setCascadeColorEnabled(true)
Panel_print:setCascadeOpacityEnabled(true)
Panel_print:setPosition(20.0000, 240.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_print)
layout:setPositionPercentX(0.0199)
layout:setPositionPercentY(0.2264)
layout:setPercentWidth(0.9602)
layout:setPercentHeight(0.7547)
layout:setSize({width = 966.0000, height = 800.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(240.0000)
Image_back:addChild(Panel_print)

--Create Text_rightBottom
local Text_rightBottom = ccui.Text:create()
Text_rightBottom:ignoreContentAdaptWithSize(false)
Text_rightBottom:setFontName("Font/default.ttf")
Text_rightBottom:setFontSize(48)
Text_rightBottom:setString([[100 经验 / 小时
100 潜能 / 小时
30 银 / 小时]])
Text_rightBottom:setTextHorizontalAlignment(2)
Text_rightBottom:setTextVerticalAlignment(1)
Text_rightBottom:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_rightBottom:setLayoutComponentEnabled(true)
Text_rightBottom:setName("Text_rightBottom")
Text_rightBottom:setTag(130)
Text_rightBottom:setCascadeColorEnabled(true)
Text_rightBottom:setCascadeOpacityEnabled(true)
Text_rightBottom:setPosition(716.0000, 120.0000)
Text_rightBottom:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_rightBottom)
layout:setPositionPercentX(0.7117)
layout:setPositionPercentY(0.1132)
layout:setPercentWidth(0.4970)
layout:setPercentHeight(0.2075)
layout:setSize({width = 500.0000, height = 220.0000})
layout:setLeftMargin(466.0000)
layout:setRightMargin(40.0000)
layout:setTopMargin(830.0000)
layout:setBottomMargin(10.0000)
Image_back:addChild(Text_rightBottom)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000