--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(191)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/ActionUI/panelBg.png",0)
Image_kuang:setScale9Enabled(true)
Image_kuang:setCapInsets({x = 341, y = 67, width = 368, height = 71})
Image_kuang:setTouchEnabled(true);
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(192)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setAnchorPoint(0.5000, 1.0000)
Image_kuang:setPosition(539.9991, 1640.0010)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8542)
layout:setPercentWidth(0.8741)
layout:setPercentHeight(0.5599)
layout:setSize({width = 944.0000, height = 1075.0000})
layout:setLeftMargin(67.9991)
layout:setRightMargin(68.0009)
layout:setTopMargin(279.9993)
layout:setBottomMargin(565.0007)
Layer:addChild(Image_kuang)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(62)
Text_title:setString([[领悟中]])
Text_title:setTextHorizontalAlignment(1)
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 2)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(193)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(539.9955, 1579.0050)
Text_title:setTextColor({r = 184, g = 162, b = 118})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8224)
layout:setPercentWidth(0.1704)
layout:setPercentHeight(0.0375)
layout:setSize({width = 184.0000, height = 72.0000})
layout:setLeftMargin(447.9955)
layout:setRightMargin(448.0045)
layout:setTopMargin(304.9952)
layout:setBottomMargin(1543.0050)
Layer:addChild(Text_title)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("Font/HYCFS.ttf")
Text_1:setFontSize(60)
Text_1:setString([[武学招式名称]])
Text_1:setTextVerticalAlignment(1)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(194)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 0.5000)
Text_1:setPosition(92.0006, 1488.5010)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.0852)
layout:setPositionPercentY(0.7753)
layout:setPercentWidth(0.3324)
layout:setPercentHeight(0.0344)
layout:setSize({width = 359.0000, height = 66.0000})
layout:setLeftMargin(92.0006)
layout:setRightMargin(628.9994)
layout:setTopMargin(398.4985)
layout:setBottomMargin(1455.5010)
Layer:addChild(Text_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:ignoreContentAdaptWithSize(true)
Text_2:setTextAreaSize({width = 0, height = 0})
Text_2:setFontName("Font/HYCFS.ttf")
Text_2:setFontSize(53)
Text_2:setString([[当前熟练度]])
Text_2:setTextVerticalAlignment(1)
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setTag(195)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
Text_2:setAnchorPoint(0.0000, 0.5000)
Text_2:setPosition(116.0000, 1394.6990)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentX(0.1074)
layout:setPositionPercentY(0.7264)
layout:setPercentWidth(0.2472)
layout:setPercentHeight(0.0302)
layout:setSize({width = 267.0000, height = 58.0000})
layout:setLeftMargin(116.0000)
layout:setRightMargin(697.0000)
layout:setTopMargin(496.3010)
layout:setBottomMargin(1365.6990)
Layer:addChild(Text_2)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:ignoreContentAdaptWithSize(true)
Text_3:setTextAreaSize({width = 0, height = 0})
Text_3:setFontName("Font/HYCFS.ttf")
Text_3:setFontSize(53)
Text_3:setString([[可获得]])
Text_3:setTextVerticalAlignment(1)
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setTag(196)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
Text_3:setAnchorPoint(0.0000, 0.5000)
Text_3:setPosition(116.0000, 1312.2270)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentX(0.1074)
layout:setPositionPercentY(0.6835)
layout:setPercentWidth(0.1481)
layout:setPercentHeight(0.0302)
layout:setSize({width = 160.0000, height = 58.0000})
layout:setLeftMargin(116.0000)
layout:setRightMargin(804.0000)
layout:setTopMargin(578.7729)
layout:setBottomMargin(1283.2270)
Layer:addChild(Text_3)

--Create Text_4
local Text_4 = ccui.Text:create()
Text_4:ignoreContentAdaptWithSize(true)
Text_4:setTextAreaSize({width = 0, height = 0})
Text_4:setFontName("Font/HYCFS.ttf")
Text_4:setFontSize(60)
Text_4:setString([[所需时间]])
Text_4:setTextVerticalAlignment(1)
Text_4:setLayoutComponentEnabled(true)
Text_4:setName("Text_4")
Text_4:setTag(197)
Text_4:setCascadeColorEnabled(true)
Text_4:setCascadeOpacityEnabled(true)
Text_4:setAnchorPoint(0.0000, 0.5000)
Text_4:setPosition(92.0000, 1218.8500)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_4)
layout:setPositionPercentX(0.0852)
layout:setPositionPercentY(0.6348)
layout:setPercentWidth(0.2176)
layout:setPercentHeight(0.0344)
layout:setSize({width = 235.0000, height = 66.0000})
layout:setLeftMargin(92.0000)
layout:setRightMargin(753.0000)
layout:setTopMargin(668.1498)
layout:setBottomMargin(1185.8500)
Layer:addChild(Text_4)

--Create Panel_anim
local Panel_anim = ccui.Layout:create()
Panel_anim:ignoreContentAdaptWithSize(false)
Panel_anim:setClippingEnabled(false)
Panel_anim:setBackGroundColorOpacity(110)
Panel_anim:setTouchEnabled(true);
Panel_anim:setLayoutComponentEnabled(true)
Panel_anim:setName("Panel_anim")
Panel_anim:setTag(198)
Panel_anim:setCascadeColorEnabled(true)
Panel_anim:setCascadeOpacityEnabled(true)
Panel_anim:setAnchorPoint(0.5000, 0.5000)
Panel_anim:setPosition(540.0000, 954.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_anim)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4969)
layout:setPercentWidth(0.4593)
layout:setPercentHeight(0.1719)
layout:setSize({width = 496.0000, height = 330.0000})
layout:setLeftMargin(292.0000)
layout:setRightMargin(292.0000)
layout:setTopMargin(801.0000)
layout:setBottomMargin(789.0000)
Layer:addChild(Panel_anim)

--Create Button_confirm
local Button_confirm = ccui.Button:create()
Button_confirm:ignoreContentAdaptWithSize(false)
Button_confirm:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_confirm:setTitleFontSize(14)
Button_confirm:setTitleColor({r = 65, g = 65, b = 70})
Button_confirm:setScale9Enabled(true)
Button_confirm:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_confirm:setLayoutComponentEnabled(true)
Button_confirm:setName("Button_confirm")
Button_confirm:setTag(199)
Button_confirm:setCascadeColorEnabled(true)
Button_confirm:setCascadeOpacityEnabled(true)
Button_confirm:setPosition(540.0005, 674.0062)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_confirm)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3510)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(408.0005)
layout:setRightMargin(407.9995)
layout:setTopMargin(1196.9940)
layout:setBottomMargin(625.0062)
Layer:addChild(Button_confirm)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/HYCFS.ttf")
Text_ButtonName:setFontSize(56)
Text_ButtonName:setString([[开始领悟]])
Text_ButtonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 3)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(200)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(132.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8636)
layout:setPercentHeight(0.6837)
layout:setSize({width = 228.0000, height = 67.0000})
layout:setLeftMargin(18.0000)
layout:setRightMargin(18.0000)
layout:setTopMargin(15.5000)
layout:setBottomMargin(15.5000)
Button_confirm:addChild(Text_ButtonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000