--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(177)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/ActionUI/panelBg.png",0)
Image_kuang:setScale9Enabled(true)
Image_kuang:setCapInsets({x = 341, y = 67, width = 368, height = 71})
Image_kuang:setTouchEnabled(true);
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(176)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setAnchorPoint(0.5000, 1.0000)
Image_kuang:setPosition(539.9994, 1758.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9156)
layout:setPercentWidth(0.9815)
layout:setPercentHeight(0.8073)
layout:setSize({width = 1060.0000, height = 1550.0000})
layout:setLeftMargin(9.9994)
layout:setRightMargin(10.0006)
layout:setTopMargin(162.0000)
layout:setBottomMargin(208.0000)
Layer:addChild(Image_kuang)

--Create Text_dsc
local Text_dsc = ccui.Text:create()
Text_dsc:ignoreContentAdaptWithSize(false)
Text_dsc:setFontName("Font/HYCFS.ttf")
Text_dsc:setFontSize(60)
Text_dsc:setString([[是否确认融汇以下残页?融汇后可获得XXXXX点尘世感悟，融汇后资源不可恢复，请谨慎对待。]])
Text_dsc:setLayoutComponentEnabled(true)
Text_dsc:setName("Text_dsc")
Text_dsc:setTag(175)
Text_dsc:setCascadeColorEnabled(true)
Text_dsc:setCascadeOpacityEnabled(true)
Text_dsc:setPosition(540.0000, 1550.0000)
Text_dsc:setTextColor({r = 255, g = 138, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_dsc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8073)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.1031)
layout:setSize({width = 900.0000, height = 198.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(90.0000)
layout:setRightMargin(90.0000)
layout:setTopMargin(271.0000)
layout:setBottomMargin(1451.0000)
Layer:addChild(Text_dsc)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setItemsMargin(20)
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorOpacity(102)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(179)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setPosition(90.0000, 471.6551)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.0833)
layout:setPositionPercentY(0.2457)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.4688)
layout:setSize({width = 900.0000, height = 900.0000})
layout:setLeftMargin(90.0000)
layout:setRightMargin(90.0000)
layout:setTopMargin(548.3450)
layout:setBottomMargin(471.6551)
Layer:addChild(ListView_1)

--Create Panel_item
local Panel_item = ccui.Layout:create()
Panel_item:ignoreContentAdaptWithSize(false)
Panel_item:setClippingEnabled(false)
Panel_item:setBackGroundColorOpacity(102)
Panel_item:setTouchEnabled(true);
Panel_item:setLayoutComponentEnabled(true)
Panel_item:setName("Panel_item")
Panel_item:setTag(180)
Panel_item:setCascadeColorEnabled(true)
Panel_item:setCascadeOpacityEnabled(true)
Panel_item:setPosition(125.4398, 2216.2240)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_item)
layout:setPositionPercentX(0.1161)
layout:setPositionPercentY(1.1543)
layout:setPercentWidth(0.7407)
layout:setPercentHeight(0.0313)
layout:setSize({width = 800.0000, height = 60.0000})
layout:setLeftMargin(125.4398)
layout:setRightMargin(154.5602)
layout:setTopMargin(-356.2241)
layout:setBottomMargin(2216.2240)
Layer:addChild(Panel_item)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/HYCFS.ttf")
Text_name:setFontSize(54)
Text_name:setString([[残页名字6个字：]])
Text_name:setTextHorizontalAlignment(1)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(173)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.5000)
Text_name:setPosition(33.9318, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0424)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4638)
layout:setPercentHeight(0.9833)
layout:setSize({width = 371.0000, height = 59.0000})
layout:setLeftMargin(33.9318)
layout:setRightMargin(395.0682)
layout:setTopMargin(0.5000)
layout:setBottomMargin(0.5000)
Panel_item:addChild(Text_name)

--Create Text_num
local Text_num = ccui.Text:create()
Text_num:ignoreContentAdaptWithSize(true)
Text_num:setTextAreaSize({width = 0, height = 0})
Text_num:setFontName("Font/HYCFS.ttf")
Text_num:setFontSize(54)
Text_num:setString([[999]])
Text_num:setTextHorizontalAlignment(1)
Text_num:setLayoutComponentEnabled(true)
Text_num:setName("Text_num")
Text_num:setTag(181)
Text_num:setCascadeColorEnabled(true)
Text_num:setCascadeOpacityEnabled(true)
Text_num:setAnchorPoint(0.0000, 0.5000)
Text_num:setPosition(642.6322, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_num)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.8033)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1000)
layout:setPercentHeight(0.9833)
layout:setSize({width = 80.0000, height = 59.0000})
layout:setLeftMargin(642.6322)
layout:setRightMargin(77.3678)
layout:setTopMargin(0.5000)
layout:setBottomMargin(0.5000)
Panel_item:addChild(Text_num)

--Create Button_cancel
local Button_cancel = ccui.Button:create()
Button_cancel:ignoreContentAdaptWithSize(false)
Button_cancel:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_cancel:setTitleFontSize(14)
Button_cancel:setTitleColor({r = 65, g = 65, b = 70})
Button_cancel:setScale9Enabled(true)
Button_cancel:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_cancel:setLayoutComponentEnabled(true)
Button_cancel:setName("Button_cancel")
Button_cancel:setTag(163)
Button_cancel:setCascadeColorEnabled(true)
Button_cancel:setCascadeOpacityEnabled(true)
Button_cancel:setPosition(291.6281, 362.8888)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_cancel)
layout:setPositionPercentX(0.2700)
layout:setPositionPercentY(0.1890)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(159.6281)
layout:setRightMargin(656.3719)
layout:setTopMargin(1508.1110)
layout:setBottomMargin(313.8888)
Layer:addChild(Button_cancel)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/HYCFS.ttf")
Text_ButtonName:setFontSize(56)
Text_ButtonName:setString([[取消]])
Text_ButtonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 3)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(164)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(132.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4205)
layout:setPercentHeight(0.6837)
layout:setSize({width = 111.0000, height = 67.0000})
layout:setLeftMargin(76.5000)
layout:setRightMargin(76.5000)
layout:setTopMargin(15.5000)
layout:setBottomMargin(15.5000)
Button_cancel:addChild(Text_ButtonName)

--Create Button_confirm
local Button_confirm = ccui.Button:create()
Button_confirm:ignoreContentAdaptWithSize(false)
Button_confirm:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_confirm:setTitleFontSize(14)
Button_confirm:setTitleColor({r = 65, g = 65, b = 70})
Button_confirm:setScale9Enabled(true)
Button_confirm:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_confirm:setLayoutComponentEnabled(true)
Button_confirm:setName("Button_confirm")
Button_confirm:setTag(161)
Button_confirm:setCascadeColorEnabled(true)
Button_confirm:setCascadeOpacityEnabled(true)
Button_confirm:setPosition(797.2648, 362.8888)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_confirm)
layout:setPositionPercentX(0.7382)
layout:setPositionPercentY(0.1890)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(665.2648)
layout:setRightMargin(150.7352)
layout:setTopMargin(1508.1110)
layout:setBottomMargin(313.8888)
Layer:addChild(Button_confirm)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/HYCFS.ttf")
Text_ButtonName:setFontSize(56)
Text_ButtonName:setString([[确定融汇]])
Text_ButtonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 3)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(162)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(132.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8523)
layout:setPercentHeight(0.6837)
layout:setSize({width = 225.0000, height = 67.0000})
layout:setLeftMargin(19.5000)
layout:setRightMargin(19.5000)
layout:setTopMargin(15.5000)
layout:setBottomMargin(15.5000)
Button_confirm:addChild(Text_ButtonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00