--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Btn_Task_Item
local Btn_Task_Item = ccui.Button:create()
Btn_Task_Item:ignoreContentAdaptWithSize(false)
Btn_Task_Item:loadTextureNormal("Image/UI/SkinUI/Skin_7/listBtnBg.png",0)
Btn_Task_Item:setTitleFontSize(14)
Btn_Task_Item:setTitleColor({r = 65, g = 65, b = 70})
Btn_Task_Item:setScale9Enabled(true)
Btn_Task_Item:setCapInsets({x = 15, y = 11, width = 938, height = 195})
Btn_Task_Item:setTouchEnabled(false);
Btn_Task_Item:setLayoutComponentEnabled(true)
Btn_Task_Item:setName("Btn_Task_Item")
Btn_Task_Item:setTag(469)
Btn_Task_Item:setCascadeColorEnabled(true)
Btn_Task_Item:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Task_Item)
layout:setSize({width = 968.0000, height = 217.0000})
layout:setLeftMargin(-484.0000)
layout:setRightMargin(-484.0000)
layout:setTopMargin(-108.5000)
layout:setBottomMargin(-108.5000)
Node:addChild(Btn_Task_Item)

--Create Img_TaskName
local Img_TaskName = ccui.ImageView:create()
Img_TaskName:ignoreContentAdaptWithSize(false)
Img_TaskName:loadTexture("Image/UI/TaskUI/anniuword01b.png",0)
Img_TaskName:setLayoutComponentEnabled(true)
Img_TaskName:setName("Img_TaskName")
Img_TaskName:setTag(470)
Img_TaskName:setCascadeColorEnabled(true)
Img_TaskName:setCascadeOpacityEnabled(true)
Img_TaskName:setPosition(300.0000, 108.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_TaskName)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3099)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4711)
layout:setPercentHeight(0.3687)
layout:setSize({width = 456.0000, height = 80.0000})
layout:setLeftMargin(72.0000)
layout:setRightMargin(440.0000)
layout:setTopMargin(68.5000)
layout:setBottomMargin(68.5000)
Btn_Task_Item:addChild(Img_TaskName)

--Create LoadingBar_Progress
local LoadingBar_Progress = ccui.LoadingBar:create()
LoadingBar_Progress:loadTexture("Image/UI/TaskUI/anniuword01.png",0)
LoadingBar_Progress:ignoreContentAdaptWithSize(false)
LoadingBar_Progress:setLayoutComponentEnabled(true)
LoadingBar_Progress:setName("LoadingBar_Progress")
LoadingBar_Progress:setTag(471)
LoadingBar_Progress:setCascadeColorEnabled(true)
LoadingBar_Progress:setCascadeOpacityEnabled(true)
LoadingBar_Progress:setPosition(300.0000, 108.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(LoadingBar_Progress)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3099)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4711)
layout:setPercentHeight(0.3687)
layout:setSize({width = 456.0000, height = 80.0000})
layout:setLeftMargin(72.0000)
layout:setRightMargin(440.0000)
layout:setTopMargin(68.5000)
layout:setBottomMargin(68.5000)
Btn_Task_Item:addChild(LoadingBar_Progress)

--Create Button_Accept
local Button_Accept = ccui.Button:create()
Button_Accept:ignoreContentAdaptWithSize(false)
Button_Accept:loadTextureNormal("Image/UI/TaskUI/anniu01.png",0)
Button_Accept:setTitleFontSize(14)
Button_Accept:setTitleColor({r = 65, g = 65, b = 70})
Button_Accept:setScale9Enabled(true)
Button_Accept:setCapInsets({x = 15, y = 11, width = 119, height = 121})
Button_Accept:setLayoutComponentEnabled(true)
Button_Accept:setName("Button_Accept")
Button_Accept:setTag(472)
Button_Accept:setCascadeColorEnabled(true)
Button_Accept:setCascadeOpacityEnabled(true)
Button_Accept:setPosition(787.1448, 108.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Accept)
layout:setPositionPercentX(0.8132)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1539)
layout:setPercentHeight(0.6590)
layout:setSize({width = 149.0000, height = 143.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(712.6448)
layout:setRightMargin(106.3552)
layout:setTopMargin(37.0000)
layout:setBottomMargin(37.0000)
Btn_Task_Item:addChild(Button_Accept)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(60)
Text_buttonName:setString([[进行中]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(473)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(75.0000, 75.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5034)
layout:setPositionPercentY(0.5245)
layout:setPercentWidth(1.2215)
layout:setPercentHeight(0.5385)
layout:setSize({width = 182.0000, height = 77.0000})
layout:setLeftMargin(-16.0000)
layout:setRightMargin(-17.0000)
layout:setTopMargin(29.5000)
layout:setBottomMargin(36.5000)
Button_Accept:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

000000000000