--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(718)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(60)
Text_desc:setString([[啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
啊啊啊啊啊啊啊啊啊
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊]])
Text_desc:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(717)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setAnchorPoint(0.0000, 0.0000)
Text_desc:setPosition(87.0000, 1449.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.0806)
layout:setPositionPercentY(0.7547)
layout:setPercentWidth(0.8389)
layout:setPercentHeight(0.1203)
layout:setSize({width = 906.0000, height = 231.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(87.0000)
layout:setTopMargin(240.0000)
layout:setBottomMargin(1449.0000)
Layer:addChild(Text_desc)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/InheritUI/answer.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 851, height = 192})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(715)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(540.0000, 1250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6510)
layout:setPercentWidth(0.8157)
layout:setPercentHeight(0.1115)
layout:setSize({width = 881.0000, height = 214.0000})
layout:setLeftMargin(99.5000)
layout:setRightMargin(99.5000)
layout:setTopMargin(563.0000)
layout:setBottomMargin(1143.0000)
Layer:addChild(Button_1)

--Create Text_name_1
local Text_name_1 = ccui.Text:create()
Text_name_1:ignoreContentAdaptWithSize(false)
Text_name_1:setFontName("Font/default.ttf")
Text_name_1:setFontSize(36)
Text_name_1:setString([[有人的地方就有江湖]])
Text_name_1:setTextVerticalAlignment(1)
Text_name_1:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name_1:setLayoutComponentEnabled(true)
Text_name_1:setName("Text_name_1")
Text_name_1:setTag(733)
Text_name_1:setCascadeColorEnabled(true)
Text_name_1:setCascadeOpacityEnabled(true)
Text_name_1:setPosition(440.0000, 107.0000)
Text_name_1:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name_1)
layout:setPositionPercentX(0.4994)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6810)
layout:setPercentHeight(1.0000)
layout:setSize({width = 600.0000, height = 214.0000})
layout:setLeftMargin(140.0000)
layout:setRightMargin(141.0000)
Button_1:addChild(Text_name_1)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Image/UI/InheritUI/answer.png",0)
Button_2:setTitleFontName("Font/default.ttf")
Button_2:setTitleFontSize(48)
Button_2:setScale9Enabled(true)
Button_2:setCapInsets({x = 15, y = 11, width = 851, height = 192})
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setTag(734)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setPosition(540.0000, 1000.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5208)
layout:setPercentWidth(0.8157)
layout:setPercentHeight(0.1115)
layout:setSize({width = 881.0000, height = 214.0000})
layout:setLeftMargin(99.5000)
layout:setRightMargin(99.5000)
layout:setTopMargin(813.0000)
layout:setBottomMargin(893.0000)
Layer:addChild(Button_2)

--Create Text_name_2
local Text_name_2 = ccui.Text:create()
Text_name_2:ignoreContentAdaptWithSize(false)
Text_name_2:setFontName("Font/default.ttf")
Text_name_2:setFontSize(36)
Text_name_2:setString([[有人的地方就有江湖]])
Text_name_2:setTextVerticalAlignment(1)
Text_name_2:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name_2:setLayoutComponentEnabled(true)
Text_name_2:setName("Text_name_2")
Text_name_2:setTag(735)
Text_name_2:setCascadeColorEnabled(true)
Text_name_2:setCascadeOpacityEnabled(true)
Text_name_2:setPosition(440.0000, 107.0000)
Text_name_2:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name_2)
layout:setPositionPercentX(0.4994)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6810)
layout:setPercentHeight(1.0000)
layout:setSize({width = 600.0000, height = 214.0000})
layout:setLeftMargin(140.0000)
layout:setRightMargin(141.0000)
Button_2:addChild(Text_name_2)

--Create Button_3
local Button_3 = ccui.Button:create()
Button_3:ignoreContentAdaptWithSize(false)
Button_3:loadTextureNormal("Image/UI/InheritUI/answer.png",0)
Button_3:setTitleFontName("Font/default.ttf")
Button_3:setTitleFontSize(48)
Button_3:setScale9Enabled(true)
Button_3:setCapInsets({x = 15, y = 11, width = 851, height = 192})
Button_3:setLayoutComponentEnabled(true)
Button_3:setName("Button_3")
Button_3:setTag(736)
Button_3:setCascadeColorEnabled(true)
Button_3:setCascadeOpacityEnabled(true)
Button_3:setPosition(540.0000, 750.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3906)
layout:setPercentWidth(0.8157)
layout:setPercentHeight(0.1115)
layout:setSize({width = 881.0000, height = 214.0000})
layout:setLeftMargin(99.5000)
layout:setRightMargin(99.5000)
layout:setTopMargin(1063.0000)
layout:setBottomMargin(643.0000)
Layer:addChild(Button_3)

--Create Text_name_3
local Text_name_3 = ccui.Text:create()
Text_name_3:ignoreContentAdaptWithSize(false)
Text_name_3:setFontName("Font/default.ttf")
Text_name_3:setFontSize(36)
Text_name_3:setString([[有人的地方就有江湖]])
Text_name_3:setTextVerticalAlignment(1)
Text_name_3:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name_3:setLayoutComponentEnabled(true)
Text_name_3:setName("Text_name_3")
Text_name_3:setTag(737)
Text_name_3:setCascadeColorEnabled(true)
Text_name_3:setCascadeOpacityEnabled(true)
Text_name_3:setPosition(440.0000, 107.0000)
Text_name_3:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name_3)
layout:setPositionPercentX(0.4994)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6810)
layout:setPercentHeight(1.0000)
layout:setSize({width = 600.0000, height = 214.0000})
layout:setLeftMargin(140.0000)
layout:setRightMargin(141.0000)
Button_3:addChild(Text_name_3)

--Create Button_4
local Button_4 = ccui.Button:create()
Button_4:ignoreContentAdaptWithSize(false)
Button_4:loadTextureNormal("Image/UI/InheritUI/answer.png",0)
Button_4:setTitleFontName("Font/default.ttf")
Button_4:setTitleFontSize(48)
Button_4:setScale9Enabled(true)
Button_4:setCapInsets({x = 15, y = 11, width = 851, height = 192})
Button_4:setLayoutComponentEnabled(true)
Button_4:setName("Button_4")
Button_4:setTag(738)
Button_4:setCascadeColorEnabled(true)
Button_4:setCascadeOpacityEnabled(true)
Button_4:setPosition(540.0000, 500.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2604)
layout:setPercentWidth(0.8157)
layout:setPercentHeight(0.1115)
layout:setSize({width = 881.0000, height = 214.0000})
layout:setLeftMargin(99.5000)
layout:setRightMargin(99.5000)
layout:setTopMargin(1313.0000)
layout:setBottomMargin(393.0000)
Layer:addChild(Button_4)

--Create Text_name_4
local Text_name_4 = ccui.Text:create()
Text_name_4:ignoreContentAdaptWithSize(false)
Text_name_4:setFontName("Font/default.ttf")
Text_name_4:setFontSize(36)
Text_name_4:setString([[有人的地方就有江湖]])
Text_name_4:setTextVerticalAlignment(1)
Text_name_4:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name_4:setLayoutComponentEnabled(true)
Text_name_4:setName("Text_name_4")
Text_name_4:setTag(739)
Text_name_4:setCascadeColorEnabled(true)
Text_name_4:setCascadeOpacityEnabled(true)
Text_name_4:setPosition(440.0000, 107.0000)
Text_name_4:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name_4)
layout:setPositionPercentX(0.4994)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6810)
layout:setPercentHeight(1.0000)
layout:setSize({width = 600.0000, height = 214.0000})
layout:setLeftMargin(140.0000)
layout:setRightMargin(141.0000)
Button_4:addChild(Text_name_4)

--Create Button_5
local Button_5 = ccui.Button:create()
Button_5:ignoreContentAdaptWithSize(false)
Button_5:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_5:setTitleFontName("Font/default.ttf")
Button_5:setTitleFontSize(48)
Button_5:setScale9Enabled(true)
Button_5:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_5:setLayoutComponentEnabled(true)
Button_5:setName("Button_5")
Button_5:setTag(707)
Button_5:setCascadeColorEnabled(true)
Button_5:setCascadeOpacityEnabled(true)
Button_5:setPosition(540.0000, 250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_5)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1302)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1611.0000)
layout:setBottomMargin(191.0000)
Layer:addChild(Button_5)

--Create Text_name_5
local Text_name_5 = ccui.Text:create()
Text_name_5:ignoreContentAdaptWithSize(true)
Text_name_5:setTextAreaSize({width = 0, height = 0})
Text_name_5:setFontName("Font/default.ttf")
Text_name_5:setFontSize(48)
Text_name_5:setString([[武学世家]])
Text_name_5:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name_5:setLayoutComponentEnabled(true)
Text_name_5:setName("Text_name_5")
Text_name_5:setTag(708)
Text_name_5:setCascadeColorEnabled(true)
Text_name_5:setCascadeOpacityEnabled(true)
Text_name_5:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name_5)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6142)
layout:setPercentHeight(0.5424)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(62.5000)
layout:setRightMargin(62.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_5:addChild(Text_name_5)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000