--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(41)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(539.9999, 960.0000)
Panel_back:setOpacity(130)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
layout:setLeftMargin(-0.0001)
layout:setRightMargin(0.0001)
Layer:addChild(Panel_back)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/MainUI/loginReward.png",0)
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(36)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(540.0120, 988.6904)
Image_kuang:setOpacity(234)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5149)
layout:setPercentWidth(0.9769)
layout:setPercentHeight(0.4323)
layout:setSize({width = 1055.0000, height = 830.0000})
layout:setLeftMargin(12.5120)
layout:setRightMargin(12.4880)
layout:setTopMargin(516.3096)
layout:setBottomMargin(573.6904)
Layer:addChild(Image_kuang)

--Create Panel_state
local Panel_state = ccui.Layout:create()
Panel_state:ignoreContentAdaptWithSize(false)
Panel_state:setClippingEnabled(false)
Panel_state:setBackGroundColorType(1)
Panel_state:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_state:setBackGroundColorOpacity(0)
Panel_state:setTouchEnabled(true);
Panel_state:setLayoutComponentEnabled(true)
Panel_state:setName("Panel_state")
Panel_state:setTag(42)
Panel_state:setCascadeColorEnabled(true)
Panel_state:setCascadeOpacityEnabled(true)
Panel_state:setAnchorPoint(0.5000, 0.5000)
Panel_state:setPosition(517.0001, 207.0800)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_state)
layout:setPositionPercentX(0.4900)
layout:setPositionPercentY(0.2495)
layout:setPercentWidth(0.9536)
layout:setPercentHeight(0.0964)
layout:setSize({width = 1006.0000, height = 80.0000})
layout:setLeftMargin(14.0001)
layout:setRightMargin(34.9999)
layout:setTopMargin(582.9200)
layout:setBottomMargin(167.0800)
Image_kuang:addChild(Panel_state)

--Create Image_9
local Image_9 = ccui.ImageView:create()
Image_9:ignoreContentAdaptWithSize(false)
Image_9:loadTexture("Image/UI/SignInUI/yuanbao-2.png",0)
Image_9:setLayoutComponentEnabled(true)
Image_9:setName("Image_9")
Image_9:setTag(82)
Image_9:setCascadeColorEnabled(true)
Image_9:setCascadeOpacityEnabled(true)
Image_9:setVisible(false)
Image_9:setPosition(590.4379, 54.9203)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_9)
layout:setPositionPercentX(0.5869)
layout:setPositionPercentY(0.6865)
layout:setPercentWidth(0.0994)
layout:setPercentHeight(1.2500)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(540.4379)
layout:setRightMargin(365.5621)
layout:setTopMargin(-24.9203)
layout:setBottomMargin(4.9203)
Panel_state:addChild(Image_9)

--Create Text_Desc
local Text_Desc = ccui.Text:create()
Text_Desc:ignoreContentAdaptWithSize(false)
Text_Desc:setFontName("Font/HYCFS.ttf")
Text_Desc:setFontSize(52)
Text_Desc:setString([[江湖纪年，初心不忘]])
Text_Desc:setTextHorizontalAlignment(1)
Text_Desc:setLayoutComponentEnabled(true)
Text_Desc:setName("Text_Desc")
Text_Desc:setTag(16)
Text_Desc:setCascadeColorEnabled(true)
Text_Desc:setCascadeOpacityEnabled(true)
Text_Desc:setPosition(530.5712, 1001.6750)
Text_Desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Desc)
layout:setPositionPercentX(0.4913)
layout:setPositionPercentY(0.5217)
layout:setPercentWidth(0.6928)
layout:setPercentHeight(0.1459)
layout:setSize({width = 748.1951, height = 280.0659})
layout:setLeftMargin(156.4737)
layout:setRightMargin(175.3312)
layout:setTopMargin(778.2916)
layout:setBottomMargin(861.6425)
Layer:addChild(Text_Desc)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(37)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(540.0116, 769.0217)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4005)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0116)
layout:setRightMargin(377.9884)
layout:setTopMargin(1091.9780)
layout:setBottomMargin(710.0217)
Layer:addChild(Button_1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(48)
Text_name:setString([[领取]])
Text_name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(35)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3179)
layout:setPercentHeight(0.5424)
layout:setSize({width = 103.0000, height = 64.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_name)

--Create Panel_title
local Panel_title = ccui.Layout:create()
Panel_title:ignoreContentAdaptWithSize(false)
Panel_title:setClippingEnabled(false)
Panel_title:setBackGroundColorType(1)
Panel_title:setBackGroundColor({r = 229, g = 229, b = 229})
Panel_title:setBackGroundColorOpacity(0)
Panel_title:setLayoutComponentEnabled(true)
Panel_title:setName("Panel_title")
Panel_title:setTag(45)
Panel_title:setCascadeColorEnabled(true)
Panel_title:setCascadeOpacityEnabled(true)
Panel_title:setAnchorPoint(0.0000, 0.5000)
Panel_title:setPosition(0.0065, 1261.0450)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_title)
layout:setPositionPercentY(0.6568)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0521)
layout:setSize({width = 1080.0000, height = 100.0000})
layout:setLeftMargin(0.0065)
layout:setRightMargin(-0.0065)
layout:setTopMargin(608.9554)
layout:setBottomMargin(1211.0450)
Layer:addChild(Panel_title)

--Create Image_denglong1
local Image_denglong1 = ccui.ImageView:create()
Image_denglong1:ignoreContentAdaptWithSize(false)
Image_denglong1:loadTexture("Image/UI/MainUI/denglong2.png",0)
Image_denglong1:setScale9Enabled(true)
Image_denglong1:setCapInsets({x = 15, y = 15, width = 349, height = 114})
Image_denglong1:setLayoutComponentEnabled(true)
Image_denglong1:setName("Image_denglong1")
Image_denglong1:setTag(149)
Image_denglong1:setCascadeColorEnabled(true)
Image_denglong1:setCascadeOpacityEnabled(true)
Image_denglong1:setVisible(false)
Image_denglong1:setPosition(112.5044, 2213.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_denglong1)
layout:setPositionPercentX(0.1042)
layout:setPositionPercentY(1.1531)
layout:setPercentWidth(0.3509)
layout:setPercentHeight(0.0750)
layout:setSize({width = 379.0000, height = 144.0000})
layout:setLeftMargin(-76.9956)
layout:setRightMargin(777.9956)
layout:setTopMargin(-365.8799)
layout:setBottomMargin(2141.8800)
Layer:addChild(Image_denglong1)

--Create Image_denglong2
local Image_denglong2 = ccui.ImageView:create()
Image_denglong2:ignoreContentAdaptWithSize(false)
Image_denglong2:loadTexture("Image/UI/MainUI/denglong2.png",0)
Image_denglong2:setFlippedX(true)
Image_denglong2:setScale9Enabled(true)
Image_denglong2:setCapInsets({x = 15, y = 15, width = 349, height = 114})
Image_denglong2:setLayoutComponentEnabled(true)
Image_denglong2:setName("Image_denglong2")
Image_denglong2:setTag(150)
Image_denglong2:setCascadeColorEnabled(true)
Image_denglong2:setCascadeOpacityEnabled(true)
Image_denglong2:setVisible(false)
Image_denglong2:setPosition(975.9601, 2152.3090)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_denglong2)
layout:setPositionPercentX(0.9037)
layout:setPositionPercentY(1.1210)
layout:setPercentWidth(0.3509)
layout:setPercentHeight(0.0750)
layout:setSize({width = 379.0000, height = 144.0000})
layout:setLeftMargin(786.4601)
layout:setRightMargin(-85.4601)
layout:setTopMargin(-304.3093)
layout:setBottomMargin(2080.3090)
Layer:addChild(Image_denglong2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0