--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_refresh
local Panel_refresh = ccui.Layout:create()
Panel_refresh:ignoreContentAdaptWithSize(false)
Panel_refresh:setClippingEnabled(false)
Panel_refresh:setBackGroundColorType(1)
Panel_refresh:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_refresh:setBackGroundColorOpacity(229)
Panel_refresh:setTouchEnabled(true);
Panel_refresh:setLayoutComponentEnabled(true)
Panel_refresh:setName("Panel_refresh")
Panel_refresh:setTag(94)
Panel_refresh:setCascadeColorEnabled(true)
Panel_refresh:setCascadeOpacityEnabled(true)
Panel_refresh:setAnchorPoint(0.5000, 0.5000)
Panel_refresh:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_refresh)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_refresh)

--Create Text_104
local Text_104 = ccui.Text:create()
Text_104:ignoreContentAdaptWithSize(false)
Text_104:setFontName("Font/default.ttf")
Text_104:setFontSize(60)
Text_104:setString([[是否花费50元宝刷新并锁定晋级奖励？刷新后晋级奖励不再自动刷新（可手动刷新奖励）]])
Text_104:setLayoutComponentEnabled(true)
Text_104:setName("Text_104")
Text_104:setTag(95)
Text_104:setCascadeColorEnabled(true)
Text_104:setCascadeOpacityEnabled(true)
Text_104:setPosition(540.0000, 1539.9990)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_104)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8021)
layout:setPercentWidth(0.7963)
layout:setPercentHeight(0.1851)
layout:setSize({width = 860.0000, height = 355.4689})
layout:setLeftMargin(110.0000)
layout:setRightMargin(110.0000)
layout:setTopMargin(202.2668)
layout:setBottomMargin(1362.2640)
Panel_refresh:addChild(Text_104)

--Create Button_refresh
local Button_refresh = ccui.Button:create()
Button_refresh:ignoreContentAdaptWithSize(false)
Button_refresh:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_refresh:setTitleFontName("Font/default.ttf")
Button_refresh:setTitleFontSize(48)
Button_refresh:setScale9Enabled(true)
Button_refresh:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_refresh:setLayoutComponentEnabled(true)
Button_refresh:setName("Button_refresh")
Button_refresh:setTag(96)
Button_refresh:setCascadeColorEnabled(true)
Button_refresh:setCascadeOpacityEnabled(true)
Button_refresh:setPosition(540.0000, 835.0400)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_refresh)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4349)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0800})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1025.9200)
layout:setBottomMargin(776.0000)
layout:setStretchHeightEnabled(true)
Panel_refresh:addChild(Button_refresh)

--Create Text_refresh
local Text_refresh = ccui.Text:create()
Text_refresh:ignoreContentAdaptWithSize(true)
Text_refresh:setTextAreaSize({width = 0, height = 0})
Text_refresh:setFontName("Font/default.ttf")
Text_refresh:setFontSize(48)
Text_refresh:setString([[刷新]])
Text_refresh:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_refresh:setLayoutComponentEnabled(true)
Text_refresh:setName("Text_refresh")
Text_refresh:setTag(97)
Text_refresh:setCascadeColorEnabled(true)
Text_refresh:setCascadeOpacityEnabled(true)
Text_refresh:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_refresh)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4997)
layout:setPercentWidth(0.3179)
layout:setPercentHeight(0.5420)
layout:setSize({width = 103.0000, height = 64.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(27.0800)
layout:setBottomMargin(27.0000)
Button_refresh:addChild(Text_refresh)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_close:setTitleFontName("Font/default.ttf")
Button_close:setTitleFontSize(48)
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(98)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setPosition(540.0000, 631.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3286)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1230.0000)
layout:setBottomMargin(572.0000)
Panel_refresh:addChild(Button_close)

--Create Text_close
local Text_close = ccui.Text:create()
Text_close:ignoreContentAdaptWithSize(true)
Text_close:setTextAreaSize({width = 0, height = 0})
Text_close:setFontName("Font/default.ttf")
Text_close:setFontSize(48)
Text_close:setString([[关闭]])
Text_close:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_close:setLayoutComponentEnabled(true)
Text_close:setName("Text_close")
Text_close:setTag(99)
Text_close:setCascadeColorEnabled(true)
Text_close:setCascadeOpacityEnabled(true)
Text_close:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_close)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(112.0000)
layout:setRightMargin(112.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_close:addChild(Text_close)

--Create Text_desc1
local Text_desc1 = ccui.Text:create()
Text_desc1:ignoreContentAdaptWithSize(true)
Text_desc1:setTextAreaSize({width = 0, height = 0})
Text_desc1:setFontName("Font/default.ttf")
Text_desc1:setFontSize(48)
Text_desc1:setString([[Text Label]])
Text_desc1:setTextHorizontalAlignment(1)
Text_desc1:setTextVerticalAlignment(1)
Text_desc1:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc1:setLayoutComponentEnabled(true)
Text_desc1:setName("Text_desc1")
Text_desc1:setTag(184)
Text_desc1:setCascadeColorEnabled(true)
Text_desc1:setCascadeOpacityEnabled(true)
Text_desc1:setPosition(540.0000, 1267.7730)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6603)
layout:setPercentWidth(0.2176)
layout:setPercentHeight(0.0281)
layout:setSize({width = 240.0000, height = 64.0000})
layout:setLeftMargin(420.0000)
layout:setRightMargin(420.0000)
layout:setTopMargin(620.2273)
layout:setBottomMargin(1235.7730)
Panel_refresh:addChild(Text_desc1)

--Create Text_desc2
local Text_desc2 = ccui.Text:create()
Text_desc2:ignoreContentAdaptWithSize(true)
Text_desc2:setTextAreaSize({width = 0, height = 0})
Text_desc2:setFontName("Font/default.ttf")
Text_desc2:setFontSize(48)
Text_desc2:setString([[Text Label]])
Text_desc2:setTextHorizontalAlignment(1)
Text_desc2:setTextVerticalAlignment(1)
Text_desc2:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc2:setLayoutComponentEnabled(true)
Text_desc2:setName("Text_desc2")
Text_desc2:setTag(185)
Text_desc2:setCascadeColorEnabled(true)
Text_desc2:setCascadeOpacityEnabled(true)
Text_desc2:setPosition(540.0000, 1109.4720)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5778)
layout:setPercentWidth(0.2222)
layout:setPercentHeight(0.0333)
layout:setSize({width = 240.0000, height = 64.0000})
layout:setLeftMargin(420.0000)
layout:setRightMargin(420.0000)
layout:setTopMargin(778.5282)
layout:setBottomMargin(1077.4720)
Panel_refresh:addChild(Text_desc2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000