--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(191)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setScale9Enabled(true)
Image_back:setCapInsets({x = 398, y = 377, width = 283, height = 478})
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(190)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0272, 1021.4560)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5320)
layout:setPercentWidth(0.9259)
layout:setPercentHeight(0.7813)
layout:setSize({width = 1000.0000, height = 1500.0000})
layout:setLeftMargin(40.0272)
layout:setRightMargin(39.9729)
layout:setTopMargin(148.5435)
layout:setBottomMargin(271.4565)
Layer:addChild(Image_back)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(44)
Text_desc:setString([[文本描述]])
Text_desc:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(200)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setAnchorPoint(0.0000, 0.0000)
Text_desc:setPosition(87.0001, 1407.9970)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.0806)
layout:setPositionPercentY(0.7333)
layout:setPercentWidth(0.8389)
layout:setPercentHeight(0.1563)
layout:setSize({width = 906.0000, height = 300.0000})
layout:setLeftMargin(87.0001)
layout:setRightMargin(86.9999)
layout:setTopMargin(212.0029)
layout:setBottomMargin(1407.9970)
Layer:addChild(Text_desc)

--Create ListView_button
local ListView_button = ccui.ListView:create()
ListView_button:setItemsMargin(50)
ListView_button:setDirection(1)
ListView_button:setGravity(0)
ListView_button:ignoreContentAdaptWithSize(false)
ListView_button:setClippingEnabled(true)
ListView_button:setBackGroundColorOpacity(102)
ListView_button:setLayoutComponentEnabled(true)
ListView_button:setName("ListView_button")
ListView_button:setTag(202)
ListView_button:setCascadeColorEnabled(true)
ListView_button:setCascadeOpacityEnabled(true)
ListView_button:setPosition(378.0000, 335.1346)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_button)
layout:setPositionPercentX(0.3500)
layout:setPositionPercentY(0.1745)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.4427)
layout:setSize({width = 324.0000, height = 850.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(734.8655)
layout:setBottomMargin(335.1346)
Layer:addChild(ListView_button)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(198)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(1505.5910, 1130.1870)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(1.3941)
layout:setPositionPercentY(0.5886)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(1343.5910)
layout:setRightMargin(-587.5906)
layout:setTopMargin(730.8129)
layout:setBottomMargin(1071.1870)
Layer:addChild(Button_1)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[按钮名]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 4)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(199)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4475)
layout:setPercentHeight(0.5254)
layout:setSize({width = 145.0000, height = 62.0000})
layout:setLeftMargin(89.5000)
layout:setRightMargin(89.5000)
layout:setTopMargin(28.0000)
layout:setBottomMargin(28.0000)
Button_1:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000