--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_back:setBackGroundColorOpacity(0)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(282)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_help
local Image_help = ccui.ImageView:create()
Image_help:ignoreContentAdaptWithSize(false)
Image_help:loadTexture("Image/UI/AttrUI/help3.png",0)
Image_help:setLayoutComponentEnabled(true)
Image_help:setName("Image_help")
Image_help:setTag(281)
Image_help:setCascadeColorEnabled(true)
Image_help:setCascadeOpacityEnabled(true)
Image_help:setPosition(540.0000, 450.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_help)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2344)
layout:setPercentWidth(0.8296)
layout:setPercentHeight(0.3125)
layout:setSize({width = 896.0000, height = 600.0000})
layout:setLeftMargin(92.0000)
layout:setRightMargin(92.0000)
layout:setTopMargin(1170.0000)
layout:setBottomMargin(150.0000)
Layer:addChild(Image_help)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(42)
Text_desc:setString([[]])
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(283)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(540.0000, 450.0000)
Text_desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2344)
layout:setPercentWidth(0.7037)
layout:setPercentHeight(0.2500)
layout:setSize({width = 760.0000, height = 480.0000})
layout:setLeftMargin(160.0000)
layout:setRightMargin(160.0000)
layout:setTopMargin(1230.0000)
layout:setBottomMargin(210.0000)
Layer:addChild(Text_desc)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000000