--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(385)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("Font/default.ttf")
Text_1:setFontSize(70)
Text_1:setString([[公  告]])
Text_1:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(677)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(540.0000, 1750.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9115)
layout:setPercentWidth(0.1769)
layout:setPercentHeight(0.0458)
layout:setSize({width = 191.0000, height = 88.0000})
layout:setLeftMargin(444.5000)
layout:setRightMargin(444.5000)
layout:setTopMargin(126.0000)
layout:setBottomMargin(1706.0000)
Layer:addChild(Text_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:ignoreContentAdaptWithSize(false)
Text_2:setFontName("Font/default.ttf")
Text_2:setFontSize(54)
Text_2:setString([[由于我们的失误，服务器出了一些问题。导致很多玩家昨晚进不了游戏。

我们决定给予玩家一定的补偿。

补偿奖励开放时间:
2016/7/5上午06:00-2016/7/6 上午06:00

给大家造成不便，非常抱歉！]])
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setTag(678)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
Text_2:setPosition(540.0000, 1160.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6042)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.4479)
layout:setSize({width = 900.0000, height = 860.0000})
layout:setLeftMargin(90.0000)
layout:setRightMargin(90.0000)
layout:setTopMargin(330.0000)
layout:setBottomMargin(730.0000)
Layer:addChild(Text_2)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(679)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(540.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3385)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1211.0000)
layout:setBottomMargin(591.0000)
Layer:addChild(Button_1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(48)
Text_name:setString([[领取奖励]])
Text_name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(680)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6080)
layout:setPercentHeight(0.5424)
layout:setSize({width = 197.0000, height = 64.0000})
layout:setLeftMargin(63.5000)
layout:setRightMargin(63.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000