--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(true)
Panel_back:setBackGroundColorOpacity(0)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(453)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_Bg
local Image_Bg = cc.Sprite:create("Image/UI/AttrUI/wupingbeibao.png")
Image_Bg:setName("Image_Bg")
Image_Bg:setTag(447)
Image_Bg:setCascadeColorEnabled(true)
Image_Bg:setCascadeOpacityEnabled(true)
Image_Bg:setPosition(540.0000, 971.3907)
Image_Bg:setScaleX(1.3334)
Image_Bg:setScaleY(1.6861)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_Bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5059)
layout:setPercentWidth(0.5963)
layout:setPercentHeight(0.3479)
layout:setSize({width = 644.0000, height = 668.0000})
layout:setLeftMargin(218.0000)
layout:setRightMargin(218.0000)
layout:setTopMargin(614.6094)
layout:setBottomMargin(637.3907)
Image_Bg:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Image_Bg)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(50)
Text_title:setString([[宝物]])
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(448)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(540.0004, 1481.4610)
Text_title:setTextColor({r = 140, g = 140, b = 140})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7716)
layout:setPercentWidth(0.0944)
layout:setPercentHeight(0.0339)
layout:setSize({width = 102.0000, height = 65.0000})
layout:setLeftMargin(489.0004)
layout:setRightMargin(488.9996)
layout:setTopMargin(406.0389)
layout:setBottomMargin(1448.9610)
Layer:addChild(Text_title)

--Create ItemInfoPanel
local ItemInfoPanel = ccui.Layout:create()
ItemInfoPanel:ignoreContentAdaptWithSize(false)
ItemInfoPanel:setClippingEnabled(false)
ItemInfoPanel:setBackGroundColorOpacity(102)
ItemInfoPanel:setTouchEnabled(true);
ItemInfoPanel:setLayoutComponentEnabled(true)
ItemInfoPanel:setName("ItemInfoPanel")
ItemInfoPanel:setTag(449)
ItemInfoPanel:setCascadeColorEnabled(true)
ItemInfoPanel:setCascadeOpacityEnabled(true)
ItemInfoPanel:setAnchorPoint(0.0000, 0.5000)
ItemInfoPanel:setPosition(1328.8230, 1397.5590)
layout = ccui.LayoutComponent:bindLayoutComponent(ItemInfoPanel)
layout:setPositionPercentX(1.2304)
layout:setPositionPercentY(0.7279)
layout:setPercentWidth(0.6525)
layout:setPercentHeight(0.0313)
layout:setSize({width = 704.7500, height = 60.0000})
layout:setLeftMargin(1328.8230)
layout:setRightMargin(-953.5732)
layout:setTopMargin(492.4408)
layout:setBottomMargin(1367.5590)
Layer:addChild(ItemInfoPanel)

--Create Text_Name
local Text_Name = ccui.Text:create()
Text_Name:ignoreContentAdaptWithSize(true)
Text_Name:setTextAreaSize({width = 0, height = 0})
Text_Name:setFontName("Font/default.ttf")
Text_Name:setFontSize(38)
Text_Name:setString([[物品物品]])
Text_Name:setTextVerticalAlignment(1)
Text_Name:setLayoutComponentEnabled(true)
Text_Name:setName("Text_Name")
Text_Name:setTag(450)
Text_Name:setCascadeColorEnabled(true)
Text_Name:setCascadeOpacityEnabled(true)
Text_Name:setAnchorPoint(0.0000, 0.5000)
Text_Name:setPosition(30.5633, 29.0175)
Text_Name:setTextColor({r = 184, g = 184, b = 184})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Name)
layout:setPositionPercentX(0.0434)
layout:setPositionPercentY(0.4836)
layout:setPercentWidth(0.2157)
layout:setPercentHeight(0.7167)
layout:setSize({width = 152.0000, height = 43.0000})
layout:setLeftMargin(30.5633)
layout:setRightMargin(522.1867)
layout:setTopMargin(9.4825)
layout:setBottomMargin(7.5175)
ItemInfoPanel:addChild(Text_Name)

--Create Text_Count
local Text_Count = ccui.Text:create()
Text_Count:ignoreContentAdaptWithSize(true)
Text_Count:setTextAreaSize({width = 0, height = 0})
Text_Count:setFontName("Font/default.ttf")
Text_Count:setFontSize(38)
Text_Count:setString([[40]])
Text_Count:setTextHorizontalAlignment(1)
Text_Count:setTextVerticalAlignment(1)
Text_Count:setLayoutComponentEnabled(true)
Text_Count:setName("Text_Count")
Text_Count:setTag(451)
Text_Count:setCascadeColorEnabled(true)
Text_Count:setCascadeOpacityEnabled(true)
Text_Count:setAnchorPoint(0.0000, 0.5000)
Text_Count:setPosition(604.3298, 29.0175)
Text_Count:setTextColor({r = 184, g = 184, b = 184})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Count)
layout:setPositionPercentX(0.8575)
layout:setPositionPercentY(0.4836)
layout:setPercentWidth(0.0667)
layout:setPercentHeight(0.7167)
layout:setSize({width = 47.0000, height = 43.0000})
layout:setLeftMargin(604.3298)
layout:setRightMargin(53.4202)
layout:setTopMargin(9.4825)
layout:setBottomMargin(7.5175)
ItemInfoPanel:addChild(Text_Count)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorOpacity(102)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(452)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(539.9760, 956.3343)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4981)
layout:setPercentWidth(0.6763)
layout:setPercentHeight(0.4974)
layout:setSize({width = 730.3519, height = 955.0355})
layout:setLeftMargin(174.8000)
layout:setRightMargin(174.8481)
layout:setTopMargin(486.1479)
layout:setBottomMargin(478.8165)
Layer:addChild(ListView_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000000000000