--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(128)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(81)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/TaskUI/kuang.png",0)
Image_kuang:setScale9Enabled(true)
Image_kuang:setCapInsets({x = 341, y = 231, width = 352, height = 238})
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(80)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(540.0031, 1054.9900)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5495)
layout:setPercentWidth(0.9574)
layout:setPercentHeight(0.6250)
layout:setSize({width = 1034.0000, height = 1200.0000})
layout:setLeftMargin(23.0031)
layout:setRightMargin(22.9969)
layout:setTopMargin(265.0101)
layout:setBottomMargin(454.9899)
Layer:addChild(Image_kuang)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(60)
Text_title:setString([[温馨提醒]])
Text_title:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(82)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(512.7230, 1099.4290)
Text_title:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.4959)
layout:setPositionPercentY(0.9162)
layout:setPercentWidth(0.2379)
layout:setPercentHeight(0.0642)
layout:setSize({width = 246.0000, height = 77.0000})
layout:setLeftMargin(389.7230)
layout:setRightMargin(398.2770)
layout:setTopMargin(62.0713)
layout:setBottomMargin(1060.9290)
Image_kuang:addChild(Text_title)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(38)
Text_desc:setString([[      根据国家新闻出版署规定，游戏公司需要针对未成年人过度使用甚至沉迷网络游戏问题，进一步严格管理措施，在坚决防止未成年人沉迷网络游戏，切实保护未成年人身心健康。
      故此所有网络游戏企业仅可在周五、周六、周日和法定节假日每日20时至21时向未成年人提供1小时服务，其他时间均不得以任何形式向未成年人提供网络游戏服务。
      在此准则下，《放置江湖》在周一至周四内，将禁止未成年人登录本游戏，并且在周五至周日的20时至21时，开放给予未成年人登录游戏，希望未成年人专注学习，努力学习。]])
Text_desc:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(77)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(517.0000, 711.2144)
Text_desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5927)
layout:setPercentWidth(0.9478)
layout:setPercentHeight(0.5000)
layout:setSize({width = 980.0000, height = 600.0000})
layout:setLeftMargin(27.0000)
layout:setRightMargin(27.0000)
layout:setTopMargin(188.7856)
layout:setBottomMargin(411.2144)
Image_kuang:addChild(Text_desc)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(46)
Text_name:setString([[放置江湖开发组]])
Text_name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(83)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(820.1804, 340.0511)
Text_name:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.7932)
layout:setPositionPercentY(0.2834)
layout:setPercentWidth(0.3172)
layout:setPercentHeight(0.0517)
layout:setSize({width = 328.0000, height = 62.0000})
layout:setLeftMargin(656.1804)
layout:setRightMargin(49.8196)
layout:setTopMargin(828.9489)
layout:setBottomMargin(309.0511)
Image_kuang:addChild(Text_name)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_close:setTitleFontName("Font/default.ttf")
Button_close:setTitleFontSize(48)
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(78)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setPosition(514.6871, 126.3050)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentX(0.4978)
layout:setPositionPercentY(0.1053)
layout:setPercentWidth(0.3133)
layout:setPercentHeight(0.0983)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(352.6871)
layout:setRightMargin(357.3129)
layout:setTopMargin(1014.6950)
layout:setBottomMargin(67.3050)
Image_kuang:addChild(Button_close)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[确定]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(79)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3179)
layout:setPercentHeight(0.5424)
layout:setSize({width = 103.0000, height = 64.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_close:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000