--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back4
local Panel_back4 = ccui.Layout:create()
Panel_back4:ignoreContentAdaptWithSize(false)
Panel_back4:setClippingEnabled(false)
Panel_back4:setBackGroundColorType(1)
Panel_back4:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back4:setBackGroundColorOpacity(229)
Panel_back4:setTouchEnabled(true);
Panel_back4:setLayoutComponentEnabled(true)
Panel_back4:setName("Panel_back4")
Panel_back4:setTag(42)
Panel_back4:setCascadeColorEnabled(true)
Panel_back4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back4)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back4)

--Create Image_48
local Image_48 = ccui.ImageView:create()
Image_48:ignoreContentAdaptWithSize(false)
Image_48:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_48:setLayoutComponentEnabled(true)
Image_48:setName("Image_48")
Image_48:setTag(92)
Image_48:setCascadeColorEnabled(true)
Image_48:setCascadeOpacityEnabled(true)
Image_48:setPosition(540.0000, 1179.1490)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_48)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6141)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(111.8513)
layout:setBottomMargin(550.1487)
Layer:addChild(Image_48)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(70)
Text_title:setString([[师门清规]])
Text_title:setTextHorizontalAlignment(1)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(178)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(524.0000, 1174.0000)
Text_title:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9332)
layout:setPercentWidth(0.2729)
layout:setPercentHeight(0.0723)
layout:setSize({width = 286.0000, height = 91.0000})
layout:setLeftMargin(381.0000)
layout:setRightMargin(381.0000)
layout:setTopMargin(38.5000)
layout:setBottomMargin(1128.5000)
Image_48:addChild(Text_title)

--Create Text_dsc1
local Text_dsc1 = ccui.Text:create()
Text_dsc1:ignoreContentAdaptWithSize(false)
Text_dsc1:setFontName("Font/HYCFS.ttf")
Text_dsc1:setFontSize(48)
Text_dsc1:setString([[我派遵初真十戒，忠、孝、济世、守身、节俭、利人、清修。
我派弟子，不得陷于贪求无厌之欲。
凡武当中人，当以行侠仗义，匡扶正道为己
任。
]])
Text_dsc1:setLayoutComponentEnabled(true)
Text_dsc1:setName("Text_dsc1")
Text_dsc1:setTag(179)
Text_dsc1:setCascadeColorEnabled(true)
Text_dsc1:setCascadeOpacityEnabled(true)
Text_dsc1:setAnchorPoint(0.5000, 1.0000)
Text_dsc1:setPosition(524.0000, 815.0000)
Text_dsc1:setTextColor({r = 102, g = 153, b = 153})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_dsc1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6479)
layout:setPercentWidth(0.8111)
layout:setPercentHeight(0.2957)
layout:setSize({width = 850.0000, height = 372.0000})
layout:setLeftMargin(99.0000)
layout:setRightMargin(99.0000)
layout:setTopMargin(443.0000)
layout:setBottomMargin(443.0000)
Image_48:addChild(Text_dsc1)

--Create Text_dsc2
local Text_dsc2 = ccui.Text:create()
Text_dsc2:ignoreContentAdaptWithSize(false)
Text_dsc2:setFontName("Font/default.ttf")
Text_dsc2:setFontSize(42)
Text_dsc2:setString([[师门任务说明：
每日可完成数量有上限；每天凌晨5点重置，未
完成的任务清空；
每日师门任务可获得贡献度最多4000点；
有几率获得其他物品奖励如技能残页；
一般来说，任务颜色品质越高，奖励越好。橙色
最优，紫色次之，蓝色再次之，绿色最差；
有些任务可以指派出去由其他同门代劳；每日可
指派次数有上限。
任务领取后可以放弃，但是放弃后需要经过5分钟后方可再接取。]])
Text_dsc2:setLayoutComponentEnabled(true)
Text_dsc2:setName("Text_dsc2")
Text_dsc2:setTag(180)
Text_dsc2:setCascadeColorEnabled(true)
Text_dsc2:setCascadeOpacityEnabled(true)
Text_dsc2:setPosition(529.0000, 629.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_dsc2)
layout:setPositionPercentX(0.5048)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8588)
layout:setPercentHeight(0.4213)
layout:setSize({width = 900.0000, height = 530.0000})
layout:setLeftMargin(79.0000)
layout:setRightMargin(69.0000)
layout:setTopMargin(364.0000)
layout:setBottomMargin(364.0000)
Image_48:addChild(Text_dsc2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000