--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(178)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(418)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 1.0000)
Panel_back:setPosition(540.0000, 1920.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Pnl_item1
local Pnl_item1 = ccui.Layout:create()
Pnl_item1:ignoreContentAdaptWithSize(false)
Pnl_item1:setClippingEnabled(true)
Pnl_item1:setBackGroundColorOpacity(102)
Pnl_item1:setLayoutComponentEnabled(true)
Pnl_item1:setName("Pnl_item1")
Pnl_item1:setTag(412)
Pnl_item1:setCascadeColorEnabled(true)
Pnl_item1:setCascadeOpacityEnabled(true)
Pnl_item1:setPosition(440.6423, 2416.8350)
layout = ccui.LayoutComponent:bindLayoutComponent(Pnl_item1)
layout:setPositionPercentX(0.4080)
layout:setPositionPercentY(1.2588)
layout:setPercentWidth(0.9259)
layout:setPercentHeight(0.1865)
layout:setSize({width = 1000.0000, height = 358.0000})
layout:setLeftMargin(440.6423)
layout:setRightMargin(-360.6423)
layout:setTopMargin(-854.8354)
layout:setBottomMargin(2416.8350)
Layer:addChild(Pnl_item1)

--Create Text_detailTitle
local Text_detailTitle = ccui.Text:create()
Text_detailTitle:ignoreContentAdaptWithSize(false)
Text_detailTitle:setFontName("Font/default.ttf")
Text_detailTitle:setFontSize(48)
Text_detailTitle:setString([[第一重]])
Text_detailTitle:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_detailTitle:setLayoutComponentEnabled(true)
Text_detailTitle:setName("Text_detailTitle")
Text_detailTitle:setTag(413)
Text_detailTitle:setCascadeColorEnabled(true)
Text_detailTitle:setCascadeOpacityEnabled(true)
Text_detailTitle:setAnchorPoint(0.0000, 1.0000)
Text_detailTitle:setPosition(22.3821, 333.3424)
Text_detailTitle:setTextColor({r = 255, g = 235, b = 58})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_detailTitle)
layout:setPositionPercentX(0.0224)
layout:setPositionPercentY(0.9311)
layout:setPercentWidth(0.6400)
layout:setPercentHeight(0.1676)
layout:setSize({width = 640.0000, height = 60.0000})
layout:setLeftMargin(22.3821)
layout:setRightMargin(337.6179)
layout:setTopMargin(24.6576)
layout:setBottomMargin(273.3424)
Pnl_item1:addChild(Text_detailTitle)

--Create Text_detailDsc
local Text_detailDsc = ccui.Text:create()
Text_detailDsc:ignoreContentAdaptWithSize(false)
Text_detailDsc:setFontName("Font/default.ttf")
Text_detailDsc:setFontSize(36)
Text_detailDsc:setString([[]])
Text_detailDsc:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_detailDsc:setLayoutComponentEnabled(true)
Text_detailDsc:setName("Text_detailDsc")
Text_detailDsc:setTag(414)
Text_detailDsc:setCascadeColorEnabled(true)
Text_detailDsc:setCascadeOpacityEnabled(true)
Text_detailDsc:setPosition(500.5000, 123.5099)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_detailDsc)
layout:setPositionPercentX(0.5005)
layout:setPositionPercentY(0.3450)
layout:setPercentWidth(0.9550)
layout:setPercentHeight(0.5587)
layout:setSize({width = 955.0000, height = 200.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(22.0000)
layout:setTopMargin(134.4901)
layout:setBottomMargin(23.5099)
Pnl_item1:addChild(Text_detailDsc)

--Create Img_bg
local Img_bg = ccui.ImageView:create()
Img_bg:ignoreContentAdaptWithSize(false)
Img_bg:loadTexture("Image/UI/SkillUI/teshuwugongbeijing.png",0)
Img_bg:setTouchEnabled(true);
Img_bg:setLayoutComponentEnabled(true)
Img_bg:setName("Img_bg")
Img_bg:setTag(408)
Img_bg:setCascadeColorEnabled(true)
Img_bg:setCascadeOpacityEnabled(true)
Img_bg:setAnchorPoint(0.0000, 0.0000)
Img_bg:setPosition(41.0400, 510.9100)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_bg)
layout:setPositionPercentX(0.0380)
layout:setPositionPercentY(0.2661)
layout:setPercentWidth(0.9426)
layout:setPercentHeight(0.6250)
layout:setSize({width = 1018.0000, height = 1200.0000})
layout:setLeftMargin(41.0400)
layout:setRightMargin(20.9600)
layout:setTopMargin(209.0900)
layout:setBottomMargin(510.9100)
Layer:addChild(Img_bg)

--Create ListView_Details
local ListView_Details = ccui.ListView:create()
ListView_Details:setDirection(1)
ListView_Details:setGravity(2)
ListView_Details:ignoreContentAdaptWithSize(false)
ListView_Details:setClippingEnabled(true)
ListView_Details:setBackGroundColorOpacity(102)
ListView_Details:setTouchEnabled(false);
ListView_Details:setLayoutComponentEnabled(true)
ListView_Details:setName("ListView_Details")
ListView_Details:setTag(422)
ListView_Details:setCascadeColorEnabled(true)
ListView_Details:setCascadeOpacityEnabled(true)
ListView_Details:setAnchorPoint(0.0000, 1.0000)
ListView_Details:setPosition(46.9122, 1304.7190)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_Details)
layout:setPositionPercentX(0.0434)
layout:setPositionPercentY(0.6795)
layout:setPercentWidth(0.9289)
layout:setPercentHeight(0.3775)
layout:setSize({width = 1003.2240, height = 724.8929})
layout:setLeftMargin(46.9122)
layout:setRightMargin(29.8637)
layout:setTopMargin(615.2805)
layout:setBottomMargin(579.8266)
Layer:addChild(ListView_Details)

--Create Txt_Title
local Txt_Title = ccui.Text:create()
Txt_Title:ignoreContentAdaptWithSize(true)
Txt_Title:setTextAreaSize({width = 0, height = 0})
Txt_Title:setFontName("Font/default.ttf")
Txt_Title:setFontSize(48)
Txt_Title:setString([[武学名称]])
Txt_Title:enableOutline({r = 31, g = 31, b = 31, a = 255}, 5)
Txt_Title:setLayoutComponentEnabled(true)
Txt_Title:setName("Txt_Title")
Txt_Title:setTag(423)
Txt_Title:setCascadeColorEnabled(true)
Txt_Title:setCascadeOpacityEnabled(true)
Txt_Title:setAnchorPoint(0.0000, 0.5000)
Txt_Title:setPosition(67.7507, 1637.1630)
Txt_Title:setTextColor({r = 140, g = 234, b = 234})
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_Title)
layout:setPositionPercentX(0.0627)
layout:setPositionPercentY(0.8527)
layout:setPercentWidth(0.1843)
layout:setPercentHeight(0.0333)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(67.7507)
layout:setRightMargin(813.2493)
layout:setTopMargin(250.8369)
layout:setBottomMargin(1605.1630)
Layer:addChild(Txt_Title)

--Create Txt_Exp
local Txt_Exp = ccui.Text:create()
Txt_Exp:ignoreContentAdaptWithSize(true)
Txt_Exp:setTextAreaSize({width = 0, height = 0})
Txt_Exp:setFontName("Font/default.ttf")
Txt_Exp:setFontSize(48)
Txt_Exp:setString([[999/999级]])
Txt_Exp:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Txt_Exp:setLayoutComponentEnabled(true)
Txt_Exp:setName("Txt_Exp")
Txt_Exp:setTag(424)
Txt_Exp:setCascadeColorEnabled(true)
Txt_Exp:setCascadeOpacityEnabled(true)
Txt_Exp:setAnchorPoint(1.0000, 1.0000)
Txt_Exp:setPosition(1009.5230, 1669.1660)
Txt_Exp:setTextColor({r = 140, g = 234, b = 234})
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_Exp)
layout:setPositionPercentX(0.9347)
layout:setPositionPercentY(0.8694)
layout:setPercentWidth(0.2343)
layout:setPercentHeight(0.0333)
layout:setSize({width = 253.0000, height = 64.0000})
layout:setLeftMargin(756.5231)
layout:setRightMargin(70.4769)
layout:setTopMargin(250.8337)
layout:setBottomMargin(1605.1660)
Layer:addChild(Txt_Exp)

--Create Txt_DetailDsc
local Txt_DetailDsc = ccui.Text:create()
Txt_DetailDsc:ignoreContentAdaptWithSize(false)
Txt_DetailDsc:setFontName("Font/default.ttf")
Txt_DetailDsc:setFontSize(36)
Txt_DetailDsc:setString([[武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述武学描述]])
Txt_DetailDsc:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Txt_DetailDsc:setLayoutComponentEnabled(true)
Txt_DetailDsc:setName("Txt_DetailDsc")
Txt_DetailDsc:setTag(425)
Txt_DetailDsc:setCascadeColorEnabled(true)
Txt_DetailDsc:setCascadeOpacityEnabled(true)
Txt_DetailDsc:setAnchorPoint(0.0000, 1.0000)
Txt_DetailDsc:setPosition(67.7543, 1552.5680)
Txt_DetailDsc:setTextColor({r = 167, g = 167, b = 167})
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_DetailDsc)
layout:setPositionPercentX(0.0627)
layout:setPositionPercentY(0.8086)
layout:setPercentWidth(0.8889)
layout:setPercentHeight(0.1250)
layout:setSize({width = 960.0000, height = 240.0000})
layout:setLeftMargin(67.7543)
layout:setRightMargin(52.2457)
layout:setTopMargin(367.4319)
layout:setBottomMargin(1312.5680)
Layer:addChild(Txt_DetailDsc)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000