--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(83)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_Desc
local Text_Desc = ccui.Text:create()
Text_Desc:ignoreContentAdaptWithSize(false)
Text_Desc:setFontName("Font/default.ttf")
Text_Desc:setFontSize(60)
Text_Desc:setString([[]])
Text_Desc:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_Desc:setLayoutComponentEnabled(true)
Text_Desc:setName("Text_Desc")
Text_Desc:setTag(11)
Text_Desc:setCascadeColorEnabled(true)
Text_Desc:setCascadeOpacityEnabled(true)
Text_Desc:setPosition(542.2119, 1477.5010)
Text_Desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Desc)
layout:setPositionPercentX(0.5020)
layout:setPositionPercentY(0.7695)
layout:setPercentWidth(0.7926)
layout:setPercentHeight(0.1563)
layout:setSize({width = 856.0000, height = 300.0000})
layout:setLeftMargin(114.2119)
layout:setRightMargin(109.7881)
layout:setTopMargin(292.4988)
layout:setBottomMargin(1327.5010)
Layer:addChild(Text_Desc)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/QuestionAndAnswerUI/btn1.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 363, y = 33, width = 131, height = 25})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(253)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(1788.9530, 1321.2010)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(1.6564)
layout:setPositionPercentY(0.6881)
layout:setPercentWidth(0.7630)
layout:setPercentHeight(0.0635)
layout:setSize({width = 824.0000, height = 122.0000})
layout:setLeftMargin(1376.9530)
layout:setRightMargin(-1120.9530)
layout:setTopMargin(537.7991)
layout:setBottomMargin(1260.2010)
Layer:addChild(Button_1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(48)
Text_name:setString([[准备类型]])
Text_name:setTextHorizontalAlignment(1)
Text_name:setTextVerticalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(254)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(412.0000, 61.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2403)
layout:setPercentHeight(0.5246)
layout:setSize({width = 198.0000, height = 64.0000})
layout:setLeftMargin(313.0000)
layout:setRightMargin(313.0000)
layout:setTopMargin(29.0000)
layout:setBottomMargin(29.0000)
Button_1:addChild(Text_name)

--Create ListView_prepare
local ListView_prepare = ccui.ListView:create()
ListView_prepare:setItemsMargin(120)
ListView_prepare:setDirection(1)
ListView_prepare:setGravity(2)
ListView_prepare:ignoreContentAdaptWithSize(false)
ListView_prepare:setClippingEnabled(true)
ListView_prepare:setBackGroundColorOpacity(102)
ListView_prepare:setLayoutComponentEnabled(true)
ListView_prepare:setName("ListView_prepare")
ListView_prepare:setTag(10)
ListView_prepare:setCascadeColorEnabled(true)
ListView_prepare:setCascadeOpacityEnabled(true)
ListView_prepare:setPosition(0.0000, 481.0284)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_prepare)
layout:setPositionPercentY(0.2505)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3646)
layout:setSize({width = 1080.0000, height = 700.0000})
layout:setTopMargin(738.9717)
layout:setBottomMargin(481.0284)
Layer:addChild(ListView_prepare)

--Create Button_cancel
local Button_cancel = ccui.Button:create()
Button_cancel:ignoreContentAdaptWithSize(false)
Button_cancel:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_cancel:setTitleFontName("Font/default.ttf")
Button_cancel:setTitleFontSize(48)
Button_cancel:setScale9Enabled(true)
Button_cancel:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_cancel:setLayoutComponentEnabled(true)
Button_cancel:setName("Button_cancel")
Button_cancel:setTag(200)
Button_cancel:setCascadeColorEnabled(true)
Button_cancel:setCascadeOpacityEnabled(true)
Button_cancel:setPosition(540.0001, 362.6457)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_cancel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1889)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0001)
layout:setRightMargin(377.9999)
layout:setTopMargin(1498.3540)
layout:setBottomMargin(303.6457)
Layer:addChild(Button_cancel)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[取消]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(201)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_cancel:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000000000