--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_4
local Panel_4 = ccui.Layout:create()
Panel_4:ignoreContentAdaptWithSize(false)
Panel_4:setClippingEnabled(false)
Panel_4:setBackGroundColorType(1)
Panel_4:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_4:setTouchEnabled(true);
Panel_4:setLayoutComponentEnabled(true)
Panel_4:setName("Panel_4")
Panel_4:setTag(73)
Panel_4:setCascadeColorEnabled(true)
Panel_4:setCascadeOpacityEnabled(true)
Panel_4:setAnchorPoint(0.5000, 0.5000)
Panel_4:setPosition(540.0000, 1233.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6422)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7156)
layout:setSize({width = 1080.0000, height = 1374.0000})
layout:setBottomMargin(546.0000)
Layer:addChild(Panel_4)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(470)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1175.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(115.9900)
layout:setBottomMargin(546.0100)
Layer:addChild(Image_back)

--Create Panel_dscArea
local Panel_dscArea = ccui.Layout:create()
Panel_dscArea:ignoreContentAdaptWithSize(false)
Panel_dscArea:setClippingEnabled(false)
Panel_dscArea:setBackGroundColorOpacity(102)
Panel_dscArea:setTouchEnabled(true);
Panel_dscArea:setLayoutComponentEnabled(true)
Panel_dscArea:setName("Panel_dscArea")
Panel_dscArea:setTag(78)
Panel_dscArea:setCascadeColorEnabled(true)
Panel_dscArea:setCascadeOpacityEnabled(true)
Panel_dscArea:setAnchorPoint(0.5000, 1.0000)
Panel_dscArea:setPosition(526.0000, 1045.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_dscArea)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.8307)
layout:setPercentWidth(0.8111)
layout:setPercentHeight(0.3975)
layout:setSize({width = 850.0000, height = 500.0000})
layout:setLeftMargin(101.0000)
layout:setRightMargin(97.0000)
layout:setTopMargin(213.0000)
layout:setBottomMargin(545.0000)
Image_back:addChild(Panel_dscArea)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(false)
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(48)
Text_title:setString([[谷虚道长]])
Text_title:setTextHorizontalAlignment(1)
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(79)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(526.0000, 1125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.8943)
layout:setPercentWidth(0.8111)
layout:setPercentHeight(0.0509)
layout:setSize({width = 850.0000, height = 64.0000})
layout:setLeftMargin(101.0000)
layout:setRightMargin(97.0000)
layout:setTopMargin(101.0000)
layout:setBottomMargin(1093.0000)
Image_back:addChild(Text_title)

--Create Image_tiao
local Image_tiao = ccui.ImageView:create()
Image_tiao:ignoreContentAdaptWithSize(false)
Image_tiao:loadTexture("Image/UI/PopUI/shiqitiao.png",0)
Image_tiao:setScale9Enabled(true)
Image_tiao:setCapInsets({x = 248, y = 6, width = 256, height = 8})
Image_tiao:setLayoutComponentEnabled(true)
Image_tiao:setName("Image_tiao")
Image_tiao:setTag(185)
Image_tiao:setCascadeColorEnabled(true)
Image_tiao:setCascadeOpacityEnabled(true)
Image_tiao:setPosition(540.0000, 486.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tiao)
layout:setPositionPercentX(0.5153)
layout:setPositionPercentY(0.3863)
layout:setPercentWidth(0.7176)
layout:setPercentHeight(0.0175)
layout:setSize({width = 752.0000, height = 22.0000})
layout:setLeftMargin(164.0000)
layout:setRightMargin(132.0000)
layout:setTopMargin(761.0000)
layout:setBottomMargin(475.0000)
Image_back:addChild(Image_tiao)

--Create Button_paimapi
local Button_paimapi = ccui.Button:create()
Button_paimapi:ignoreContentAdaptWithSize(false)
Button_paimapi:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_paimapi:setTitleFontSize(14)
Button_paimapi:setTitleColor({r = 65, g = 65, b = 70})
Button_paimapi:setScale9Enabled(true)
Button_paimapi:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_paimapi:setLayoutComponentEnabled(true)
Button_paimapi:setName("Button_paimapi")
Button_paimapi:setTag(186)
Button_paimapi:setCascadeColorEnabled(true)
Button_paimapi:setCascadeOpacityEnabled(true)
Button_paimapi:setPosition(540.0000, 275.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_paimapi)
layout:setPositionPercentX(0.5153)
layout:setPositionPercentY(0.2186)
layout:setPercentWidth(0.3092)
layout:setPercentHeight(0.0938)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(346.0000)
layout:setTopMargin(924.0000)
layout:setBottomMargin(216.0000)
Image_back:addChild(Button_paimapi)

--Create Text_pokedex_button_text
local Text_pokedex_button_text = ccui.Text:create()
Text_pokedex_button_text:ignoreContentAdaptWithSize(true)
Text_pokedex_button_text:setTextAreaSize({width = 0, height = 0})
Text_pokedex_button_text:setFontName("Font/default.ttf")
Text_pokedex_button_text:setFontSize(54)
Text_pokedex_button_text:setString([[拍马屁]])
Text_pokedex_button_text:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_pokedex_button_text:setLayoutComponentEnabled(true)
Text_pokedex_button_text:setName("Text_pokedex_button_text")
Text_pokedex_button_text:setTag(187)
Text_pokedex_button_text:setCascadeColorEnabled(true)
Text_pokedex_button_text:setCascadeOpacityEnabled(true)
Text_pokedex_button_text:setPosition(162.0000, 59.0000)
Text_pokedex_button_text:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_pokedex_button_text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5185)
layout:setPercentHeight(0.5932)
layout:setSize({width = 168.0000, height = 70.0000})
layout:setLeftMargin(78.0000)
layout:setRightMargin(78.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
Button_paimapi:addChild(Text_pokedex_button_text)

--Create Panel_kuang
local Panel_kuang = ccui.Layout:create()
Panel_kuang:ignoreContentAdaptWithSize(false)
Panel_kuang:setBackGroundImage("Image/UI/TeacherTask/mubiqoquyu.png",0)
Panel_kuang:setClippingEnabled(false)
Panel_kuang:setBackGroundColorType(1)
Panel_kuang:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_kuang:setBackGroundColorOpacity(102)
Panel_kuang:setTouchEnabled(true);
Panel_kuang:setLayoutComponentEnabled(true)
Panel_kuang:setName("Panel_kuang")
Panel_kuang:setTag(190)
Panel_kuang:setCascadeColorEnabled(true)
Panel_kuang:setCascadeOpacityEnabled(true)
Panel_kuang:setAnchorPoint(0.5000, 0.5000)
Panel_kuang:setPosition(881.0000, 486.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_kuang)
layout:setPositionPercentX(0.8406)
layout:setPositionPercentY(0.3863)
layout:setPercentWidth(0.0668)
layout:setPercentHeight(0.0175)
layout:setSize({width = 70.0000, height = 22.0000})
layout:setLeftMargin(846.0000)
layout:setRightMargin(132.0000)
layout:setTopMargin(761.0000)
layout:setBottomMargin(475.0000)
Image_back:addChild(Panel_kuang)

--Create Panel_move
local Panel_move = ccui.Layout:create()
Panel_move:ignoreContentAdaptWithSize(false)
Panel_move:setBackGroundImage("Image/UI/TeacherTask/sanjiao.png",0)
Panel_move:setClippingEnabled(false)
Panel_move:setBackGroundColorOpacity(102)
Panel_move:setTouchEnabled(true);
Panel_move:setLayoutComponentEnabled(true)
Panel_move:setName("Panel_move")
Panel_move:setTag(189)
Panel_move:setCascadeColorEnabled(true)
Panel_move:setCascadeOpacityEnabled(true)
Panel_move:setAnchorPoint(0.5000, 0.5000)
Panel_move:setPosition(164.0000, 486.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_move)
layout:setPositionPercentX(0.1565)
layout:setPositionPercentY(0.3863)
layout:setPercentWidth(0.0143)
layout:setPercentHeight(0.0238)
layout:setSize({width = 15.0000, height = 30.0000})
layout:setLeftMargin(156.5000)
layout:setRightMargin(876.5000)
layout:setTopMargin(757.0000)
layout:setBottomMargin(471.0000)
Image_back:addChild(Panel_move)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000