--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_4
local Panel_4 = ccui.Layout:create()
Panel_4:ignoreContentAdaptWithSize(false)
Panel_4:setClippingEnabled(false)
Panel_4:setBackGroundColorType(1)
Panel_4:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_4:setTouchEnabled(true);
Panel_4:setLayoutComponentEnabled(true)
Panel_4:setName("Panel_4")
Panel_4:setTag(46)
Panel_4:setCascadeColorEnabled(true)
Panel_4:setCascadeOpacityEnabled(true)
Panel_4:setAnchorPoint(0.5000, 0.5000)
Panel_4:setPosition(540.0000, 1233.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6422)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7156)
layout:setSize({width = 1080.0000, height = 1374.0000})
layout:setBottomMargin(546.0000)
Layer:addChild(Panel_4)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(60)
Text_title:setString([[官府缉凶]])
Text_title:setTextHorizontalAlignment(1)
Text_title:setTextVerticalAlignment(1)
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(58)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(540.0000, 1862.0000)
Text_title:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9698)
layout:setPercentWidth(0.2222)
layout:setPercentHeight(0.0365)
layout:setSize({width = 240.0000, height = 70.0000})
layout:setLeftMargin(420.0000)
layout:setRightMargin(420.0000)
layout:setTopMargin(23.0000)
layout:setBottomMargin(1827.0000)
Layer:addChild(Text_title)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(45)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1175.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(115.9900)
layout:setBottomMargin(546.0100)
Layer:addChild(Image_back)

--Create Text_dsc
local Text_dsc = ccui.Text:create()
Text_dsc:ignoreContentAdaptWithSize(false)
Text_dsc:setFontName("Font/default.ttf")
Text_dsc:setFontSize(42)
Text_dsc:setString([[Text Label]])
Text_dsc:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_dsc:setLayoutComponentEnabled(true)
Text_dsc:setName("Text_dsc")
Text_dsc:setTag(59)
Text_dsc:setCascadeColorEnabled(true)
Text_dsc:setCascadeOpacityEnabled(true)
Text_dsc:setPosition(540.0083, 1546.0500)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_dsc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8052)
layout:setPercentWidth(0.7870)
layout:setPercentHeight(0.1563)
layout:setSize({width = 850.0000, height = 300.0000})
layout:setLeftMargin(115.0083)
layout:setRightMargin(114.9917)
layout:setTopMargin(223.9496)
layout:setBottomMargin(1396.0500)
Layer:addChild(Text_dsc)

--Create Button_panwen
local Button_panwen = ccui.Button:create()
Button_panwen:ignoreContentAdaptWithSize(false)
Button_panwen:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_panwen:setTitleFontSize(14)
Button_panwen:setTitleColor({r = 65, g = 65, b = 70})
Button_panwen:setScale9Enabled(true)
Button_panwen:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_panwen:setLayoutComponentEnabled(true)
Button_panwen:setName("Button_panwen")
Button_panwen:setTag(69)
Button_panwen:setCascadeColorEnabled(true)
Button_panwen:setCascadeOpacityEnabled(true)
Button_panwen:setPosition(540.0000, 912.5276)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_panwen)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4753)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(948.4724)
layout:setBottomMargin(853.5276)
Layer:addChild(Button_panwen)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/default.ttf")
Text_ButtonName:setFontSize(54)
Text_ButtonName:setString([[拦住盘问]])
Text_ButtonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(70)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(162.0000, 59.0000)
Text_ButtonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6759)
layout:setPercentHeight(0.5932)
layout:setSize({width = 219.0000, height = 70.0000})
layout:setLeftMargin(52.5000)
layout:setRightMargin(52.5000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
Button_panwen:addChild(Text_ButtonName)

--Create Button_fangxing
local Button_fangxing = ccui.Button:create()
Button_fangxing:ignoreContentAdaptWithSize(false)
Button_fangxing:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_fangxing:setTitleFontSize(14)
Button_fangxing:setTitleColor({r = 65, g = 65, b = 70})
Button_fangxing:setScale9Enabled(true)
Button_fangxing:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_fangxing:setLayoutComponentEnabled(true)
Button_fangxing:setName("Button_fangxing")
Button_fangxing:setTag(71)
Button_fangxing:setCascadeColorEnabled(true)
Button_fangxing:setCascadeOpacityEnabled(true)
Button_fangxing:setPosition(540.0000, 689.6159)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_fangxing)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3592)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1171.3840)
layout:setBottomMargin(630.6159)
Layer:addChild(Button_fangxing)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/default.ttf")
Text_ButtonName:setFontSize(54)
Text_ButtonName:setString([[放行]])
Text_ButtonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(72)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(162.0000, 59.0000)
Text_ButtonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3519)
layout:setPercentHeight(0.5932)
layout:setSize({width = 114.0000, height = 70.0000})
layout:setLeftMargin(105.0000)
layout:setRightMargin(105.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(24.0000)
Button_fangxing:addChild(Text_ButtonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000