--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(279)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create ListView_map
local ListView_map = ccui.ListView:create()
ListView_map:setItemsMargin(5)
ListView_map:setDirection(1)
ListView_map:setGravity(2)
ListView_map:ignoreContentAdaptWithSize(false)
ListView_map:setClippingEnabled(true)
ListView_map:setBackGroundColorOpacity(102)
ListView_map:setLayoutComponentEnabled(true)
ListView_map:setName("ListView_map")
ListView_map:setTag(148)
ListView_map:setCascadeColorEnabled(true)
ListView_map:setCascadeOpacityEnabled(true)
ListView_map:setPosition(13.9996, 270.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_map)
layout:setPositionPercentX(0.0130)
layout:setPositionPercentY(0.1406)
layout:setPercentWidth(0.9741)
layout:setPercentHeight(0.7813)
layout:setSize({width = 1052.0000, height = 1500.0000})
layout:setLeftMargin(13.9996)
layout:setRightMargin(14.0004)
layout:setTopMargin(150.0000)
layout:setBottomMargin(270.0000)
Layer:addChild(ListView_map)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(60)
Text_title:setString([[鹊起无名卷]])
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(772)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(540.0000, 1866.5460)
Text_title:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9722)
layout:setPercentWidth(0.2889)
layout:setPercentHeight(0.0458)
layout:setSize({width = 312.0000, height = 88.0000})
layout:setLeftMargin(384.0000)
layout:setRightMargin(384.0000)
layout:setTopMargin(9.4541)
layout:setBottomMargin(1822.5460)
Layer:addChild(Text_title)

--Create Button_back_JH
local Button_back_JH = ccui.Button:create()
Button_back_JH:ignoreContentAdaptWithSize(false)
Button_back_JH:loadTextureNormal("Image/UI/MenuUI/back.png",0)
Button_back_JH:loadTexturePressed("Image/UI/MenuUI/back2.png",0)
Button_back_JH:setTitleFontSize(48)
Button_back_JH:setTitleColor({r = 208, g = 208, b = 208})
Button_back_JH:setFlippedX(true)
Button_back_JH:setLayoutComponentEnabled(true)
Button_back_JH:setName("Button_back_JH")
Button_back_JH:setTag(459)
Button_back_JH:setCascadeColorEnabled(true)
Button_back_JH:setCascadeOpacityEnabled(true)
Button_back_JH:setPosition(981.5359, 1862.8300)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back_JH)
layout:setPositionPercentX(0.9088)
layout:setPositionPercentY(0.9702)
layout:setPercentWidth(0.1620)
layout:setPercentHeight(0.0406)
layout:setSize({width = 175.0000, height = 78.0000})
layout:setLeftMargin(894.0359)
layout:setRightMargin(10.9641)
layout:setTopMargin(18.1700)
layout:setBottomMargin(1823.8300)
Layer:addChild(Button_back_JH)

--Create Panel_Button
local Panel_Button = ccui.Layout:create()
Panel_Button:ignoreContentAdaptWithSize(false)
Panel_Button:setClippingEnabled(false)
Panel_Button:setTouchEnabled(true);
Panel_Button:setLayoutComponentEnabled(true)
Panel_Button:setName("Panel_Button")
Panel_Button:setTag(460)
Panel_Button:setCascadeColorEnabled(true)
Panel_Button:setCascadeOpacityEnabled(true)
Panel_Button:setAnchorPoint(0.5000, 0.5000)
Panel_Button:setPosition(539.1542, 2050.3910)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Button)
layout:setPositionPercentX(0.4992)
layout:setPositionPercentY(1.0679)
layout:setPercentWidth(0.8824)
layout:setPercentHeight(0.0862)
layout:setSize({width = 953.0000, height = 165.4500})
layout:setLeftMargin(62.6542)
layout:setRightMargin(64.3458)
layout:setTopMargin(-213.1162)
layout:setBottomMargin(1967.6660)
Layer:addChild(Panel_Button)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Image/UI/MapUI/quananniu.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 95, y = 16, width = 757, height = 114})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(35)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(476.5000, 82.7250)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9937)
layout:setPercentHeight(0.8824)
layout:setSize({width = 947.0000, height = 146.0000})
layout:setLeftMargin(3.0000)
layout:setRightMargin(3.0000)
layout:setTopMargin(9.7250)
layout:setBottomMargin(9.7250)
Panel_Button:addChild(Image_1)

--Create Image_37
local Image_37 = ccui.ImageView:create()
Image_37:ignoreContentAdaptWithSize(false)
Image_37:loadTexture("Image/UI/MapUI/maobi.png",0)
Image_37:setLayoutComponentEnabled(true)
Image_37:setName("Image_37")
Image_37:setTag(247)
Image_37:setCascadeColorEnabled(true)
Image_37:setCascadeOpacityEnabled(true)
Image_37:setPosition(476.5000, 82.7250)
Image_37:setColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Image_37)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3977)
layout:setPercentHeight(0.4835)
layout:setSize({width = 379.0000, height = 80.0000})
layout:setLeftMargin(287.0000)
layout:setRightMargin(287.0000)
layout:setTopMargin(42.7250)
layout:setBottomMargin(42.7250)
Panel_Button:addChild(Image_37)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/HYCFS.ttf")
Text_name:setFontSize(79)
Text_name:setString([[鹊起无名卷]])
Text_name:setTextHorizontalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(34)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(476.5000, 82.7250)
Text_name:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4281)
layout:setPercentHeight(0.6830)
layout:setSize({width = 408.0000, height = 113.0000})
layout:setLeftMargin(272.5000)
layout:setRightMargin(272.5000)
layout:setTopMargin(26.2250)
layout:setBottomMargin(26.2250)
Panel_Button:addChild(Text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000000