--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create ScrollView_map
local ScrollView_map = ccui.ScrollView:create()
ScrollView_map:setBounceEnabled(true)
ScrollView_map:setDirection(3)
ScrollView_map:setInnerContainerSize({width = 1080, height = 1080})
ScrollView_map:ignoreContentAdaptWithSize(false)
ScrollView_map:setClippingEnabled(true)
ScrollView_map:setBackGroundColorOpacity(102)
ScrollView_map:setLayoutComponentEnabled(true)
ScrollView_map:setName("ScrollView_map")
ScrollView_map:setTag(53)
ScrollView_map:setCascadeColorEnabled(true)
ScrollView_map:setCascadeOpacityEnabled(true)
ScrollView_map:setAnchorPoint(0.0000, 0.5000)
ScrollView_map:setPosition(28.0000, 1250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_map)
layout:setPositionPercentX(0.0259)
layout:setPositionPercentY(0.6510)
layout:setPercentWidth(0.9481)
layout:setPercentHeight(0.4167)
layout:setSize({width = 1024.0000, height = 800.0000})
layout:setLeftMargin(28.0000)
layout:setRightMargin(28.0000)
layout:setTopMargin(270.0000)
layout:setBottomMargin(850.0000)
Layer:addChild(ScrollView_map)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000000000000