--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(233)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Sprite_background
local Sprite_background = cc.Sprite:create("Image/UI/MainUI/backgurand.jpg")
Sprite_background:setName("Sprite_background")
Sprite_background:setTag(232)
Sprite_background:setCascadeColorEnabled(true)
Sprite_background:setCascadeOpacityEnabled(true)
Sprite_background:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_background)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Sprite_background:setBlendFunc({src = 770, dst = 771})
Layer:addChild(Sprite_background)

--Create Sprite_background2
local Sprite_background2 = cc.Sprite:create("Image/UI/MainUI/back/xiaoyaopai.png")
Sprite_background2:setName("Sprite_background2")
Sprite_background2:setTag(231)
Sprite_background2:setCascadeColorEnabled(true)
Sprite_background2:setCascadeOpacityEnabled(true)
Sprite_background2:setPosition(540.0000, 350.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_background2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1823)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3646)
layout:setSize({width = 1080.0000, height = 700.0000})
layout:setTopMargin(1220.0000)
Sprite_background2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Sprite_background2)

--Create Panel_di
local Panel_di = ccui.Layout:create()
Panel_di:ignoreContentAdaptWithSize(false)
Panel_di:setClippingEnabled(false)
Panel_di:setBackGroundColorType(1)
Panel_di:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_di:setBackGroundColorOpacity(162)
Panel_di:setLayoutComponentEnabled(true)
Panel_di:setName("Panel_di")
Panel_di:setTag(230)
Panel_di:setCascadeColorEnabled(true)
Panel_di:setCascadeOpacityEnabled(true)
Panel_di:setAnchorPoint(0.5000, 0.5000)
Panel_di:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_di)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_di)

--Create Text_Title1
local Text_Title1 = ccui.Text:create()
Text_Title1:ignoreContentAdaptWithSize(false)
Text_Title1:setFontName("Font/default.ttf")
Text_Title1:setFontSize(60)
Text_Title1:setString([[当前拥有]])
Text_Title1:setLayoutComponentEnabled(true)
Text_Title1:setName("Text_Title1")
Text_Title1:setTag(229)
Text_Title1:setCascadeColorEnabled(true)
Text_Title1:setCascadeOpacityEnabled(true)
Text_Title1:setPosition(540.0000, 1495.2930)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Title1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7788)
layout:setPercentWidth(0.8500)
layout:setPercentHeight(0.1073)
layout:setSize({width = 918.0000, height = 206.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(81.0000)
layout:setTopMargin(321.7065)
layout:setBottomMargin(1392.2930)
Layer:addChild(Text_Title1)

--Create Text_desc_1
local Text_desc_1 = ccui.Text:create()
Text_desc_1:ignoreContentAdaptWithSize(false)
Text_desc_1:setFontName("Font/default.ttf")
Text_desc_1:setFontSize(50)
Text_desc_1:setString([[条件1
条件2
条件3
条件4
条件5]])
Text_desc_1:setLayoutComponentEnabled(true)
Text_desc_1:setName("Text_desc_1")
Text_desc_1:setTag(144)
Text_desc_1:setCascadeColorEnabled(true)
Text_desc_1:setCascadeOpacityEnabled(true)
Text_desc_1:setAnchorPoint(0.0000, 1.0000)
Text_desc_1:setPosition(82.0883, 1258.1730)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc_1)
layout:setPositionPercentX(0.0760)
layout:setPositionPercentY(0.6553)
layout:setPercentWidth(0.8500)
layout:setPercentHeight(0.1530)
layout:setSize({width = 918.0000, height = 293.7374})
layout:setLeftMargin(82.0883)
layout:setRightMargin(79.9117)
layout:setTopMargin(661.8274)
layout:setBottomMargin(964.4352)
Layer:addChild(Text_desc_1)

--Create Panel_Text1
local Panel_Text1 = ccui.Layout:create()
Panel_Text1:ignoreContentAdaptWithSize(false)
Panel_Text1:setClippingEnabled(false)
Panel_Text1:setBackGroundColorOpacity(102)
Panel_Text1:setTouchEnabled(true);
Panel_Text1:setLayoutComponentEnabled(true)
Panel_Text1:setName("Panel_Text1")
Panel_Text1:setTag(147)
Panel_Text1:setCascadeColorEnabled(true)
Panel_Text1:setCascadeOpacityEnabled(true)
Panel_Text1:setPosition(82.0768, 848.2751)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Text1)
layout:setPositionPercentX(0.0760)
layout:setPositionPercentY(0.4418)
layout:setPercentWidth(0.8500)
layout:setPercentHeight(0.0389)
layout:setSize({width = 918.0000, height = 74.6600})
layout:setLeftMargin(82.0768)
layout:setRightMargin(79.9232)
layout:setTopMargin(997.0648)
layout:setBottomMargin(848.2751)
Layer:addChild(Panel_Text1)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(50)
Text_title:setString([[XXX：]])
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(236)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setAnchorPoint(0.0000, 0.5000)
Text_title:setPosition(0.0000, 37.3300)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1253)
layout:setPercentHeight(0.7501)
layout:setSize({width = 115.0000, height = 56.0000})
layout:setRightMargin(803.0000)
layout:setTopMargin(9.3300)
layout:setBottomMargin(9.3300)
Panel_Text1:addChild(Text_title)

--Create Text_point
local Text_point = ccui.Text:create()
Text_point:ignoreContentAdaptWithSize(true)
Text_point:setTextAreaSize({width = 0, height = 0})
Text_point:setFontName("Font/default.ttf")
Text_point:setFontSize(50)
Text_point:setString([[000000]])
Text_point:setTextHorizontalAlignment(2)
Text_point:setLayoutComponentEnabled(true)
Text_point:setName("Text_point")
Text_point:setTag(118)
Text_point:setCascadeColorEnabled(true)
Text_point:setCascadeOpacityEnabled(true)
Text_point:setAnchorPoint(1.0000, 0.5000)
Text_point:setPosition(918.0000, 37.3300)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_point)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1972)
layout:setPercentHeight(0.7501)
layout:setSize({width = 181.0000, height = 56.0000})
layout:setLeftMargin(737.0000)
layout:setTopMargin(9.3300)
layout:setBottomMargin(9.3300)
Panel_Text1:addChild(Text_point)

--Create Text_Title2
local Text_Title2 = ccui.Text:create()
Text_Title2:ignoreContentAdaptWithSize(true)
Text_Title2:setTextAreaSize({width = 0, height = 0})
Text_Title2:setFontName("Font/default.ttf")
Text_Title2:setFontSize(50)
Text_Title2:setString([[XXXX：]])
Text_Title2:setLayoutComponentEnabled(true)
Text_Title2:setName("Text_Title2")
Text_Title2:setTag(228)
Text_Title2:setCascadeColorEnabled(true)
Text_Title2:setCascadeOpacityEnabled(true)
Text_Title2:setAnchorPoint(0.0000, 0.5000)
Text_Title2:setPosition(82.6010, 1291.1100)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Title2)
layout:setPositionPercentX(0.0765)
layout:setPositionPercentY(0.6725)
layout:setPercentWidth(0.1361)
layout:setPercentHeight(0.0292)
layout:setSize({width = 147.0000, height = 56.0000})
layout:setLeftMargin(82.6010)
layout:setRightMargin(850.3990)
layout:setTopMargin(600.8898)
layout:setBottomMargin(1263.1100)
Layer:addChild(Text_Title2)

--Create Button_cancel
local Button_cancel = ccui.Button:create()
Button_cancel:ignoreContentAdaptWithSize(false)
Button_cancel:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_cancel:setTitleFontSize(14)
Button_cancel:setTitleColor({r = 65, g = 65, b = 70})
Button_cancel:setScale9Enabled(true)
Button_cancel:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_cancel:setLayoutComponentEnabled(true)
Button_cancel:setName("Button_cancel")
Button_cancel:setTag(209)
Button_cancel:setCascadeColorEnabled(true)
Button_cancel:setCascadeOpacityEnabled(true)
Button_cancel:setPosition(540.0000, 551.0039)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_cancel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2870)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(408.0000)
layout:setRightMargin(408.0000)
layout:setTopMargin(1319.9960)
layout:setBottomMargin(502.0039)
Layer:addChild(Button_cancel)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/default.ttf")
Text_ButtonName:setFontSize(48)
Text_ButtonName:setString([[取消]])
Text_ButtonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 4)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(210)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(132.0000, 50.0000)
Text_ButtonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5102)
layout:setPercentWidth(0.3826)
layout:setPercentHeight(0.6327)
layout:setSize({width = 101.0000, height = 62.0000})
layout:setLeftMargin(81.5000)
layout:setRightMargin(81.5000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(19.0000)
Button_cancel:addChild(Text_ButtonName)

--Create Button_confirm
local Button_confirm = ccui.Button:create()
Button_confirm:ignoreContentAdaptWithSize(false)
Button_confirm:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_confirm:setTitleFontSize(14)
Button_confirm:setTitleColor({r = 65, g = 65, b = 70})
Button_confirm:setScale9Enabled(true)
Button_confirm:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_confirm:setLayoutComponentEnabled(true)
Button_confirm:setName("Button_confirm")
Button_confirm:setTag(211)
Button_confirm:setCascadeColorEnabled(true)
Button_confirm:setCascadeOpacityEnabled(true)
Button_confirm:setPosition(540.0000, 693.5653)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_confirm)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3612)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(408.0000)
layout:setRightMargin(408.0000)
layout:setTopMargin(1177.4350)
layout:setBottomMargin(644.5653)
Layer:addChild(Button_confirm)

--Create Text_ButtonName
local Text_ButtonName = ccui.Text:create()
Text_ButtonName:ignoreContentAdaptWithSize(true)
Text_ButtonName:setTextAreaSize({width = 0, height = 0})
Text_ButtonName:setFontName("Font/default.ttf")
Text_ButtonName:setFontSize(48)
Text_ButtonName:setString([[确定]])
Text_ButtonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 4)
Text_ButtonName:setLayoutComponentEnabled(true)
Text_ButtonName:setName("Text_ButtonName")
Text_ButtonName:setTag(212)
Text_ButtonName:setCascadeColorEnabled(true)
Text_ButtonName:setCascadeOpacityEnabled(true)
Text_ButtonName:setPosition(132.0000, 50.0000)
Text_ButtonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_ButtonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5102)
layout:setPercentWidth(0.3864)
layout:setPercentHeight(0.6327)
layout:setSize({width = 102.0000, height = 62.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(81.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(19.0000)
Button_confirm:addChild(Text_ButtonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000