--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Sprite_background
local Sprite_background = cc.Sprite:create("Image/UI/MainUI/backgurand.jpg")
Sprite_background:setName("Sprite_background")
Sprite_background:setTag(214)
Sprite_background:setCascadeColorEnabled(true)
Sprite_background:setCascadeOpacityEnabled(true)
Sprite_background:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_background)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Sprite_background:setBlendFunc({src = 770, dst = 771})
Layer:addChild(Sprite_background)

--Create Sprite_bottom
local Sprite_bottom = cc.Sprite:create("Image/UI/MainUI/changjing01.png")
Sprite_bottom:setName("Sprite_bottom")
Sprite_bottom:setTag(215)
Sprite_bottom:setCascadeColorEnabled(true)
Sprite_bottom:setCascadeOpacityEnabled(true)
Sprite_bottom:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_bottom)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3224)
layout:setSize({width = 1080.0000, height = 619.0000})
layout:setTopMargin(1301.0000)
Sprite_bottom:setBlendFunc({src = 770, dst = 771})
Layer:addChild(Sprite_bottom)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000