--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorOpacity(0)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(94)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setTouchEnabled(true);
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(93)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1173.4800)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6112)
layout:setPercentWidth(0.9741)
layout:setPercentHeight(0.6573)
layout:setSize({width = 1052.0000, height = 1262.0000})
layout:setLeftMargin(14.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(115.5198)
layout:setBottomMargin(542.4802)
Layer:addChild(Image_back)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(true)
Text_desc:setTextAreaSize({width = 0, height = 0})
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(60)
Text_desc:setString([[绑定邮箱]])
Text_desc:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(92)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(540.0000, 1600.0000)
Text_desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8333)
layout:setPercentWidth(0.2269)
layout:setPercentHeight(0.0401)
layout:setSize({width = 245.0000, height = 77.0000})
layout:setLeftMargin(417.5000)
layout:setRightMargin(417.5000)
layout:setTopMargin(281.5000)
layout:setBottomMargin(1561.5000)
Layer:addChild(Text_desc)

--Create Text_desc2
local Text_desc2 = ccui.Text:create()
Text_desc2:ignoreContentAdaptWithSize(true)
Text_desc2:setTextAreaSize({width = 0, height = 0})
Text_desc2:setFontName("Font/default.ttf")
Text_desc2:setFontSize(50)
Text_desc2:setString([[输入需要绑定账号的邮箱地址]])
Text_desc2:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_desc2:setLayoutComponentEnabled(true)
Text_desc2:setName("Text_desc2")
Text_desc2:setTag(91)
Text_desc2:setCascadeColorEnabled(true)
Text_desc2:setCascadeOpacityEnabled(true)
Text_desc2:setAnchorPoint(0.5000, 0.0000)
Text_desc2:setPosition(540.0012, 1371.5580)
Text_desc2:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7144)
layout:setPercentWidth(0.6074)
layout:setPercentHeight(0.0344)
layout:setSize({width = 656.0000, height = 66.0000})
layout:setLeftMargin(212.0012)
layout:setRightMargin(211.9988)
layout:setTopMargin(482.4421)
layout:setBottomMargin(1371.5580)
Layer:addChild(Text_desc2)

--Create EditBoxMail
local EditBoxMail = ccui.ImageView:create()
EditBoxMail:ignoreContentAdaptWithSize(false)
EditBoxMail:loadTexture("Image/UI/PopUI/kuang.png",0)
EditBoxMail:setLayoutComponentEnabled(true)
EditBoxMail:setName("EditBoxMail")
EditBoxMail:setTag(82)
EditBoxMail:setCascadeColorEnabled(true)
EditBoxMail:setCascadeOpacityEnabled(true)
EditBoxMail:setPosition(540.0000, 1251.3200)
layout = ccui.LayoutComponent:bindLayoutComponent(EditBoxMail)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6517)
layout:setPercentWidth(0.6667)
layout:setPercentHeight(0.0625)
layout:setSize({width = 720.0000, height = 120.0000})
layout:setLeftMargin(180.0000)
layout:setRightMargin(180.0000)
layout:setTopMargin(608.6796)
layout:setBottomMargin(1191.3200)
Layer:addChild(EditBoxMail)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(88)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(540.0000, 934.0234)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4865)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(926.9766)
layout:setBottomMargin(875.0234)
Layer:addChild(Button_1)

--Create Text_btn1Name
local Text_btn1Name = ccui.Text:create()
Text_btn1Name:ignoreContentAdaptWithSize(true)
Text_btn1Name:setTextAreaSize({width = 0, height = 0})
Text_btn1Name:setFontName("Font/default.ttf")
Text_btn1Name:setFontSize(48)
Text_btn1Name:setString([[确认]])
Text_btn1Name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_btn1Name:setLayoutComponentEnabled(true)
Text_btn1Name:setName("Text_btn1Name")
Text_btn1Name:setTag(89)
Text_btn1Name:setCascadeColorEnabled(true)
Text_btn1Name:setCascadeOpacityEnabled(true)
Text_btn1Name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_btn1Name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3179)
layout:setPercentHeight(0.5424)
layout:setSize({width = 103.0000, height = 64.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_btn1Name)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_2:setTitleFontSize(14)
Button_2:setTitleColor({r = 65, g = 65, b = 70})
Button_2:setScale9Enabled(true)
Button_2:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setTag(86)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setPosition(540.0000, 742.6851)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3868)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1118.3150)
layout:setBottomMargin(683.6851)
Layer:addChild(Button_2)

--Create Text_btn2Name
local Text_btn2Name = ccui.Text:create()
Text_btn2Name:ignoreContentAdaptWithSize(true)
Text_btn2Name:setTextAreaSize({width = 0, height = 0})
Text_btn2Name:setFontName("Font/default.ttf")
Text_btn2Name:setFontSize(48)
Text_btn2Name:setString([[取消]])
Text_btn2Name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_btn2Name:setLayoutComponentEnabled(true)
Text_btn2Name:setName("Text_btn2Name")
Text_btn2Name:setTag(87)
Text_btn2Name:setCascadeColorEnabled(true)
Text_btn2Name:setCascadeOpacityEnabled(true)
Text_btn2Name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_btn2Name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_2:addChild(Text_btn2Name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0