--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Image_print
local Image_print = ccui.ImageView:create()
Image_print:ignoreContentAdaptWithSize(false)
Image_print:loadTexture("Image/UI/MainUI/kuangdown.png",0)
Image_print:setLayoutComponentEnabled(true)
Image_print:setName("Image_print")
Image_print:setTag(227)
Image_print:setCascadeColorEnabled(true)
Image_print:setCascadeOpacityEnabled(true)
Image_print:setPosition(540.0000, 270.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_print)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1406)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2813)
layout:setSize({width = 1080.0000, height = 540.0000})
layout:setTopMargin(1380.0000)
Layer:addChild(Image_print)

--Create Panel_print
local Panel_print = ccui.Layout:create()
Panel_print:ignoreContentAdaptWithSize(false)
Panel_print:setClippingEnabled(false)
Panel_print:setBackGroundColorOpacity(102)
Panel_print:setTouchEnabled(true);
Panel_print:setLayoutComponentEnabled(true)
Panel_print:setName("Panel_print")
Panel_print:setTag(131)
Panel_print:setCascadeColorEnabled(true)
Panel_print:setCascadeOpacityEnabled(true)
Panel_print:setPosition(20.0000, 10.0000)
Panel_print:setOpacity(0)
Panel_print:setColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_print)
layout:setPositionPercentX(0.0185)
layout:setPositionPercentY(0.0185)
layout:setPercentWidth(0.9630)
layout:setPercentHeight(0.9630)
layout:setSize({width = 1040.0000, height = 520.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(10.0000)
layout:setBottomMargin(10.0000)
Image_print:addChild(Panel_print)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(697)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setVisible(false)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(540.0000, 270.0000)
Panel_1:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1406)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2813)
layout:setSize({width = 1080.0000, height = 540.0000})
layout:setTopMargin(1380.0000)
Layer:addChild(Panel_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000000