--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create LoadingBar
local LoadingBar = ccui.LoadingBar:create()
LoadingBar:loadTexture("Default/LoadingBarFile.png",0)
LoadingBar:ignoreContentAdaptWithSize(false)
LoadingBar:setLayoutComponentEnabled(true)
LoadingBar:setName("LoadingBar")
LoadingBar:setTag(2)
LoadingBar:setCascadeColorEnabled(true)
LoadingBar:setCascadeOpacityEnabled(true)
LoadingBar:setPosition(539.9998, 760.0000)
LoadingBar:setColor({r = 205, g = 203, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(LoadingBar)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3958)
layout:setPercentWidth(0.6481)
layout:setPercentHeight(0.0104)
layout:setSize({width = 700.0000, height = 20.0000})
layout:setLeftMargin(189.9998)
layout:setRightMargin(190.0002)
layout:setTopMargin(1150.0000)
layout:setBottomMargin(750.0000)
Layer:addChild(LoadingBar)

--Create Text
local Text = ccui.Text:create()
Text:ignoreContentAdaptWithSize(true)
Text:setTextAreaSize({width = 0, height = 0})
Text:setFontName("Font/default.ttf")
Text:setFontSize(64)
Text:setString([[正在更新资源(100%)]])
Text:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text:setLayoutComponentEnabled(true)
Text:setName("Text")
Text:setTag(3)
Text:setCascadeColorEnabled(true)
Text:setCascadeOpacityEnabled(true)
Text:setPosition(540.0000, 890.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4635)
layout:setPercentWidth(0.5630)
layout:setPercentHeight(0.0427)
layout:setSize({width = 608.0000, height = 82.0000})
layout:setLeftMargin(236.0000)
layout:setRightMargin(236.0000)
layout:setTopMargin(989.0000)
layout:setBottomMargin(849.0000)
Layer:addChild(Text)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(194)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setVisible(false)
Button_1:setPosition(540.0000, 600.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3125)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1261.0000)
layout:setBottomMargin(541.0000)
Layer:addChild(Button_1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(48)
Text_name:setString([[重新链接]])
Text_name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(195)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6142)
layout:setPercentHeight(0.5424)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(62.5000)
layout:setRightMargin(62.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000