--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(11)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(60)
Text_title:setString([[你想把黑糯米撒向谁？]])
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(12)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(539.9998, 1534.3040)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7991)
layout:setPercentWidth(0.5296)
layout:setPercentHeight(0.0349)
layout:setSize({width = 572.0000, height = 67.0000})
layout:setLeftMargin(253.9998)
layout:setRightMargin(254.0002)
layout:setTopMargin(352.1959)
layout:setBottomMargin(1500.8040)
Layer:addChild(Text_title)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setItemsMargin(35)
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(0)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(13)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(539.9998, 921.9692)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4802)
layout:setPercentWidth(0.9259)
layout:setPercentHeight(0.4688)
layout:setSize({width = 1000.0000, height = 900.0000})
layout:setLeftMargin(39.9998)
layout:setRightMargin(40.0002)
layout:setTopMargin(548.0308)
layout:setBottomMargin(471.9692)
Layer:addChild(ListView_1)

--Create Button_cancel
local Button_cancel = ccui.Button:create()
Button_cancel:ignoreContentAdaptWithSize(false)
Button_cancel:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_cancel:setTitleFontSize(14)
Button_cancel:setTitleColor({r = 65, g = 65, b = 70})
Button_cancel:setScale9Enabled(true)
Button_cancel:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_cancel:setLayoutComponentEnabled(true)
Button_cancel:setName("Button_cancel")
Button_cancel:setTag(29)
Button_cancel:setCascadeColorEnabled(true)
Button_cancel:setCascadeOpacityEnabled(true)
Button_cancel:setPosition(540.0000, 275.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_cancel)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1432)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1586.0000)
layout:setBottomMargin(216.0000)
Layer:addChild(Button_cancel)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[关闭]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(30)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(160.0000, 59.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(114.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_cancel:addChild(Text_buttonName)

--Create Button
local Button = ccui.Button:create()
Button:ignoreContentAdaptWithSize(false)
Button:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button:setTitleFontSize(14)
Button:setTitleColor({r = 65, g = 65, b = 70})
Button:setScale9Enabled(true)
Button:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button:setLayoutComponentEnabled(true)
Button:setName("Button")
Button:setTag(43)
Button:setCascadeColorEnabled(true)
Button:setCascadeOpacityEnabled(true)
Button:setPosition(2174.1330, 929.1321)
layout = ccui.LayoutComponent:bindLayoutComponent(Button)
layout:setPositionPercentX(2.0131)
layout:setPositionPercentY(0.4839)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(2012.1330)
layout:setRightMargin(-1256.1330)
layout:setTopMargin(931.8679)
layout:setBottomMargin(870.1321)
Layer:addChild(Button)

--Create Text
local Text = ccui.Text:create()
Text:ignoreContentAdaptWithSize(true)
Text:setTextAreaSize({width = 0, height = 0})
Text:setFontName("Font/default.ttf")
Text:setFontSize(48)
Text:setString([[张三]])
Text:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text:setLayoutComponentEnabled(true)
Text:setName("Text")
Text:setTag(44)
Text:setCascadeColorEnabled(true)
Text:setCascadeOpacityEnabled(true)
Text:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button:addChild(Text)

--Create Panel_role
local Panel_role = ccui.Layout:create()
Panel_role:ignoreContentAdaptWithSize(false)
Panel_role:setClippingEnabled(false)
Panel_role:setBackGroundColorType(1)
Panel_role:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_role:setBackGroundColorOpacity(0)
Panel_role:setTouchEnabled(true);
Panel_role:setLayoutComponentEnabled(true)
Panel_role:setName("Panel_role")
Panel_role:setTag(31)
Panel_role:setCascadeColorEnabled(true)
Panel_role:setCascadeOpacityEnabled(true)
Panel_role:setPosition(1621.9190, 1641.5830)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_role)
layout:setPositionPercentX(1.5018)
layout:setPositionPercentY(0.8550)
layout:setPercentWidth(0.9259)
layout:setPercentHeight(0.0615)
layout:setSize({width = 1000.0000, height = 118.0000})
layout:setLeftMargin(1621.9190)
layout:setRightMargin(-1541.9190)
layout:setTopMargin(160.4175)
layout:setBottomMargin(1641.5830)
Layer:addChild(Panel_role)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000