--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(95)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(84)
Text_title:setString([[首充大礼]])
Text_title:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(190)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(520.0000, 1835.0000)
Text_title:setTextColor({r = 255, g = 235, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.4815)
layout:setPositionPercentY(0.9557)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.0568)
layout:setSize({width = 340.0000, height = 109.0000})
layout:setLeftMargin(350.0000)
layout:setRightMargin(390.0000)
layout:setTopMargin(30.5000)
layout:setBottomMargin(1780.5000)
Layer:addChild(Text_title)

--Create Image_tiao
local Image_tiao = ccui.ImageView:create()
Image_tiao:ignoreContentAdaptWithSize(false)
Image_tiao:loadTexture("Image/UI/StoreUI/sc03.png",0)
Image_tiao:setLayoutComponentEnabled(true)
Image_tiao:setName("Image_tiao")
Image_tiao:setTag(191)
Image_tiao:setCascadeColorEnabled(true)
Image_tiao:setCascadeOpacityEnabled(true)
Image_tiao:setPosition(540.0000, 1775.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tiao)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9245)
layout:setPercentWidth(0.6630)
layout:setPercentHeight(0.0042)
layout:setSize({width = 716.0000, height = 8.0000})
layout:setLeftMargin(182.0000)
layout:setRightMargin(182.0000)
layout:setTopMargin(141.0000)
layout:setBottomMargin(1771.0000)
Layer:addChild(Image_tiao)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/StoreUI/hd02.png",0)
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(192)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(540.0000, 930.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4844)
layout:setPercentWidth(0.9759)
layout:setPercentHeight(0.6229)
layout:setSize({width = 1054.0000, height = 1196.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(392.0000)
layout:setBottomMargin(332.0000)
Layer:addChild(Image_kuang)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_close:setTitleFontSize(14)
Button_close:setTitleColor({r = 65, g = 65, b = 70})
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(195)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setAnchorPoint(0.0000, 0.0000)
Button_close:setPosition(378.0000, 121.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentX(0.3500)
layout:setPositionPercentY(0.0630)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1681.0000)
layout:setBottomMargin(121.0000)
Layer:addChild(Button_close)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[关闭]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(196)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setAnchorPoint(0.0000, 0.0000)
Text_buttonName:setPosition(110.0000, 20.5000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.3395)
layout:setPositionPercentY(0.1737)
layout:setPercentWidth(0.2901)
layout:setPercentHeight(0.5254)
layout:setSize({width = 94.0000, height = 62.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(120.0000)
layout:setTopMargin(35.5000)
layout:setBottomMargin(20.5000)
Button_close:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000