--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(207)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_tiao
local Image_tiao = ccui.ImageView:create()
Image_tiao:ignoreContentAdaptWithSize(false)
Image_tiao:loadTexture("Image/UI/StoreUI/sc03.png",0)
Image_tiao:setLayoutComponentEnabled(true)
Image_tiao:setName("Image_tiao")
Image_tiao:setTag(92)
Image_tiao:setCascadeColorEnabled(true)
Image_tiao:setCascadeOpacityEnabled(true)
Image_tiao:setPosition(540.0000, 1775.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tiao)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9245)
layout:setPercentWidth(0.6630)
layout:setPercentHeight(0.0042)
layout:setSize({width = 716.0000, height = 8.0000})
layout:setLeftMargin(182.0000)
layout:setRightMargin(182.0000)
layout:setTopMargin(141.0000)
layout:setBottomMargin(1771.0000)
Layer:addChild(Image_tiao)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(84)
Text_title:setString([[放风筝、答题活动]])
Text_title:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(93)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(520.0000, 1835.0000)
Text_title:setTextColor({r = 255, g = 235, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.4815)
layout:setPositionPercentY(0.9557)
layout:setPercentWidth(0.6278)
layout:setPercentHeight(0.0620)
layout:setSize({width = 678.0000, height = 119.0000})
layout:setLeftMargin(181.0000)
layout:setRightMargin(221.0000)
layout:setTopMargin(25.5000)
layout:setBottomMargin(1775.5000)
Layer:addChild(Text_title)

--Create Text_19
local Text_19 = ccui.Text:create()
Text_19:ignoreContentAdaptWithSize(true)
Text_19:setTextAreaSize({width = 0, height = 0})
Text_19:setFontName("Font/default.ttf")
Text_19:setFontSize(36)
Text_19:setString([[本活动结束时将根据积分排行榜发放奖励
奖励将于活动结束后次日12点发放，请于4月4日前领取]])
Text_19:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_19:setLayoutComponentEnabled(true)
Text_19:setName("Text_19")
Text_19:setTag(95)
Text_19:setCascadeColorEnabled(true)
Text_19:setCascadeOpacityEnabled(true)
Text_19:setPosition(501.1545, 121.2044)
Text_19:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_19)
layout:setPositionPercentX(0.4640)
layout:setPositionPercentY(0.0631)
layout:setPercentWidth(0.8222)
layout:setPercentHeight(0.0521)
layout:setSize({width = 888.0000, height = 100.0000})
layout:setLeftMargin(57.1545)
layout:setRightMargin(134.8455)
layout:setTopMargin(1748.7960)
layout:setBottomMargin(71.2044)
Layer:addChild(Text_19)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorOpacity(102)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(96)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(529.9484, 935.3375)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.4907)
layout:setPositionPercentY(0.4872)
layout:setPercentWidth(0.9991)
layout:setPercentHeight(0.4688)
layout:setSize({width = 1079.0000, height = 900.0000})
layout:setLeftMargin(-9.5516)
layout:setRightMargin(10.5515)
layout:setTopMargin(534.6625)
layout:setBottomMargin(485.3375)
Layer:addChild(ListView_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontName("Font/default.ttf")
Text_1:setFontSize(42)
Text_1:setString([[看龙舟,看龙舟,两堤未斗水悠悠。端午节将至,平安小镇内已涌起的赛龙舟热潮,诸位少侠可往平安小镇,北大街上方的码头查看一二。
赛龙舟活动时间为：活动上线后至2018年6月x日23点59秒结束。]])
Text_1:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(114)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 1.0000)
Text_1:setPosition(67.0000, 1750.0000)
Text_1:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.0620)
layout:setPositionPercentY(0.9115)
layout:setPercentWidth(0.8704)
layout:setPercentHeight(0.1563)
layout:setSize({width = 940.0000, height = 300.0000})
layout:setLeftMargin(67.0000)
layout:setRightMargin(73.0000)
layout:setTopMargin(170.0000)
layout:setBottomMargin(1450.0000)
Layer:addChild(Text_1)

--Create Button_10
local Button_10 = ccui.Button:create()
Button_10:ignoreContentAdaptWithSize(false)
Button_10:loadTextureNormal("Image/UI/MainUI/anniuchang.png",0)
Button_10:loadTexturePressed("Image/UI/MainUI/anniuchang.png",0)
Button_10:loadTextureDisabled("Default/Button_Disable.png",0)
Button_10:setTitleFontName("Font/default.ttf")
Button_10:setTitleFontSize(48)
Button_10:setScale9Enabled(true)
Button_10:setCapInsets({x = 15, y = 11, width = 373, height = 76})
Button_10:setLayoutComponentEnabled(true)
Button_10:setName("Button_10")
Button_10:setTag(123)
Button_10:setCascadeColorEnabled(true)
Button_10:setCascadeOpacityEnabled(true)
Button_10:setPosition(833.0602, 279.8127)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_10)
layout:setPositionPercentX(0.7714)
layout:setPositionPercentY(0.1457)
layout:setPercentWidth(0.3731)
layout:setPercentHeight(0.0510)
layout:setSize({width = 403.0000, height = 98.0000})
layout:setLeftMargin(631.5602)
layout:setRightMargin(45.4398)
layout:setTopMargin(1591.1870)
layout:setBottomMargin(230.8127)
Layer:addChild(Button_10)

--Create Text_TotalPrizeName
local Text_TotalPrizeName = ccui.Text:create()
Text_TotalPrizeName:ignoreContentAdaptWithSize(true)
Text_TotalPrizeName:setTextAreaSize({width = 0, height = 0})
Text_TotalPrizeName:setFontName("Font/default.ttf")
Text_TotalPrizeName:setFontSize(48)
Text_TotalPrizeName:setString([[春分积分排行榜]])
Text_TotalPrizeName:setTextHorizontalAlignment(1)
Text_TotalPrizeName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_TotalPrizeName:setLayoutComponentEnabled(true)
Text_TotalPrizeName:setName("Text_TotalPrizeName")
Text_TotalPrizeName:setTag(183)
Text_TotalPrizeName:setCascadeColorEnabled(true)
Text_TotalPrizeName:setCascadeOpacityEnabled(true)
Text_TotalPrizeName:setPosition(201.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_TotalPrizeName)
layout:setPositionPercentX(0.4988)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8462)
layout:setPercentHeight(0.6531)
layout:setSize({width = 341.0000, height = 64.0000})
layout:setLeftMargin(30.5000)
layout:setRightMargin(31.5000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
Button_10:addChild(Text_TotalPrizeName)

--Create Panel_4
local Panel_4 = ccui.Layout:create()
Panel_4:ignoreContentAdaptWithSize(false)
Panel_4:setClippingEnabled(true)
Panel_4:setBackGroundColorOpacity(102)
Panel_4:setTouchEnabled(true);
Panel_4:setLayoutComponentEnabled(true)
Panel_4:setName("Panel_4")
Panel_4:setTag(253)
Panel_4:setCascadeColorEnabled(true)
Panel_4:setCascadeOpacityEnabled(true)
Panel_4:setPosition(-1406.1380, 1890.8310)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_4)
layout:setPositionPercentX(-1.3020)
layout:setPositionPercentY(0.9848)
layout:setPercentWidth(0.9972)
layout:setPercentHeight(0.1042)
layout:setSize({width = 1077.0000, height = 200.0000})
layout:setLeftMargin(-1406.1380)
layout:setRightMargin(1409.1380)
layout:setTopMargin(-170.8306)
layout:setBottomMargin(1890.8310)
Layer:addChild(Panel_4)

--Create Image_23
local Image_23 = ccui.ImageView:create()
Image_23:ignoreContentAdaptWithSize(false)
Image_23:loadTexture("Image/UI/MainUI/kuang.png",0)
Image_23:setLayoutComponentEnabled(true)
Image_23:setName("Image_23")
Image_23:setTag(254)
Image_23:setCascadeColorEnabled(true)
Image_23:setCascadeOpacityEnabled(true)
Image_23:setPosition(538.5000, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_23)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1077.0000, height = 200.0000})
Panel_4:addChild(Image_23)

--Create Text_num
local Text_num = ccui.Text:create()
Text_num:ignoreContentAdaptWithSize(true)
Text_num:setTextAreaSize({width = 0, height = 0})
Text_num:setFontName("Font/HYCFS.ttf")
Text_num:setFontSize(48)
Text_num:setString([[Text Label]])
Text_num:setTextHorizontalAlignment(2)
Text_num:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_num:setLayoutComponentEnabled(true)
Text_num:setName("Text_num")
Text_num:setTag(122)
Text_num:setCascadeColorEnabled(true)
Text_num:setCascadeOpacityEnabled(true)
Text_num:setAnchorPoint(1.0000, 0.5000)
Text_num:setPosition(995.9728, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_num)
layout:setPositionPercentX(0.9248)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1959)
layout:setPercentHeight(0.3600)
layout:setSize({width = 211.0000, height = 72.0000})
layout:setLeftMargin(784.9728)
layout:setRightMargin(81.0272)
layout:setTopMargin(64.0000)
layout:setBottomMargin(64.0000)
Panel_4:addChild(Text_num)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/HYCFS.ttf")
Text_name:setFontSize(48)
Text_name:setString([[Text Label]])
Text_name:setTextVerticalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setTouchEnabled(true);
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(121)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.5000)
Text_name:setPosition(70.9500, 100.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.0659)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1959)
layout:setPercentHeight(0.3600)
layout:setSize({width = 211.0000, height = 72.0000})
layout:setLeftMargin(70.9500)
layout:setRightMargin(795.0500)
layout:setTopMargin(64.0000)
layout:setBottomMargin(64.0000)
Panel_4:addChild(Text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000