--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(606)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_num1
local Text_num1 = ccui.Text:create()
Text_num1:ignoreContentAdaptWithSize(true)
Text_num1:setTextAreaSize({width = 0, height = 0})
Text_num1:setFontName("Font/default.ttf")
Text_num1:setFontSize(40)
Text_num1:setString([[当前拥有0个]])
Text_num1:setLayoutComponentEnabled(true)
Text_num1:setName("Text_num1")
Text_num1:setTag(622)
Text_num1:setCascadeColorEnabled(true)
Text_num1:setCascadeOpacityEnabled(true)
Text_num1:setPosition(500.0000, 905.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_num1)
layout:setPositionPercentX(0.4630)
layout:setPositionPercentY(0.4714)
layout:setPercentWidth(0.2093)
layout:setPercentHeight(0.0234)
layout:setSize({width = 226.0000, height = 45.0000})
layout:setLeftMargin(387.0000)
layout:setRightMargin(467.0000)
layout:setTopMargin(992.5000)
layout:setBottomMargin(882.5000)
Layer:addChild(Text_num1)

--Create Text_num2
local Text_num2 = ccui.Text:create()
Text_num2:ignoreContentAdaptWithSize(true)
Text_num2:setTextAreaSize({width = 0, height = 0})
Text_num2:setFontName("Font/default.ttf")
Text_num2:setFontSize(40)
Text_num2:setString([[当前拥有1个]])
Text_num2:setLayoutComponentEnabled(true)
Text_num2:setName("Text_num2")
Text_num2:setTag(623)
Text_num2:setCascadeColorEnabled(true)
Text_num2:setCascadeOpacityEnabled(true)
Text_num2:setPosition(500.0000, 660.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_num2)
layout:setPositionPercentX(0.4630)
layout:setPositionPercentY(0.3438)
layout:setPercentWidth(0.2093)
layout:setPercentHeight(0.0234)
layout:setSize({width = 226.0000, height = 45.0000})
layout:setLeftMargin(387.0000)
layout:setRightMargin(467.0000)
layout:setTopMargin(1237.5000)
layout:setBottomMargin(637.5000)
Layer:addChild(Text_num2)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(84)
Text_title:setString([[投票]])
Text_title:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(608)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(520.0000, 1800.0000)
Text_title:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.4815)
layout:setPositionPercentY(0.9375)
layout:setPercentWidth(0.1648)
layout:setPercentHeight(0.0620)
layout:setSize({width = 178.0000, height = 119.0000})
layout:setLeftMargin(431.0000)
layout:setRightMargin(471.0000)
layout:setTopMargin(60.5000)
layout:setBottomMargin(1740.5000)
Layer:addChild(Text_title)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(false)
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(58)
Text_name:setString([[你将要投票给柳玄风。请问你打算用何种令牌投票？]])
Text_name:setTextHorizontalAlignment(1)
Text_name:setTextVerticalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(609)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.0000)
Text_name:setPosition(67.0000, 1321.1970)
Text_name:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.0620)
layout:setPositionPercentY(0.6881)
layout:setPercentWidth(0.8704)
layout:setPercentHeight(0.1713)
layout:setSize({width = 940.0000, height = 328.8027})
layout:setLeftMargin(67.0000)
layout:setRightMargin(73.0000)
layout:setTopMargin(270.0000)
layout:setBottomMargin(1321.1970)
Layer:addChild(Text_name)

--Create Button_shengzhen
local Button_shengzhen = ccui.Button:create()
Button_shengzhen:ignoreContentAdaptWithSize(false)
Button_shengzhen:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_shengzhen:setTitleFontSize(14)
Button_shengzhen:setTitleColor({r = 65, g = 65, b = 70})
Button_shengzhen:setScale9Enabled(true)
Button_shengzhen:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_shengzhen:setLayoutComponentEnabled(true)
Button_shengzhen:setName("Button_shengzhen")
Button_shengzhen:setTag(68)
Button_shengzhen:setCascadeColorEnabled(true)
Button_shengzhen:setCascadeOpacityEnabled(true)
Button_shengzhen:setAnchorPoint(0.0000, 0.0000)
Button_shengzhen:setPosition(380.0000, 950.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_shengzhen)
layout:setPositionPercentX(0.3519)
layout:setPositionPercentY(0.4948)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(380.0000)
layout:setRightMargin(376.0000)
layout:setTopMargin(852.0000)
layout:setBottomMargin(950.0000)
Layer:addChild(Button_shengzhen)

--Create Text_shengzhen
local Text_shengzhen = ccui.Text:create()
Text_shengzhen:ignoreContentAdaptWithSize(true)
Text_shengzhen:setTextAreaSize({width = 0, height = 0})
Text_shengzhen:setFontName("Font/default.ttf")
Text_shengzhen:setFontSize(48)
Text_shengzhen:setString([[江湖风云令]])
Text_shengzhen:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_shengzhen:setLayoutComponentEnabled(true)
Text_shengzhen:setName("Text_shengzhen")
Text_shengzhen:setTag(69)
Text_shengzhen:setCascadeColorEnabled(true)
Text_shengzhen:setCascadeOpacityEnabled(true)
Text_shengzhen:setAnchorPoint(0.0000, 0.0000)
Text_shengzhen:setPosition(40.0000, 30.0000)
Text_shengzhen:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_shengzhen)
layout:setPositionPercentX(0.1235)
layout:setPositionPercentY(0.2542)
layout:setPercentWidth(0.7623)
layout:setPercentHeight(0.5424)
layout:setSize({width = 247.0000, height = 64.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(30.0000)
Button_shengzhen:addChild(Text_shengzhen)

--Create Button_yangming
local Button_yangming = ccui.Button:create()
Button_yangming:ignoreContentAdaptWithSize(false)
Button_yangming:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_yangming:setTitleFontSize(14)
Button_yangming:setTitleColor({r = 65, g = 65, b = 70})
Button_yangming:setScale9Enabled(true)
Button_yangming:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_yangming:setLayoutComponentEnabled(true)
Button_yangming:setName("Button_yangming")
Button_yangming:setTag(70)
Button_yangming:setCascadeColorEnabled(true)
Button_yangming:setCascadeOpacityEnabled(true)
Button_yangming:setAnchorPoint(0.0000, 0.0000)
Button_yangming:setPosition(380.0000, 700.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_yangming)
layout:setPositionPercentX(0.3519)
layout:setPositionPercentY(0.3646)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(380.0000)
layout:setRightMargin(376.0000)
layout:setTopMargin(1102.0000)
layout:setBottomMargin(700.0000)
Layer:addChild(Button_yangming)

--Create Text_yangming
local Text_yangming = ccui.Text:create()
Text_yangming:ignoreContentAdaptWithSize(true)
Text_yangming:setTextAreaSize({width = 0, height = 0})
Text_yangming:setFontName("Font/default.ttf")
Text_yangming:setFontSize(48)
Text_yangming:setString([[江湖扬名令]])
Text_yangming:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_yangming:setLayoutComponentEnabled(true)
Text_yangming:setName("Text_yangming")
Text_yangming:setTag(71)
Text_yangming:setCascadeColorEnabled(true)
Text_yangming:setCascadeOpacityEnabled(true)
Text_yangming:setAnchorPoint(0.0000, 0.0000)
Text_yangming:setPosition(40.0000, 30.0000)
Text_yangming:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_yangming)
layout:setPositionPercentX(0.1235)
layout:setPositionPercentY(0.2542)
layout:setPercentWidth(0.7623)
layout:setPercentHeight(0.5424)
layout:setSize({width = 247.0000, height = 64.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(30.0000)
Button_yangming:addChild(Text_yangming)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_back:setTitleFontSize(14)
Button_back:setTitleColor({r = 65, g = 65, b = 70})
Button_back:setScale9Enabled(true)
Button_back:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(72)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setAnchorPoint(0.0000, 0.0000)
Button_back:setPosition(380.0000, 450.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.3519)
layout:setPositionPercentY(0.2344)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(380.0000)
layout:setRightMargin(376.0000)
layout:setTopMargin(1352.0000)
layout:setBottomMargin(450.0000)
Layer:addChild(Button_back)

--Create Text_quit
local Text_quit = ccui.Text:create()
Text_quit:ignoreContentAdaptWithSize(true)
Text_quit:setTextAreaSize({width = 0, height = 0})
Text_quit:setFontName("Font/default.ttf")
Text_quit:setFontSize(48)
Text_quit:setString([[容我再考虑]])
Text_quit:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_quit:setLayoutComponentEnabled(true)
Text_quit:setName("Text_quit")
Text_quit:setTag(73)
Text_quit:setCascadeColorEnabled(true)
Text_quit:setCascadeOpacityEnabled(true)
Text_quit:setAnchorPoint(0.0000, 0.0000)
Text_quit:setPosition(40.0000, 30.0000)
Text_quit:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_quit)
layout:setPositionPercentX(0.1235)
layout:setPositionPercentY(0.2542)
layout:setPercentWidth(0.7623)
layout:setPercentHeight(0.5424)
layout:setSize({width = 247.0000, height = 64.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(37.0000)
layout:setTopMargin(24.0000)
layout:setBottomMargin(30.0000)
Button_back:addChild(Text_quit)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000