--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorOpacity(102)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(73)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(72)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1175.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(115.9900)
layout:setBottomMargin(546.0100)
Layer:addChild(Image_back)

--Create Image_inherit
local Image_inherit = ccui.ImageView:create()
Image_inherit:ignoreContentAdaptWithSize(false)
Image_inherit:loadTexture("Image/UI/RankingUI/chuanshimingmen.png",0)
Image_inherit:setLayoutComponentEnabled(true)
Image_inherit:setName("Image_inherit")
Image_inherit:setTag(61)
Image_inherit:setCascadeColorEnabled(true)
Image_inherit:setCascadeOpacityEnabled(true)
Image_inherit:setPosition(895.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_inherit)
layout:setPositionPercentX(0.8287)
layout:setPositionPercentY(0.3333)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0885)
layout:setSize({width = 324.0000, height = 170.0000})
layout:setLeftMargin(733.0000)
layout:setRightMargin(23.0000)
layout:setTopMargin(1195.0000)
layout:setBottomMargin(555.0000)
Layer:addChild(Image_inherit)

--Create ScrollView_view
local ScrollView_view = ccui.ScrollView:create()
ScrollView_view:setInnerContainerSize({width = 1052, height = 1262})
ScrollView_view:ignoreContentAdaptWithSize(false)
ScrollView_view:setClippingEnabled(false)
ScrollView_view:setBackGroundColorType(1)
ScrollView_view:setBackGroundColor({r = 255, g = 150, b = 100})
ScrollView_view:setBackGroundColorOpacity(0)
ScrollView_view:setLayoutComponentEnabled(true)
ScrollView_view:setName("ScrollView_view")
ScrollView_view:setTag(71)
ScrollView_view:setCascadeColorEnabled(true)
ScrollView_view:setCascadeOpacityEnabled(true)
ScrollView_view:setAnchorPoint(0.5000, 0.5000)
ScrollView_view:setPosition(540.0000, 1175.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_view)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9741)
layout:setPercentHeight(0.6573)
layout:setSize({width = 1052.0000, height = 1262.0000})
layout:setLeftMargin(14.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(114.0000)
layout:setBottomMargin(544.0000)
Layer:addChild(ScrollView_view)

--Create ListView_list
local ListView_list = ccui.ListView:create()
ListView_list:setDirection(1)
ListView_list:setGravity(2)
ListView_list:ignoreContentAdaptWithSize(false)
ListView_list:setClippingEnabled(false)
ListView_list:setBackGroundColorType(1)
ListView_list:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_list:setBackGroundColorOpacity(0)
ListView_list:setLayoutComponentEnabled(true)
ListView_list:setName("ListView_list")
ListView_list:setTag(70)
ListView_list:setCascadeColorEnabled(true)
ListView_list:setCascadeOpacityEnabled(true)
ListView_list:setAnchorPoint(0.5000, 0.5000)
ListView_list:setPosition(540.0000, 1175.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_list)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9741)
layout:setPercentHeight(0.6573)
layout:setSize({width = 1052.0000, height = 1262.0000})
layout:setLeftMargin(14.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(114.0000)
layout:setBottomMargin(544.0000)
Layer:addChild(ListView_list)

--Create Panel_attr
local Panel_attr = ccui.Layout:create()
Panel_attr:ignoreContentAdaptWithSize(false)
Panel_attr:setClippingEnabled(false)
Panel_attr:setBackGroundColorType(1)
Panel_attr:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_attr:setBackGroundColorOpacity(0)
Panel_attr:setTouchEnabled(true);
Panel_attr:setLayoutComponentEnabled(true)
Panel_attr:setName("Panel_attr")
Panel_attr:setTag(63)
Panel_attr:setCascadeColorEnabled(true)
Panel_attr:setCascadeOpacityEnabled(true)
Panel_attr:setAnchorPoint(0.5000, 0.5000)
Panel_attr:setPosition(540.0000, 1175.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_attr)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9741)
layout:setPercentHeight(0.6573)
layout:setSize({width = 1052.0000, height = 1262.0000})
layout:setLeftMargin(14.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(114.0000)
layout:setBottomMargin(544.0000)
Layer:addChild(Panel_attr)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(false)
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(48)
Text_title:setString([[谷虚道长]])
Text_title:setTextHorizontalAlignment(1)
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(64)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(526.0000, 1125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8914)
layout:setPercentWidth(0.8080)
layout:setPercentHeight(0.0507)
layout:setSize({width = 850.0000, height = 64.0000})
layout:setLeftMargin(101.0000)
layout:setRightMargin(101.0000)
layout:setTopMargin(105.0000)
layout:setBottomMargin(1093.0000)
Panel_attr:addChild(Text_title)

--Create Panel_dscArea
local Panel_dscArea = ccui.Layout:create()
Panel_dscArea:ignoreContentAdaptWithSize(false)
Panel_dscArea:setClippingEnabled(false)
Panel_dscArea:setBackGroundColorOpacity(102)
Panel_dscArea:setTouchEnabled(true);
Panel_dscArea:setLayoutComponentEnabled(true)
Panel_dscArea:setName("Panel_dscArea")
Panel_dscArea:setTag(65)
Panel_dscArea:setCascadeColorEnabled(true)
Panel_dscArea:setCascadeOpacityEnabled(true)
Panel_dscArea:setAnchorPoint(0.5000, 1.0000)
Panel_dscArea:setPosition(526.0000, 1045.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_dscArea)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8281)
layout:setPercentWidth(0.8080)
layout:setPercentHeight(0.3962)
layout:setSize({width = 850.0000, height = 500.0000})
layout:setLeftMargin(101.0000)
layout:setRightMargin(101.0000)
layout:setTopMargin(217.0000)
layout:setBottomMargin(545.0000)
Panel_attr:addChild(Panel_dscArea)

--Create ListView_bottom
local ListView_bottom = ccui.ListView:create()
ListView_bottom:setDirection(1)
ListView_bottom:setGravity(2)
ListView_bottom:ignoreContentAdaptWithSize(false)
ListView_bottom:setClippingEnabled(true)
ListView_bottom:setBackGroundColorOpacity(102)
ListView_bottom:setLayoutComponentEnabled(true)
ListView_bottom:setName("ListView_bottom")
ListView_bottom:setTag(66)
ListView_bottom:setCascadeColorEnabled(true)
ListView_bottom:setCascadeOpacityEnabled(true)
ListView_bottom:setAnchorPoint(0.5000, 1.0000)
ListView_bottom:setPosition(526.0000, 595.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_bottom)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4715)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4754)
layout:setSize({width = 1052.0000, height = 600.0000})
layout:setTopMargin(667.0000)
layout:setBottomMargin(-5.0000)
Panel_attr:addChild(ListView_bottom)

--Create Image_di
local Image_di = ccui.ImageView:create()
Image_di:ignoreContentAdaptWithSize(false)
Image_di:loadTexture("Image/UI/AttrUI/di1.png",0)
Image_di:setLayoutComponentEnabled(true)
Image_di:setName("Image_di")
Image_di:setTag(67)
Image_di:setCascadeColorEnabled(true)
Image_di:setCascadeOpacityEnabled(true)
Image_di:setVisible(false)
Image_di:setPosition(855.0000, 1103.7600)
Image_di:setScaleX(0.8000)
Image_di:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_di)
layout:setPositionPercentX(0.8127)
layout:setPositionPercentY(0.8746)
layout:setPercentWidth(0.2433)
layout:setPercentHeight(0.2029)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(727.0000)
layout:setRightMargin(69.0000)
layout:setTopMargin(30.2397)
layout:setBottomMargin(975.7603)
Panel_attr:addChild(Image_di)

--Create Image_frame
local Image_frame = ccui.ImageView:create()
Image_frame:ignoreContentAdaptWithSize(false)
Image_frame:loadTexture("Image/UI/MainUI/biankuang01.png",0)
Image_frame:setLayoutComponentEnabled(true)
Image_frame:setName("Image_frame")
Image_frame:setTag(68)
Image_frame:setCascadeColorEnabled(true)
Image_frame:setCascadeOpacityEnabled(true)
Image_frame:setVisible(false)
Image_frame:setPosition(855.0000, 1103.7600)
Image_frame:setScaleX(0.8000)
Image_frame:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_frame)
layout:setPositionPercentX(0.8127)
layout:setPositionPercentY(0.8746)
layout:setPercentWidth(0.2605)
layout:setPercentHeight(0.2171)
layout:setSize({width = 274.0000, height = 274.0000})
layout:setLeftMargin(718.0000)
layout:setRightMargin(60.0000)
layout:setTopMargin(21.2400)
layout:setBottomMargin(966.7600)
Panel_attr:addChild(Image_frame)

--Create Image_head
local Image_head = ccui.ImageView:create()
Image_head:ignoreContentAdaptWithSize(false)
Image_head:loadTexture("Image/UI/AttrUI/nv/9.png",0)
Image_head:setLayoutComponentEnabled(true)
Image_head:setName("Image_head")
Image_head:setTag(69)
Image_head:setCascadeColorEnabled(true)
Image_head:setCascadeOpacityEnabled(true)
Image_head:setVisible(false)
Image_head:setPosition(855.0000, 1103.7600)
Image_head:setScaleX(0.8000)
Image_head:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_head)
layout:setPositionPercentX(0.8127)
layout:setPositionPercentY(0.8746)
layout:setPercentWidth(0.2433)
layout:setPercentHeight(0.2029)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(727.0000)
layout:setRightMargin(69.0000)
layout:setTopMargin(30.2397)
layout:setBottomMargin(975.7603)
Panel_attr:addChild(Image_head)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000