--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_backColor
local Panel_backColor = ccui.Layout:create()
Panel_backColor:ignoreContentAdaptWithSize(false)
Panel_backColor:setBackGroundImage("Image/UI/MainUI/backgurand.jpg",0)
Panel_backColor:setClippingEnabled(false)
Panel_backColor:setBackGroundColorType(1)
Panel_backColor:setBackGroundColor({r = 127, g = 127, b = 127})
Panel_backColor:setLayoutComponentEnabled(true)
Panel_backColor:setName("Panel_backColor")
Panel_backColor:setTag(1169)
Panel_backColor:setCascadeColorEnabled(true)
Panel_backColor:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_backColor)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_backColor)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("Image/UI/MainUI/changjing01.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(1170)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(540.0000, 310.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1615)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3224)
layout:setSize({width = 1080.0000, height = 619.0000})
layout:setTopMargin(1300.5000)
layout:setBottomMargin(0.5000)
Panel_backColor:addChild(Image_3)

--Create PageView_ranking
local PageView_ranking = ccui.PageView:create()
PageView_ranking:ignoreContentAdaptWithSize(false)
PageView_ranking:setClippingEnabled(false)
PageView_ranking:setBackGroundColorOpacity(102)
PageView_ranking:setLayoutComponentEnabled(true)
PageView_ranking:setName("PageView_ranking")
PageView_ranking:setTag(1168)
PageView_ranking:setCascadeColorEnabled(true)
PageView_ranking:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(PageView_ranking)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(PageView_ranking)

--Create Panel_category
local Panel_category = ccui.Layout:create()
Panel_category:ignoreContentAdaptWithSize(false)
Panel_category:setClippingEnabled(false)
Panel_category:setBackGroundColorType(1)
Panel_category:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_category:setBackGroundColorOpacity(102)
Panel_category:setLayoutComponentEnabled(true)
Panel_category:setName("Panel_category")
Panel_category:setTag(1167)
Panel_category:setCascadeColorEnabled(true)
Panel_category:setCascadeOpacityEnabled(true)
Panel_category:setPosition(0.0000, 1820.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_category)
layout:setPositionPercentY(0.9479)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0521)
layout:setSize({width = 1080.0000, height = 100.0000})
layout:setBottomMargin(1820.0000)
Layer:addChild(Panel_category)

--Create Panel_item
local Panel_item = ccui.Layout:create()
Panel_item:ignoreContentAdaptWithSize(false)
Panel_item:setBackGroundImage("Image/UI/RankingUI/1.png",0)
Panel_item:setClippingEnabled(false)
Panel_item:setBackGroundColorOpacity(102)
Panel_item:setLayoutComponentEnabled(true)
Panel_item:setName("Panel_item")
Panel_item:setTag(1173)
Panel_item:setCascadeColorEnabled(true)
Panel_item:setCascadeOpacityEnabled(true)
Panel_item:setPosition(51.0614, 2012.9670)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_item)
layout:setPositionPercentX(0.0473)
layout:setPositionPercentY(1.0484)
layout:setPercentWidth(0.9259)
layout:setPercentHeight(0.0677)
layout:setSize({width = 1000.0000, height = 130.0000})
layout:setLeftMargin(51.0614)
layout:setRightMargin(28.9386)
layout:setTopMargin(-222.9673)
layout:setBottomMargin(2012.9670)
Layer:addChild(Panel_item)

--Create Image_beijing
local Image_beijing = ccui.ImageView:create()
Image_beijing:ignoreContentAdaptWithSize(false)
Image_beijing:loadTexture("Image/UI/RankingUI/2.png",0)
Image_beijing:setLayoutComponentEnabled(true)
Image_beijing:setName("Image_beijing")
Image_beijing:setTag(1174)
Image_beijing:setCascadeColorEnabled(true)
Image_beijing:setCascadeOpacityEnabled(true)
Image_beijing:setPosition(164.0000, 70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_beijing)
layout:setPositionPercentX(0.1640)
layout:setPositionPercentY(0.5385)
layout:setPercentWidth(0.1160)
layout:setPercentHeight(0.8923)
layout:setSize({width = 116.0000, height = 116.0000})
layout:setLeftMargin(106.0000)
layout:setRightMargin(778.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(12.0000)
Panel_item:addChild(Image_beijing)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/MainUI/biankuang03.png",0)
Image_kuang:setTouchEnabled(true);
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(1175)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(164.0000, 70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.1640)
layout:setPositionPercentY(0.5385)
layout:setPercentWidth(0.1180)
layout:setPercentHeight(0.9077)
layout:setSize({width = 118.0000, height = 118.0000})
layout:setLeftMargin(105.0000)
layout:setRightMargin(777.0000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(11.0000)
Panel_item:addChild(Image_kuang)

--Create Image_looks
local Image_looks = ccui.ImageView:create()
Image_looks:ignoreContentAdaptWithSize(false)
Image_looks:loadTexture("Image/UI/AttrUI/nan/9.png",0)
Image_looks:setLayoutComponentEnabled(true)
Image_looks:setName("Image_looks")
Image_looks:setTag(1176)
Image_looks:setCascadeColorEnabled(true)
Image_looks:setCascadeOpacityEnabled(true)
Image_looks:setPosition(164.0000, 70.0000)
Image_looks:setScaleX(0.3900)
Image_looks:setScaleY(0.3900)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_looks)
layout:setPositionPercentX(0.1640)
layout:setPositionPercentY(0.5385)
layout:setPercentWidth(0.2560)
layout:setPercentHeight(1.9692)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(36.0000)
layout:setRightMargin(708.0000)
layout:setTopMargin(-68.0000)
layout:setBottomMargin(-58.0000)
Panel_item:addChild(Image_looks)

--Create Text_mingci
local Text_mingci = ccui.Text:create()
Text_mingci:ignoreContentAdaptWithSize(true)
Text_mingci:setTextAreaSize({width = 0, height = 0})
Text_mingci:setFontName("Font/default.ttf")
Text_mingci:setFontSize(36)
Text_mingci:setString([[9999+]])
Text_mingci:enableOutline({r = 221, g = 215, b = 151, a = 255}, 5)
Text_mingci:setLayoutComponentEnabled(true)
Text_mingci:setName("Text_mingci")
Text_mingci:setTag(1177)
Text_mingci:setCascadeColorEnabled(true)
Text_mingci:setCascadeOpacityEnabled(true)
Text_mingci:setAnchorPoint(1.0000, 0.0000)
Text_mingci:setPosition(110.0001, 8.9996)
Text_mingci:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_mingci)
layout:setPositionPercentX(0.1100)
layout:setPositionPercentY(0.0692)
layout:setPercentWidth(0.1160)
layout:setPercentHeight(0.3846)
layout:setSize({width = 116.0000, height = 50.0000})
layout:setLeftMargin(-5.9999)
layout:setRightMargin(889.9999)
layout:setTopMargin(71.0004)
layout:setBottomMargin(8.9996)
Panel_item:addChild(Text_mingci)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(54)
Text_name:setString([[西门大官]])
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setTouchEnabled(true);
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(1178)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.0000)
Text_name:setPosition(241.4327, 14.9970)
Text_name:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.2414)
layout:setPositionPercentY(0.1154)
layout:setPercentWidth(0.2200)
layout:setPercentHeight(0.5385)
layout:setSize({width = 220.0000, height = 70.0000})
layout:setLeftMargin(241.4327)
layout:setRightMargin(538.5673)
layout:setTopMargin(45.0030)
layout:setBottomMargin(14.9970)
Panel_item:addChild(Text_name)

--Create Text_pingjia
local Text_pingjia = ccui.Text:create()
Text_pingjia:ignoreContentAdaptWithSize(true)
Text_pingjia:setTextAreaSize({width = 0, height = 0})
Text_pingjia:setFontName("Font/HYCFS.ttf")
Text_pingjia:setFontSize(54)
Text_pingjia:setString([[深不可测]])
Text_pingjia:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_pingjia:setTouchEnabled(true);
Text_pingjia:setLayoutComponentEnabled(true)
Text_pingjia:setName("Text_pingjia")
Text_pingjia:setTag(1179)
Text_pingjia:setCascadeColorEnabled(true)
Text_pingjia:setCascadeOpacityEnabled(true)
Text_pingjia:setAnchorPoint(1.0000, 0.0000)
Text_pingjia:setPosition(955.0001, 14.9999)
Text_pingjia:setTextColor({r = 192, g = 3, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_pingjia)
layout:setPositionPercentX(0.9550)
layout:setPositionPercentY(0.1154)
layout:setPercentWidth(0.2190)
layout:setPercentHeight(0.4923)
layout:setSize({width = 219.0000, height = 64.0000})
layout:setLeftMargin(736.0001)
layout:setRightMargin(44.9999)
layout:setTopMargin(51.0001)
layout:setBottomMargin(14.9999)
Panel_item:addChild(Text_pingjia)

--Create Text_jifen
local Text_jifen = ccui.Text:create()
Text_jifen:ignoreContentAdaptWithSize(true)
Text_jifen:setTextAreaSize({width = 0, height = 0})
Text_jifen:setFontName("Font/default.ttf")
Text_jifen:setFontSize(42)
Text_jifen:setString([[西门大官人]])
Text_jifen:setTouchEnabled(true);
Text_jifen:setLayoutComponentEnabled(true)
Text_jifen:setName("Text_jifen")
Text_jifen:setTag(1180)
Text_jifen:setCascadeColorEnabled(true)
Text_jifen:setCascadeOpacityEnabled(true)
Text_jifen:setAnchorPoint(0.0000, 0.0000)
Text_jifen:setPosition(470.0000, 14.9997)
Text_jifen:setTextColor({r = 182, g = 134, b = 27})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_jifen)
layout:setPositionPercentX(0.4700)
layout:setPositionPercentY(0.1154)
layout:setPercentWidth(0.2120)
layout:setPercentHeight(0.3615)
layout:setSize({width = 212.0000, height = 47.0000})
layout:setLeftMargin(470.0000)
layout:setRightMargin(318.0000)
layout:setTopMargin(68.0003)
layout:setBottomMargin(14.9997)
Panel_item:addChild(Text_jifen)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("Image/UI/MenuUI/back.png",0)
Button_back:loadTexturePressed("Image/UI/MenuUI/back2.png",0)
Button_back:setTitleFontSize(48)
Button_back:setTitleColor({r = 208, g = 208, b = 208})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(1160)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(100.0000, 1870.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.0926)
layout:setPositionPercentY(0.9740)
layout:setPercentWidth(0.1620)
layout:setPercentHeight(0.0406)
layout:setSize({width = 175.0000, height = 78.0000})
layout:setLeftMargin(12.5000)
layout:setRightMargin(892.5000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(1831.0000)
Layer:addChild(Button_back)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000