--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(915)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(84)
Text_title:setString([[七夕情书]])
Text_title:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(914)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(540.0009, 1835.0000)
Text_title:setTextColor({r = 255, g = 235, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9557)
layout:setPercentWidth(0.3130)
layout:setPercentHeight(0.0620)
layout:setSize({width = 338.0000, height = 119.0000})
layout:setLeftMargin(371.0009)
layout:setRightMargin(370.9991)
layout:setTopMargin(25.4999)
layout:setBottomMargin(1775.5000)
Layer:addChild(Text_title)

--Create Image_tiao
local Image_tiao = ccui.ImageView:create()
Image_tiao:ignoreContentAdaptWithSize(false)
Image_tiao:loadTexture("Image/UI/StoreUI/sc03.png",0)
Image_tiao:setLayoutComponentEnabled(true)
Image_tiao:setName("Image_tiao")
Image_tiao:setTag(913)
Image_tiao:setCascadeColorEnabled(true)
Image_tiao:setCascadeOpacityEnabled(true)
Image_tiao:setPosition(540.0000, 1775.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_tiao)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9245)
layout:setPercentWidth(0.6630)
layout:setPercentHeight(0.0042)
layout:setSize({width = 716.0000, height = 8.0000})
layout:setLeftMargin(182.0000)
layout:setRightMargin(182.0000)
layout:setTopMargin(141.0000)
layout:setBottomMargin(1771.0000)
Layer:addChild(Image_tiao)

--Create Image_kuang
local Image_kuang = ccui.ImageView:create()
Image_kuang:ignoreContentAdaptWithSize(false)
Image_kuang:loadTexture("Image/UI/StoreUI/hd02.png",0)
Image_kuang:setLayoutComponentEnabled(true)
Image_kuang:setName("Image_kuang")
Image_kuang:setTag(912)
Image_kuang:setCascadeColorEnabled(true)
Image_kuang:setCascadeOpacityEnabled(true)
Image_kuang:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_kuang)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9759)
layout:setPercentHeight(0.7292)
layout:setSize({width = 1054.0000, height = 1400.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(260.0000)
layout:setBottomMargin(260.0000)
Layer:addChild(Image_kuang)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(42)
Text_desc:setString([[]])
Text_desc:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(909)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(539.9753, 1059.0120)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5516)
layout:setPercentWidth(0.9074)
layout:setPercentHeight(0.5729)
layout:setSize({width = 980.0000, height = 1100.0000})
layout:setLeftMargin(49.9753)
layout:setRightMargin(50.0247)
layout:setTopMargin(310.9883)
layout:setBottomMargin(509.0117)
Layer:addChild(Text_desc)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(918)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(828.0000, 154.0007)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.7667)
layout:setPositionPercentY(0.0802)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setHorizontalEdge(2)
layout:setLeftMargin(666.0000)
layout:setRightMargin(90.0000)
layout:setTopMargin(1706.9990)
layout:setBottomMargin(95.0007)
Layer:addChild(Button_1)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[关闭]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(919)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(160.0000, 59.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(114.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_buttonName)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_2:setTitleFontSize(14)
Button_2:setTitleColor({r = 65, g = 65, b = 70})
Button_2:setScale9Enabled(true)
Button_2:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setTag(920)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setVisible(false)
Button_2:setPosition(540.0001, 397.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2072)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0001)
layout:setRightMargin(377.9999)
layout:setTopMargin(1463.2000)
layout:setBottomMargin(338.8000)
Layer:addChild(Button_2)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[查看榜单]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(921)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(160.0000, 59.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6111)
layout:setPercentHeight(0.5424)
layout:setSize({width = 198.0000, height = 64.0000})
layout:setLeftMargin(61.0000)
layout:setRightMargin(65.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_2:addChild(Text_buttonName)

--Create Button_3
local Button_3 = ccui.Button:create()
Button_3:ignoreContentAdaptWithSize(false)
Button_3:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_3:setTitleFontSize(14)
Button_3:setTitleColor({r = 65, g = 65, b = 70})
Button_3:setScale9Enabled(true)
Button_3:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_3:setLayoutComponentEnabled(true)
Button_3:setName("Button_3")
Button_3:setTag(922)
Button_3:setCascadeColorEnabled(true)
Button_3:setCascadeOpacityEnabled(true)
Button_3:setPosition(252.0000, 154.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_3)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.0802)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(90.0000)
layout:setRightMargin(666.0000)
layout:setTopMargin(1707.0000)
layout:setBottomMargin(95.0000)
Layer:addChild(Button_3)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[领取任务]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(923)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(160.0000, 59.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.4938)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6111)
layout:setPercentHeight(0.5424)
layout:setSize({width = 198.0000, height = 64.0000})
layout:setLeftMargin(61.0000)
layout:setRightMargin(65.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_3:addChild(Text_buttonName)

--Create Image_hongdian
local Image_hongdian = ccui.ImageView:create()
Image_hongdian:ignoreContentAdaptWithSize(false)
Image_hongdian:loadTexture("Image/UI/TeacherUI/hongdian.png",0)
Image_hongdian:setLayoutComponentEnabled(true)
Image_hongdian:setName("Image_hongdian")
Image_hongdian:setTag(66)
Image_hongdian:setCascadeColorEnabled(true)
Image_hongdian:setCascadeOpacityEnabled(true)
Image_hongdian:setVisible(false)
Image_hongdian:setPosition(396.3488, 197.1405)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_hongdian)
layout:setPositionPercentX(0.3670)
layout:setPositionPercentY(0.1027)
layout:setPercentWidth(0.0213)
layout:setPercentHeight(0.0120)
layout:setSize({width = 23.0000, height = 23.0000})
layout:setLeftMargin(384.8488)
layout:setRightMargin(672.1512)
layout:setTopMargin(1711.3590)
layout:setBottomMargin(185.6405)
Layer:addChild(Image_hongdian)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000