--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(202)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_title
local Image_title = ccui.ImageView:create()
Image_title:ignoreContentAdaptWithSize(false)
Image_title:loadTexture("Image/UI/MainUI/kuangup.png",0)
Image_title:setScale9Enabled(true)
Image_title:setCapInsets({x = 356, y = 35, width = 368, height = 38})
Image_title:setLayoutComponentEnabled(true)
Image_title:setName("Image_title")
Image_title:setTag(195)
Image_title:setCascadeColorEnabled(true)
Image_title:setCascadeOpacityEnabled(true)
Image_title:setAnchorPoint(0.5000, 1.0000)
Image_title:setPosition(540.0000, 1920.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0562)
layout:setSize({width = 1080.0000, height = 108.0000})
layout:setBottomMargin(1812.0000)
Layer:addChild(Image_title)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("Image/UI/MenuUI/back.png",0)
Button_back:loadTexturePressed("Image/UI/MenuUI/back2.png",0)
Button_back:loadTextureDisabled("Default/Button_Disable.png",0)
Button_back:setTitleFontSize(14)
Button_back:setTitleColor({r = 65, g = 65, b = 70})
Button_back:setScale9Enabled(true)
Button_back:setCapInsets({x = 15, y = 11, width = 145, height = 56})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(196)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(100.0000, 54.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.0926)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1620)
layout:setPercentHeight(0.7222)
layout:setSize({width = 175.0000, height = 78.0000})
layout:setLeftMargin(12.5000)
layout:setRightMargin(892.5000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(15.0000)
Image_title:addChild(Button_back)

--Create Text_tital
local Text_tital = ccui.Text:create()
Text_tital:ignoreContentAdaptWithSize(true)
Text_tital:setTextAreaSize({width = 0, height = 0})
Text_tital:setFontName("Font/HYCFS.ttf")
Text_tital:setFontSize(60)
Text_tital:setString([[招式描述选择]])
Text_tital:setTextHorizontalAlignment(1)
Text_tital:setTextVerticalAlignment(1)
Text_tital:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_tital:setLayoutComponentEnabled(true)
Text_tital:setName("Text_tital")
Text_tital:setTag(197)
Text_tital:setCascadeColorEnabled(true)
Text_tital:setCascadeOpacityEnabled(true)
Text_tital:setPosition(540.0000, 54.0000)
Text_tital:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_tital)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3380)
layout:setPercentHeight(0.6481)
layout:setSize({width = 365.0000, height = 70.0000})
layout:setLeftMargin(357.5000)
layout:setRightMargin(357.5000)
layout:setTopMargin(19.0000)
layout:setBottomMargin(19.0000)
Image_title:addChild(Text_tital)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setItemsMargin(22)
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(0)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(194)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setPosition(25.0000, 332.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.0231)
layout:setPositionPercentY(0.1729)
layout:setPercentWidth(0.9537)
layout:setPercentHeight(0.7552)
layout:setSize({width = 1030.0000, height = 1450.0000})
layout:setLeftMargin(25.0000)
layout:setRightMargin(25.0000)
layout:setTopMargin(138.0000)
layout:setBottomMargin(332.0000)
Layer:addChild(ListView_1)

--Create Panel_zhaoDsc
local Panel_zhaoDsc = ccui.Layout:create()
Panel_zhaoDsc:ignoreContentAdaptWithSize(false)
Panel_zhaoDsc:setClippingEnabled(false)
Panel_zhaoDsc:setTouchEnabled(true);
Panel_zhaoDsc:setLayoutComponentEnabled(true)
Panel_zhaoDsc:setName("Panel_zhaoDsc")
Panel_zhaoDsc:setTag(184)
Panel_zhaoDsc:setCascadeColorEnabled(true)
Panel_zhaoDsc:setCascadeOpacityEnabled(true)
Panel_zhaoDsc:setAnchorPoint(0.5000, 0.5000)
Panel_zhaoDsc:setPosition(1754.3900, 1240.2020)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_zhaoDsc)
layout:setPositionPercentX(1.6244)
layout:setPositionPercentY(0.6459)
layout:setPercentWidth(0.9537)
layout:setPercentHeight(0.1198)
layout:setSize({width = 1030.0000, height = 230.0000})
layout:setLeftMargin(1239.3900)
layout:setRightMargin(-1189.3900)
layout:setTopMargin(564.7979)
layout:setBottomMargin(1125.2020)
Layer:addChild(Panel_zhaoDsc)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Image/UI/SelfCreatedSkillUI/4.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(206)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(515.0000, 115.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1030.0000, height = 230.0000})
Panel_zhaoDsc:addChild(Image_1)

--Create Image_xuanzhong
local Image_xuanzhong = ccui.ImageView:create()
Image_xuanzhong:ignoreContentAdaptWithSize(false)
Image_xuanzhong:loadTexture("Image/UI/SelfCreatedSkillUI/kuang5.png",0)
Image_xuanzhong:setLayoutComponentEnabled(true)
Image_xuanzhong:setName("Image_xuanzhong")
Image_xuanzhong:setTag(330)
Image_xuanzhong:setCascadeColorEnabled(true)
Image_xuanzhong:setCascadeOpacityEnabled(true)
Image_xuanzhong:setVisible(false)
Image_xuanzhong:setPosition(515.0000, 115.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_xuanzhong)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1030.0000, height = 230.0000})
Panel_zhaoDsc:addChild(Image_xuanzhong)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:ignoreContentAdaptWithSize(false)
Text_3:setFontName("Font/default.ttf")
Text_3:setFontSize(42)
Text_3:setString([[招式描述详情招式描述详情招式描述详情招式描述详情招式描述详情招式描述详情招式描述详情招式描述详情]])
Text_3:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setTag(203)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
Text_3:setPosition(515.0858, 123.6130)
Text_3:setTextColor({r = 201, g = 201, b = 201})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentX(0.5001)
layout:setPositionPercentY(0.5374)
layout:setPercentWidth(0.9515)
layout:setPercentHeight(0.7826)
layout:setSize({width = 980.0000, height = 180.0000})
layout:setLeftMargin(25.0858)
layout:setRightMargin(24.9142)
layout:setTopMargin(16.3870)
layout:setBottomMargin(33.6130)
Panel_zhaoDsc:addChild(Text_3)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("Image/UI/SelfCreatedSkillUI/suo2.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(216)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(515.0000, 122.8959)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5343)
layout:setPercentWidth(0.6748)
layout:setPercentHeight(0.4696)
layout:setSize({width = 695.0000, height = 108.0000})
layout:setLeftMargin(167.5000)
layout:setRightMargin(167.5000)
layout:setTopMargin(53.1041)
layout:setBottomMargin(68.8959)
Panel_zhaoDsc:addChild(Image_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000000