--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 278.0000, height = 278.0000})

--Create Click_Area
local Click_Area = ccui.Layout:create()
Click_Area:ignoreContentAdaptWithSize(false)
Click_Area:setClippingEnabled(false)
Click_Area:setBackGroundColorOpacity(102)
Click_Area:setTouchEnabled(true);
Click_Area:setLayoutComponentEnabled(true)
Click_Area:setName("Click_Area")
Click_Area:setTag(8)
Click_Area:setCascadeColorEnabled(true)
Click_Area:setCascadeOpacityEnabled(true)
Click_Area:setPosition(0.0000, 2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Click_Area)
layout:setPositionPercentY(0.0072)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 278.0000, height = 278.0000})
layout:setTopMargin(-2.0000)
layout:setBottomMargin(2.0000)
Layer:addChild(Click_Area)

--Create Img_bg
local Img_bg = ccui.ImageView:create()
Img_bg:ignoreContentAdaptWithSize(false)
Img_bg:loadTexture("Image/UI/AttrUI/di1.png",0)
Img_bg:setLayoutComponentEnabled(true)
Img_bg:setName("Img_bg")
Img_bg:setTag(144)
Img_bg:setCascadeColorEnabled(true)
Img_bg:setCascadeOpacityEnabled(true)
Img_bg:setPosition(139.0000, 139.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9209)
layout:setPercentHeight(0.9209)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Layer:addChild(Img_bg)

--Create Img_Static
local Img_Static = ccui.ImageView:create()
Img_Static:ignoreContentAdaptWithSize(false)
Img_Static:loadTexture("Image/UI/AttrUI/nv/9.png",0)
Img_Static:setLayoutComponentEnabled(true)
Img_Static:setName("Img_Static")
Img_Static:setTag(145)
Img_Static:setCascadeColorEnabled(true)
Img_Static:setCascadeOpacityEnabled(true)
Img_Static:setPosition(139.0000, 139.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_Static)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9209)
layout:setPercentHeight(0.9209)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Layer:addChild(Img_Static)

--Create AnimParent
local AnimParent = ccui.Layout:create()
AnimParent:ignoreContentAdaptWithSize(false)
AnimParent:setClippingEnabled(true)
AnimParent:setBackGroundColorOpacity(102)
AnimParent:setLayoutComponentEnabled(true)
AnimParent:setName("AnimParent")
AnimParent:setTag(389)
AnimParent:setCascadeColorEnabled(true)
AnimParent:setCascadeOpacityEnabled(true)
AnimParent:setAnchorPoint(0.5000, 0.5000)
AnimParent:setPosition(139.0000, 139.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AnimParent)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9209)
layout:setPercentHeight(0.9209)
layout:setSize({width = 256.0000, height = 256.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Layer:addChild(AnimParent)

--Create Node_AnimPos
local Node_AnimPos=cc.Node:create()
Node_AnimPos:setName("Node_AnimPos")
Node_AnimPos:setTag(146)
Node_AnimPos:setCascadeColorEnabled(true)
Node_AnimPos:setCascadeOpacityEnabled(true)
Node_AnimPos:setVisible(false)
Node_AnimPos:setPosition(128.0000, 128.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_AnimPos)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(128.0000)
layout:setRightMargin(128.0000)
layout:setTopMargin(128.0000)
layout:setBottomMargin(128.0000)
AnimParent:addChild(Node_AnimPos)

--Create Node_EffectPos
local Node_EffectPos=cc.Node:create()
Node_EffectPos:setName("Node_EffectPos")
Node_EffectPos:setTag(147)
Node_EffectPos:setCascadeColorEnabled(true)
Node_EffectPos:setCascadeOpacityEnabled(true)
Node_EffectPos:setVisible(false)
Node_EffectPos:setPosition(128.0000, 128.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_EffectPos)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(128.0000)
layout:setRightMargin(128.0000)
layout:setTopMargin(128.0000)
layout:setBottomMargin(128.0000)
AnimParent:addChild(Node_EffectPos)

--Create Img_border
local Img_border = ccui.ImageView:create()
Img_border:ignoreContentAdaptWithSize(false)
Img_border:loadTexture("Image/UI/AttrUI/frame/border-black-hollow.png",0)
Img_border:setLayoutComponentEnabled(true)
Img_border:setName("Img_border")
Img_border:setTag(46)
Img_border:setCascadeColorEnabled(true)
Img_border:setCascadeOpacityEnabled(true)
Img_border:setPosition(139.0000, 139.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_border)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 278.0000, height = 278.0000})
Layer:addChild(Img_border)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000