--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(156)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create ListView_map
local ListView_map = ccui.ListView:create()
ListView_map:setItemsMargin(46)
ListView_map:setDirection(1)
ListView_map:setGravity(0)
ListView_map:ignoreContentAdaptWithSize(false)
ListView_map:setClippingEnabled(true)
ListView_map:setBackGroundColorType(1)
ListView_map:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_map:setBackGroundColorOpacity(0)
ListView_map:setLayoutComponentEnabled(true)
ListView_map:setName("ListView_map")
ListView_map:setTag(148)
ListView_map:setCascadeColorEnabled(true)
ListView_map:setCascadeOpacityEnabled(true)
ListView_map:setPosition(54.0000, 196.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_map)
layout:setPositionPercentX(0.0500)
layout:setPositionPercentY(0.1021)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.8125)
layout:setSize({width = 972.0000, height = 1560.0000})
layout:setLeftMargin(54.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(164.0000)
layout:setBottomMargin(196.0000)
Layer:addChild(ListView_map)

--Create Panel_item
local Panel_item = ccui.Layout:create()
Panel_item:ignoreContentAdaptWithSize(false)
Panel_item:setBackGroundImage("Image/UI/MapUI/quananniu.png",0)
Panel_item:setClippingEnabled(true)
Panel_item:setBackGroundImageCapInsets({x = 341, y = 48, width = 265, height = 50})
Panel_item:setBackGroundImageScale9Enabled(true)
Panel_item:setTouchEnabled(true);
Panel_item:setLayoutComponentEnabled(true)
Panel_item:setName("Panel_item")
Panel_item:setTag(149)
Panel_item:setCascadeColorEnabled(true)
Panel_item:setCascadeOpacityEnabled(true)
Panel_item:setAnchorPoint(0.5000, 0.5000)
Panel_item:setPosition(1629.0330, 1662.8560)
Panel_item:setOpacity(213)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_item)
layout:setPositionPercentX(1.5084)
layout:setPositionPercentY(0.8661)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.0760)
layout:setSize({width = 972.0000, height = 146.0000})
layout:setLeftMargin(1143.0330)
layout:setRightMargin(-1035.0330)
layout:setTopMargin(184.1440)
layout:setBottomMargin(1589.8560)
Layer:addChild(Panel_item)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("Image/BaseUI/txt-bg3.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(113)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(486.0000, 72.9693)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4998)
layout:setPercentWidth(0.6492)
layout:setPercentHeight(0.8014)
layout:setSize({width = 631.0000, height = 117.0000})
layout:setLeftMargin(170.5000)
layout:setRightMargin(170.5000)
layout:setTopMargin(14.5307)
layout:setBottomMargin(14.4693)
Panel_item:addChild(Image_2)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/HYCFS.ttf")
Text_name:setFontSize(88)
Text_name:setString([[副本名称]])
Text_name:setTextVerticalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 4)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(150)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setPosition(485.9989, 70.8457)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4852)
layout:setPercentWidth(0.3632)
layout:setPercentHeight(0.7123)
layout:setSize({width = 353.0000, height = 104.0000})
layout:setLeftMargin(309.4989)
layout:setRightMargin(309.5011)
layout:setTopMargin(23.1543)
layout:setBottomMargin(18.8457)
Panel_item:addChild(Text_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000000