return {["Sheet1"]={},["wxtj"]={["1"]={["id"]=1,["level"]=1,["type"]=[[neigong]],["value"]=[[0;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将内功境界划分为五层，每一层则以掌握的内功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初通气道NOR
WHT二层：NORHIB任督相通NOR
WHT三层：NORHIM气行周天NOR
WHT四层：NORHIY乾坤归元NOR
WHT五层：NORHIR功参造化NOR]],["wxtext"]=[[HIG初通气道NOR]]},["10"]={["id"]=10,["level"]=5,["type"]=[[qinggong]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将轻功境界划分为五层，每一层则以掌握的轻功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG轻身初试NOR
WHT二层：NORHIB身轻如燕NOR
WHT三层：NORHIM草上疾飞NOR
WHT四层：NORHIY踏雪无痕NOR
WHT五层：NORHIR一苇渡江NOR]],["wxtext"]=[[HIR一苇渡江NOR]],["wxtexts"]=[[轻折一苇渡长江]],["wxtstext"]=[[其中，你的轻功已然进退随心，飘忽若神。]]},["11"]={["id"]=11,["level"]=1,["type"]=[[zhishi]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将绝世武学类境界划分为五层，每一层则以掌握的绝世武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG粗通文墨NOR
WHT二层：NORHIB学贯州郡NOR
WHT三层：NORHIM满腹经纶NOR
WHT四层：NORHIY学富五车NOR
WHT五层：NORHIR博古通今NOR]],["wxtext"]=[[HIG粗通文墨NOR]]},["12"]={["id"]=12,["level"]=2,["type"]=[[zhishi]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将绝世武学类境界划分为五层，每一层则以掌握的绝世武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG粗通文墨NOR
WHT二层：NORHIB学贯州郡NOR
WHT三层：NORHIM满腹经纶NOR
WHT四层：NORHIY学富五车NOR
WHT五层：NORHIR博古通今NOR]],["wxtext"]=[[HIB学贯州郡NOR]],["wxtexts"]=[[兰庭才名满州郡]]},["13"]={["id"]=13,["level"]=3,["type"]=[[zhishi]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将绝世武学类境界划分为五层，每一层则以掌握的绝世武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG粗通文墨NOR
WHT二层：NORHIB学贯州郡NOR
WHT三层：NORHIM满腹经纶NOR
WHT四层：NORHIY学富五车NOR
WHT五层：NORHIR博古通今NOR]],["wxtext"]=[[HIM满腹经纶NOR]],["wxtexts"]=[[经纶满腹安天下]],["wxtstext"]=[[其中，你的知识造诣之高，可谓上知天文，下晓地理。]]},["14"]={["id"]=14,["level"]=4,["type"]=[[zhishi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将绝世武学类境界划分为五层，每一层则以掌握的绝世武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG粗通文墨NOR
WHT二层：NORHIB学贯州郡NOR
WHT三层：NORHIM满腹经纶NOR
WHT四层：NORHIY学富五车NOR
WHT五层：NORHIR博古通今NOR]],["wxtext"]=[[HIY学富五车NOR]],["wxtexts"]=[[学识冠绝岂五车]],["wxtstext"]=[[其中，你的知识造诣之高，可谓上知天文，下晓地理。]]},["15"]={["id"]=15,["level"]=5,["type"]=[[zhishi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将绝世武学类境界划分为五层，每一层则以掌握的绝世武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG粗通文墨NOR
WHT二层：NORHIB学贯州郡NOR
WHT三层：NORHIM满腹经纶NOR
WHT四层：NORHIY学富五车NOR
WHT五层：NORHIR博古通今NOR]],["wxtext"]=[[HIR博古通今NOR]],["wxtexts"]=[[博知古事晓今朝]],["wxtstext"]=[[其中，你的知识造诣之高，可谓上知天文，下晓地理。]]},["16"]={["id"]=16,["level"]=1,["type"]=[[quan]],["value"]=[[0;750]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将拳法境界划分为五层，每一层则以掌握的拳法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG拳法初通NOR
WHT二层：NORHIB名起双拳NOR
WHT三层：NORHIM拳镇四海NOR
WHT四层：NORHIY拳道巨匠NOR
WHT五层：NORHIR拳冠天下NOR]],["wxtext"]=[[HIG拳法初通NOR]]},["17"]={["id"]=17,["level"]=2,["type"]=[[quan]],["value"]=[[751;1500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将拳法境界划分为五层，每一层则以掌握的拳法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG拳法初通NOR
WHT二层：NORHIB名起双拳NOR
WHT三层：NORHIM拳镇四海NOR
WHT四层：NORHIY拳道巨匠NOR
WHT五层：NORHIR拳冠天下NOR]],["wxtext"]=[[HIB名起双拳NOR]],["wxtexts"]=[[凌云双拳名鹊起]]},["18"]={["id"]=18,["level"]=3,["type"]=[[quan]],["value"]=[[1501;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将拳法境界划分为五层，每一层则以掌握的拳法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG拳法初通NOR
WHT二层：NORHIB名起双拳NOR
WHT三层：NORHIM拳镇四海NOR
WHT四层：NORHIY拳道巨匠NOR
WHT五层：NORHIR拳冠天下NOR]],["wxtext"]=[[HIM拳镇四海NOR]],["wxtexts"]=[[拳道盛名震四海]],["wxtstext"]=[[其中，你的拳法可撼青云。每每迎敌之际，你都能将天下各路拳法信手拈来，随心而动。]]},["19"]={["id"]=19,["level"]=4,["type"]=[[quan]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将拳法境界划分为五层，每一层则以掌握的拳法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG拳法初通NOR
WHT二层：NORHIB名起双拳NOR
WHT三层：NORHIM拳镇四海NOR
WHT四层：NORHIY拳道巨匠NOR
WHT五层：NORHIR拳冠天下NOR]],["wxtext"]=[[HIY拳道巨匠NOR]],["wxtexts"]=[[拳名四方为巨匠]],["wxtstext"]=[[其中，你的拳法可撼青云。每每迎敌之际，你都能将天下各路拳法信手拈来，随心而动。]]},["2"]={["id"]=2,["level"]=2,["type"]=[[neigong]],["value"]=[[1001;4000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将内功境界划分为五层，每一层则以掌握的内功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初通气道NOR
WHT二层：NORHIB任督相通NOR
WHT三层：NORHIM气行周天NOR
WHT四层：NORHIY乾坤归元NOR
WHT五层：NORHIR功参造化NOR]],["wxtext"]=[[HIB任督相通NOR]],["wxtexts"]=[[气通任督破玄关]]},["20"]={["id"]=20,["level"]=5,["type"]=[[quan]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将拳法境界划分为五层，每一层则以掌握的拳法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG拳法初通NOR
WHT二层：NORHIB名起双拳NOR
WHT三层：NORHIM拳镇四海NOR
WHT四层：NORHIY拳道巨匠NOR
WHT五层：NORHIR拳冠天下NOR]],["wxtext"]=[[HIR拳冠天下NOR]],["wxtexts"]=[[拳道无双冠天下]],["wxtstext"]=[[其中，你的拳法可撼青云。每每迎敌之际，你都能将天下各路拳法信手拈来，随心而动。]]},["21"]={["id"]=21,["level"]=1,["type"]=[[zhang]],["value"]=[[0;750]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将掌法境界划分为五层，每一层则以掌握的掌法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG习掌有得NOR
WHT二层：NORHIB一方名掌NOR
WHT三层：NORHIM掌动九州NOR
WHT四层：NORHIY掌补苍天NOR
WHT五层：NORHIR掌撼天地NOR]],["wxtext"]=[[HIG习掌有得NOR]]},["22"]={["id"]=22,["level"]=2,["type"]=[[zhang]],["value"]=[[751;1500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将掌法境界划分为五层，每一层则以掌握的掌法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG习掌有得NOR
WHT二层：NORHIB一方名掌NOR
WHT三层：NORHIM掌动九州NOR
WHT四层：NORHIY掌补苍天NOR
WHT五层：NORHIR掌撼天地NOR]],["wxtext"]=[[HIB一方名掌NOR]],["wxtexts"]=[[名掌初成显一方]]},["23"]={["id"]=23,["level"]=3,["type"]=[[zhang]],["value"]=[[1501;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将掌法境界划分为五层，每一层则以掌握的掌法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG习掌有得NOR
WHT二层：NORHIB一方名掌NOR
WHT三层：NORHIM掌动九州NOR
WHT四层：NORHIY掌补苍天NOR
WHT五层：NORHIR掌撼天地NOR]],["wxtext"]=[[HIM掌动九州NOR]],["wxtexts"]=[[一掌风动九州月]],["wxtstext"]=[[其中，你的掌法刚柔并济，既有柔劲缠敌之妙，亦有刚猛弊敌之威。]]},["24"]={["id"]=24,["level"]=4,["type"]=[[zhang]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将掌法境界划分为五层，每一层则以掌握的掌法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG习掌有得NOR
WHT二层：NORHIB一方名掌NOR
WHT三层：NORHIM掌动九州NOR
WHT四层：NORHIY掌补苍天NOR
WHT五层：NORHIR掌撼天地NOR]],["wxtext"]=[[HIY掌补苍天NOR]],["wxtexts"]=[[掌现危崖补苍天]],["wxtstext"]=[[其中，你的掌法刚柔并济，既有柔劲缠敌之妙，亦有刚猛弊敌之威。]]},["25"]={["id"]=25,["level"]=5,["type"]=[[zhang]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将掌法境界划分为五层，每一层则以掌握的掌法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG习掌有得NOR
WHT二层：NORHIB一方名掌NOR
WHT三层：NORHIM掌动九州NOR
WHT四层：NORHIY掌补苍天NOR
WHT五层：NORHIR掌撼天地NOR]],["wxtext"]=[[HIR掌撼天地NOR]],["wxtexts"]=[[须臾一掌撼天地]],["wxtstext"]=[[其中，你的掌法刚柔并济，既有柔劲缠敌之妙，亦有刚猛弊敌之威。]]},["26"]={["id"]=26,["level"]=1,["type"]=[[zhi]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将指法境界划分为五层，每一层则以掌握的指法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG指道初论NOR
WHT二层：NORHIB指法新秀NOR
WHT三层：NORHIM灵指无伦NOR
WHT四层：NORHIY化指为刃NOR
WHT五层：NORHIR一指擎天NOR]],["wxtext"]=[[HIG指道初论NOR]]},["27"]={["id"]=27,["level"]=2,["type"]=[[zhi]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将指法境界划分为五层，每一层则以掌握的指法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG指道初论NOR
WHT二层：NORHIB指法新秀NOR
WHT三层：NORHIM灵指无伦NOR
WHT四层：NORHIY化指为刃NOR
WHT五层：NORHIR一指擎天NOR]],["wxtext"]=[[HIB指法新秀NOR]],["wxtexts"]=[[指法小成出新秀]]},["28"]={["id"]=28,["level"]=3,["type"]=[[zhi]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将指法境界划分为五层，每一层则以掌握的指法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG指道初论NOR
WHT二层：NORHIB指法新秀NOR
WHT三层：NORHIM灵指无伦NOR
WHT四层：NORHIY化指为刃NOR
WHT五层：NORHIR一指擎天NOR]],["wxtext"]=[[HIM灵指无伦NOR]],["wxtexts"]=[[灵指无影碎虚空]],["wxtstext"]=[[其中，你的指法外则轻盈潇洒，内则刚劲迅猛。]]},["29"]={["id"]=29,["level"]=4,["type"]=[[zhi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将指法境界划分为五层，每一层则以掌握的指法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG指道初论NOR
WHT二层：NORHIB指法新秀NOR
WHT三层：NORHIM灵指无伦NOR
WHT四层：NORHIY化指为刃NOR
WHT五层：NORHIR一指擎天NOR]],["wxtext"]=[[HIY化指为刃NOR]],["wxtexts"]=[[刃出刀虚实为指]],["wxtstext"]=[[其中，你的指法外则轻盈潇洒，内则刚劲迅猛。]]},["3"]={["id"]=3,["level"]=3,["type"]=[[neigong]],["value"]=[[4001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将内功境界划分为五层，每一层则以掌握的内功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初通气道NOR
WHT二层：NORHIB任督相通NOR
WHT三层：NORHIM气行周天NOR
WHT四层：NORHIY乾坤归元NOR
WHT五层：NORHIR功参造化NOR]],["wxtext"]=[[HIM气行周天NOR]],["wxtexts"]=[[真气连绵行周天]],["wxtstext"]=[[其中，你的内功深厚，内力如浩瀚沧海，深不可测。]]},["30"]={["id"]=30,["level"]=5,["type"]=[[zhi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将指法境界划分为五层，每一层则以掌握的指法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG指道初论NOR
WHT二层：NORHIB指法新秀NOR
WHT三层：NORHIM灵指无伦NOR
WHT四层：NORHIY化指为刃NOR
WHT五层：NORHIR一指擎天NOR]],["wxtext"]=[[HIR一指擎天NOR]],["wxtexts"]=[[待天翻覆一指擎]],["wxtstext"]=[[其中，你的指法外则轻盈潇洒，内则刚劲迅猛。]]},["31"]={["id"]=31,["level"]=1,["type"]=[[zhua]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将爪法境界划分为五层，每一层则以掌握的爪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初窥爪道NOR
WHT二层：NORHIB爪冠州府NOR
WHT三层：NORHIM爪道宗师NOR
WHT四层：NORHIY爪镇四方NOR
WHT五层：NORHIR神爪裂天NOR]],["wxtext"]=[[HIG初窥爪道NOR]]},["32"]={["id"]=32,["level"]=2,["type"]=[[zhua]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将爪法境界划分为五层，每一层则以掌握的爪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初窥爪道NOR
WHT二层：NORHIB爪冠州府NOR
WHT三层：NORHIM爪道宗师NOR
WHT四层：NORHIY爪镇四方NOR
WHT五层：NORHIR神爪裂天NOR]],["wxtext"]=[[HIB爪冠州府NOR]],["wxtexts"]=[[飞爪连环冠州府]]},["33"]={["id"]=33,["level"]=3,["type"]=[[zhua]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将爪法境界划分为五层，每一层则以掌握的爪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初窥爪道NOR
WHT二层：NORHIB爪冠州府NOR
WHT三层：NORHIM爪道宗师NOR
WHT四层：NORHIY爪镇四方NOR
WHT五层：NORHIR神爪裂天NOR]],["wxtext"]=[[HIM爪道宗师NOR]],["wxtexts"]=[[鸿爪无影冠当世]],["wxtstext"]=[[其中，你的爪法迅捷刚烈，挫骨拿穴，疾如飞电。]]},["34"]={["id"]=34,["level"]=4,["type"]=[[zhua]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将爪法境界划分为五层，每一层则以掌握的爪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初窥爪道NOR
WHT二层：NORHIB爪冠州府NOR
WHT三层：NORHIM爪道宗师NOR
WHT四层：NORHIY爪镇四方NOR
WHT五层：NORHIR神爪裂天NOR]],["wxtext"]=[[HIY爪镇四方NOR]],["wxtexts"]=[[爪镇江河定四方]],["wxtstext"]=[[其中，你的爪法迅捷刚烈，挫骨拿穴，疾如飞电。]]},["35"]={["id"]=35,["level"]=5,["type"]=[[zhua]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将爪法境界划分为五层，每一层则以掌握的爪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初窥爪道NOR
WHT二层：NORHIB爪冠州府NOR
WHT三层：NORHIM爪道宗师NOR
WHT四层：NORHIY爪镇四方NOR
WHT五层：NORHIR神爪裂天NOR]],["wxtext"]=[[HIR神爪裂天NOR]],["wxtexts"]=[[五爪擎天倒星辰]],["wxtstext"]=[[其中，你的爪法迅捷刚烈，挫骨拿穴，疾如飞电。]]},["36"]={["id"]=36,["level"]=1,["type"]=[[tui]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将腿法境界划分为五层，每一层则以掌握的腿法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG腿功小成NOR
WHT二层：NORHIB腿法新秀NOR
WHT三层：NORHIM神腿无双NOR
WHT四层：NORHIY腿法宗师NOR
WHT五层：NORHIR腿荡八荒NOR]],["wxtext"]=[[HIG腿功小成NOR]]},["37"]={["id"]=37,["level"]=2,["type"]=[[tui]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将腿法境界划分为五层，每一层则以掌握的腿法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG腿功小成NOR
WHT二层：NORHIB腿法新秀NOR
WHT三层：NORHIM神腿无双NOR
WHT四层：NORHIY腿法宗师NOR
WHT五层：NORHIR腿荡八荒NOR]],["wxtext"]=[[HIB腿法新秀NOR]],["wxtexts"]=[[疾踢飞踏独秀群]]},["38"]={["id"]=38,["level"]=3,["type"]=[[tui]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将腿法境界划分为五层，每一层则以掌握的腿法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG腿功小成NOR
WHT二层：NORHIB腿法新秀NOR
WHT三层：NORHIM神腿无双NOR
WHT四层：NORHIY腿法宗师NOR
WHT五层：NORHIR腿荡八荒NOR]],["wxtext"]=[[HIM神腿无双NOR]],["wxtexts"]=[[飞腿夺魂劲无双]],["wxtstext"]=[[其中，你的腿法踢击迅猛，灵动无双。]]},["39"]={["id"]=39,["level"]=4,["type"]=[[tui]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将腿法境界划分为五层，每一层则以掌握的腿法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG腿功小成NOR
WHT二层：NORHIB腿法新秀NOR
WHT三层：NORHIM神腿无双NOR
WHT四层：NORHIY腿法宗师NOR
WHT五层：NORHIR腿荡八荒NOR]],["wxtext"]=[[HIY腿法宗师NOR]],["wxtexts"]=[[破晓顿悟腿中道]],["wxtstext"]=[[其中，你的腿法踢击迅猛，灵动无双。]]},["4"]={["id"]=4,["level"]=4,["type"]=[[neigong]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将内功境界划分为五层，每一层则以掌握的内功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初通气道NOR
WHT二层：NORHIB任督相通NOR
WHT三层：NORHIM气行周天NOR
WHT四层：NORHIY乾坤归元NOR
WHT五层：NORHIR功参造化NOR]],["wxtext"]=[[HIY乾坤归元NOR]],["wxtexts"]=[[劲行乾坤气归元]],["wxtstext"]=[[其中，你的内功深厚，内力如浩瀚沧海，深不可测。]]},["40"]={["id"]=40,["level"]=5,["type"]=[[tui]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将腿法境界划分为五层，每一层则以掌握的腿法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG腿功小成NOR
WHT二层：NORHIB腿法新秀NOR
WHT三层：NORHIM神腿无双NOR
WHT四层：NORHIY腿法宗师NOR
WHT五层：NORHIR腿荡八荒NOR]],["wxtext"]=[[HIR腿荡八荒NOR]],["wxtexts"]=[[腿影无常荡八荒]],["wxtstext"]=[[其中，你的腿法踢击迅猛，灵动无双。]]},["41"]={["id"]=41,["level"]=1,["type"]=[[dao]],["value"]=[[0;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将刀法境界划分为五层，每一层则以掌握的刀法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG杀鸡宰牛NOR
WHT二层：NORHIB刀意似水NOR
WHT三层：NORHIM弯刀作月NOR
WHT四层：NORHIY刀平武林NOR
WHT五层：NORHIR纵刀寰宇NOR]],["wxtext"]=[[HIG杀鸡宰牛NOR]]},["42"]={["id"]=42,["level"]=2,["type"]=[[dao]],["value"]=[[1001;2000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将刀法境界划分为五层，每一层则以掌握的刀法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG杀鸡宰牛NOR
WHT二层：NORHIB刀意似水NOR
WHT三层：NORHIM弯刀作月NOR
WHT四层：NORHIY刀平武林NOR
WHT五层：NORHIR纵刀寰宇NOR]],["wxtext"]=[[HIB刀意似水NOR]],["wxtexts"]=[[刀意似水融春雨]]},["43"]={["id"]=43,["level"]=3,["type"]=[[dao]],["value"]=[[2001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将刀法境界划分为五层，每一层则以掌握的刀法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG杀鸡宰牛NOR
WHT二层：NORHIB刀意似水NOR
WHT三层：NORHIM弯刀作月NOR
WHT四层：NORHIY刀平武林NOR
WHT五层：NORHIR纵刀寰宇NOR]],["wxtext"]=[[HIM弯刀作月NOR]],["wxtexts"]=[[弯刀作月碎飞雪]],["wxtstext"]=[[其中，你的刀法圆转如意，精妙绝伦。]]},["44"]={["id"]=44,["level"]=4,["type"]=[[dao]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将刀法境界划分为五层，每一层则以掌握的刀法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG杀鸡宰牛NOR
WHT二层：NORHIB刀意似水NOR
WHT三层：NORHIM弯刀作月NOR
WHT四层：NORHIY刀平武林NOR
WHT五层：NORHIR纵刀寰宇NOR]],["wxtext"]=[[HIY刀平武林NOR]],["wxtexts"]=[[刀断流水破长风]],["wxtstext"]=[[其中，你的刀法圆转如意，精妙绝伦。]]},["45"]={["id"]=45,["level"]=5,["type"]=[[dao]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将刀法境界划分为五层，每一层则以掌握的刀法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG杀鸡宰牛NOR
WHT二层：NORHIB刀意似水NOR
WHT三层：NORHIM弯刀作月NOR
WHT四层：NORHIY刀平武林NOR
WHT五层：NORHIR纵刀寰宇NOR]],["wxtext"]=[[HIR纵刀寰宇NOR]],["wxtexts"]=[[刀横大荒纵寰宇]],["wxtstext"]=[[其中，你的刀法圆转如意，精妙绝伦。]]},["46"]={["id"]=46,["level"]=1,["type"]=[[jian]],["value"]=[[0;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将剑法境界划分为五层，每一层则以掌握的剑法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG剑器初名NOR
WHT二层：NORHIB剑试括羽NOR
WHT三层：NORHIM折枝作剑NOR
WHT四层：NORHIY仗剑天涯NOR
WHT五层：NORHIR剑扫六合NOR]],["wxtext"]=[[HIG剑器初名NOR]]},["47"]={["id"]=47,["level"]=2,["type"]=[[jian]],["value"]=[[1001;2000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将剑法境界划分为五层，每一层则以掌握的剑法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG剑器初名NOR
WHT二层：NORHIB剑试括羽NOR
WHT三层：NORHIM折枝作剑NOR
WHT四层：NORHIY仗剑天涯NOR
WHT五层：NORHIR剑扫六合NOR]],["wxtext"]=[[HIB剑试括羽NOR]],["wxtexts"]=[[剑试括羽下青山]]},["48"]={["id"]=48,["level"]=3,["type"]=[[jian]],["value"]=[[2001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将剑法境界划分为五层，每一层则以掌握的剑法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG剑器初名NOR
WHT二层：NORHIB剑试括羽NOR
WHT三层：NORHIM折枝作剑NOR
WHT四层：NORHIY仗剑天涯NOR
WHT五层：NORHIR剑扫六合NOR]],["wxtext"]=[[HIM折枝作剑NOR]],["wxtexts"]=[[折枝作剑出寒锋]],["wxtstext"]=[[其中，你的剑法可逸清俊，神奥无方。]]},["49"]={["id"]=49,["level"]=4,["type"]=[[jian]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将剑法境界划分为五层，每一层则以掌握的剑法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG剑器初名NOR
WHT二层：NORHIB剑试括羽NOR
WHT三层：NORHIM折枝作剑NOR
WHT四层：NORHIY仗剑天涯NOR
WHT五层：NORHIR剑扫六合NOR]],["wxtext"]=[[HIY仗剑天涯NOR]],["wxtexts"]=[[只影仗剑天涯处]],["wxtstext"]=[[其中，你的剑法可逸清俊，神奥无方。]]},["5"]={["id"]=5,["level"]=5,["type"]=[[neigong]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将内功境界划分为五层，每一层则以掌握的内功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG初通气道NOR
WHT二层：NORHIB任督相通NOR
WHT三层：NORHIM气行周天NOR
WHT四层：NORHIY乾坤归元NOR
WHT五层：NORHIR功参造化NOR]],["wxtext"]=[[HIR功参造化NOR]],["wxtexts"]=[[灵脉功成造化生]],["wxtstext"]=[[其中，你的内功深厚，内力如浩瀚沧海，深不可测。]]},["50"]={["id"]=50,["level"]=5,["type"]=[[jian]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将剑法境界划分为五层，每一层则以掌握的剑法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG剑器初名NOR
WHT二层：NORHIB剑试括羽NOR
WHT三层：NORHIM折枝作剑NOR
WHT四层：NORHIY仗剑天涯NOR
WHT五层：NORHIR剑扫六合NOR]],["wxtext"]=[[HIR剑扫六合NOR]],["wxtexts"]=[[破晓一剑扫六合]],["wxtstext"]=[[其中，你的剑法可逸清俊，神奥无方。]]},["51"]={["id"]=51,["level"]=1,["type"]=[[gun]],["value"]=[[0;650]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将棍法境界划分为五层，每一层则以掌握的棍法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG似担若犁NOR
WHT二层：NORHIB持棍如松NOR
WHT三层：NORHIM棍碎清泉NOR
WHT四层：NORHIY棍扫两道NOR
WHT五层：NORHIR棍生百相NOR]],["wxtext"]=[[HIG似担若犁NOR]]},["52"]={["id"]=52,["level"]=2,["type"]=[[gun]],["value"]=[[651;1200]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将棍法境界划分为五层，每一层则以掌握的棍法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG似担若犁NOR
WHT二层：NORHIB持棍如松NOR
WHT三层：NORHIM棍碎清泉NOR
WHT四层：NORHIY棍扫两道NOR
WHT五层：NORHIR棍生百相NOR]],["wxtext"]=[[HIB持棍如松NOR]],["wxtexts"]=[[持棍如松笑迎客]]},["53"]={["id"]=53,["level"]=3,["type"]=[[gun]],["value"]=[[1201;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将棍法境界划分为五层，每一层则以掌握的棍法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG似担若犁NOR
WHT二层：NORHIB持棍如松NOR
WHT三层：NORHIM棍碎清泉NOR
WHT四层：NORHIY棍扫两道NOR
WHT五层：NORHIR棍生百相NOR]],["wxtext"]=[[HIM棍碎清泉NOR]],["wxtexts"]=[[棍影霍霍碎清泉]],["wxtstext"]=[[其中，你的棍法刚猛无俦，无人可挡。]]},["54"]={["id"]=54,["level"]=4,["type"]=[[gun]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将棍法境界划分为五层，每一层则以掌握的棍法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG似担若犁NOR
WHT二层：NORHIB持棍如松NOR
WHT三层：NORHIM棍碎清泉NOR
WHT四层：NORHIY棍扫两道NOR
WHT五层：NORHIR棍生百相NOR]],["wxtext"]=[[HIY棍扫两道NOR]],["wxtexts"]=[[棍扫两道分黑白]],["wxtstext"]=[[其中，你的棍法刚猛无俦，无人可挡。]]},["55"]={["id"]=55,["level"]=5,["type"]=[[gun]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将棍法境界划分为五层，每一层则以掌握的棍法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG似担若犁NOR
WHT二层：NORHIB持棍如松NOR
WHT三层：NORHIM棍碎清泉NOR
WHT四层：NORHIY棍扫两道NOR
WHT五层：NORHIR棍生百相NOR]],["wxtext"]=[[HIR棍生百相NOR]],["wxtexts"]=[[无念一棍百相生]],["wxtstext"]=[[其中，你的棍法刚猛无俦，无人可挡。]]},["56"]={["id"]=56,["level"]=1,["type"]=[[fu]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将斧法境界划分为五层，每一层则以掌握的斧法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG持斧学樵NOR
WHT二层：NORHIB斧惊山鸟NOR
WHT三层：NORHIM开山碎石NOR
WHT四层：NORHIY落斧成渠NOR
WHT五层：NORHIR斧开太虚NOR]],["wxtext"]=[[HIG持斧学樵NOR]]},["57"]={["id"]=57,["level"]=2,["type"]=[[fu]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将斧法境界划分为五层，每一层则以掌握的斧法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG持斧学樵NOR
WHT二层：NORHIB斧惊山鸟NOR
WHT三层：NORHIM开山碎石NOR
WHT四层：NORHIY落斧成渠NOR
WHT五层：NORHIR斧开太虚NOR]],["wxtext"]=[[HIB斧惊山鸟NOR]],["wxtexts"]=[[挥斧成风惊山鸟]]},["58"]={["id"]=58,["level"]=3,["type"]=[[fu]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将斧法境界划分为五层，每一层则以掌握的斧法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG持斧学樵NOR
WHT二层：NORHIB斧惊山鸟NOR
WHT三层：NORHIM开山碎石NOR
WHT四层：NORHIY落斧成渠NOR
WHT五层：NORHIR斧开太虚NOR]],["wxtext"]=[[HIM开山碎石NOR]],["wxtexts"]=[[笑劈金玉断青松]],["wxtstext"]=[[其中，你的斧可力劈华山，惊天动地。]]},["59"]={["id"]=59,["level"]=4,["type"]=[[fu]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将斧法境界划分为五层，每一层则以掌握的斧法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG持斧学樵NOR
WHT二层：NORHIB斧惊山鸟NOR
WHT三层：NORHIM开山碎石NOR
WHT四层：NORHIY落斧成渠NOR
WHT五层：NORHIR斧开太虚NOR]],["wxtext"]=[[HIY落斧成渠NOR]],["wxtexts"]=[[落斧成渠劈江河]],["wxtstext"]=[[其中，你的斧可力劈华山，惊天动地。]]},["6"]={["id"]=6,["level"]=1,["type"]=[[qinggong]],["value"]=[[0;750]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将轻功境界划分为五层，每一层则以掌握的轻功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG轻身初试NOR
WHT二层：NORHIB身轻如燕NOR
WHT三层：NORHIM草上疾飞NOR
WHT四层：NORHIY踏雪无痕NOR
WHT五层：NORHIR一苇渡江NOR]],["wxtext"]=[[HIG轻身初试NOR]]},["60"]={["id"]=60,["level"]=5,["type"]=[[fu]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将斧法境界划分为五层，每一层则以掌握的斧法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG持斧学樵NOR
WHT二层：NORHIB斧惊山鸟NOR
WHT三层：NORHIM开山碎石NOR
WHT四层：NORHIY落斧成渠NOR
WHT五层：NORHIR斧开太虚NOR]],["wxtext"]=[[HIR斧开太虚NOR]],["wxtexts"]=[[纵斧横挥开太虚]],["wxtstext"]=[[其中，你的斧可力劈华山，惊天动地。]]},["61"]={["id"]=61,["level"]=1,["type"]=[[qiang]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将枪法境界划分为五层，每一层则以掌握的枪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG草耙作枪NOR
WHT二层：NORHIB人枪随行NOR
WHT三层：NORHIM枪出如龙NOR
WHT四层：NORHIY枪定玉门NOR
WHT五层：NORHIR枪点七星NOR]],["wxtext"]=[[HIG草耙作枪NOR]]},["62"]={["id"]=62,["level"]=2,["type"]=[[qiang]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将枪法境界划分为五层，每一层则以掌握的枪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG草耙作枪NOR
WHT二层：NORHIB人枪随行NOR
WHT三层：NORHIM枪出如龙NOR
WHT四层：NORHIY枪定玉门NOR
WHT五层：NORHIR枪点七星NOR]],["wxtext"]=[[HIB人枪随行NOR]],["wxtexts"]=[[人枪随行过江湖]]},["63"]={["id"]=63,["level"]=3,["type"]=[[qiang]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将枪法境界划分为五层，每一层则以掌握的枪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG草耙作枪NOR
WHT二层：NORHIB人枪随行NOR
WHT三层：NORHIM枪出如龙NOR
WHT四层：NORHIY枪定玉门NOR
WHT五层：NORHIR枪点七星NOR]],["wxtext"]=[[HIM枪出如龙NOR]],["wxtexts"]=[[龙落长坂破三军]],["wxtstext"]=[[其中，你的枪法威势惊人，横扫千军。]]},["64"]={["id"]=64,["level"]=4,["type"]=[[qiang]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将枪法境界划分为五层，每一层则以掌握的枪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG草耙作枪NOR
WHT二层：NORHIB人枪随行NOR
WHT三层：NORHIM枪出如龙NOR
WHT四层：NORHIY枪定玉门NOR
WHT五层：NORHIR枪点七星NOR]],["wxtext"]=[[HIY枪定玉门NOR]],["wxtexts"]=[[银枪白马过玉门]],["wxtstext"]=[[其中，你的枪法威势惊人，横扫千军。]]},["65"]={["id"]=65,["level"]=5,["type"]=[[qiang]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将枪法境界划分为五层，每一层则以掌握的枪法武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG草耙作枪NOR
WHT二层：NORHIB人枪随行NOR
WHT三层：NORHIM枪出如龙NOR
WHT四层：NORHIY枪定玉门NOR
WHT五层：NORHIR枪点七星NOR]],["wxtext"]=[[HIR枪点七星NOR]],["wxtexts"]=[[刺若天星破长夜]],["wxtstext"]=[[其中，你的枪法威势惊人，横扫千军。]]},["66"]={["id"]=66,["level"]=1,["type"]=[[shuangchi]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将双持武学境界划分为五层，每一层则以掌握的双持武学熟练度总和来判断。这五层分别：
WHT一层：NORHIG左违右错NOR
WHT二层：NORHIB左行右合NOR
WHT三层：NORHIM双刃纵横NOR
WHT四层：NORHIY满盈两仪NOR
WHT五层：NORHIR双悬日月NOR]],["wxtext"]=[[HIG左违右错NOR]]},["67"]={["id"]=67,["level"]=2,["type"]=[[shuangchi]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将双持武学境界划分为五层，每一层则以掌握的双持武学熟练度总和来判断。这五层分别：
WHT一层：NORHIG左违右错NOR
WHT二层：NORHIB左行右合NOR
WHT三层：NORHIM双刃纵横NOR
WHT四层：NORHIY满盈两仪NOR
WHT五层：NORHIR双悬日月NOR]],["wxtext"]=[[HIB左行右合NOR]],["wxtexts"]=[[左行右合开来路]]},["68"]={["id"]=68,["level"]=3,["type"]=[[shuangchi]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将双持武学境界划分为五层，每一层则以掌握的双持武学熟练度总和来判断。这五层分别：
WHT一层：NORHIG左违右错NOR
WHT二层：NORHIB左行右合NOR
WHT三层：NORHIM双刃纵横NOR
WHT四层：NORHIY满盈两仪NOR
WHT五层：NORHIR双悬日月NOR]],["wxtext"]=[[HIM双刃纵横NOR]],["wxtexts"]=[[天式从横地势坤]],["wxtstext"]=[[其中，你的双持武器使得左右无间，惊为天人]]},["69"]={["id"]=69,["level"]=4,["type"]=[[shuangchi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将双持武学境界划分为五层，每一层则以掌握的双持武学熟练度总和来判断。这五层分别：
WHT一层：NORHIG左违右错NOR
WHT二层：NORHIB左行右合NOR
WHT三层：NORHIM双刃纵横NOR
WHT四层：NORHIY满盈两仪NOR
WHT五层：NORHIR双悬日月NOR]],["wxtext"]=[[HIY满盈两仪NOR]],["wxtexts"]=[[刃分流错盈两仪]],["wxtstext"]=[[其中，你的双持武器使得左右无间，惊为天人]]},["7"]={["id"]=7,["level"]=2,["type"]=[[qinggong]],["value"]=[[751;1500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将轻功境界划分为五层，每一层则以掌握的轻功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG轻身初试NOR
WHT二层：NORHIB身轻如燕NOR
WHT三层：NORHIM草上疾飞NOR
WHT四层：NORHIY踏雪无痕NOR
WHT五层：NORHIR一苇渡江NOR]],["wxtext"]=[[HIB身轻如燕NOR]],["wxtexts"]=[[轻身初成踏飞燕]]},["70"]={["id"]=70,["level"]=5,["type"]=[[shuangchi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将双持武学境界划分为五层，每一层则以掌握的双持武学熟练度总和来判断。这五层分别：
WHT一层：NORHIG左违右错NOR
WHT二层：NORHIB左行右合NOR
WHT三层：NORHIM双刃纵横NOR
WHT四层：NORHIY满盈两仪NOR
WHT五层：NORHIR双悬日月NOR]],["wxtext"]=[[HIR双悬日月NOR]],["wxtexts"]=[[双悬日月照乾坤]],["wxtstext"]=[[其中，你的双持武器使得左右无间，惊为天人]]},["71"]={["id"]=71,["level"]=1,["type"]=[[anqi]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将暗器武学境界划分为五层，每一层则以掌握的暗器武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG寸尺不中NOR
WHT二层：NORHIB挥掷有声NOR
WHT三层：NORHIM镖出无影NOR
WHT四层：NORHIY飒如流星NOR
WHT五层：NORHIR针落九日NOR]],["wxtext"]=[[HIG寸尺不中NOR]]},["72"]={["id"]=72,["level"]=2,["type"]=[[anqi]],["value"]=[[501;1500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将暗器武学境界划分为五层，每一层则以掌握的暗器武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG寸尺不中NOR
WHT二层：NORHIB挥掷有声NOR
WHT三层：NORHIM镖出无影NOR
WHT四层：NORHIY飒如流星NOR
WHT五层：NORHIR针落九日NOR]],["wxtext"]=[[HIB挥掷有声NOR]],["wxtexts"]=[[挥掷有声穿风雾]]},["73"]={["id"]=73,["level"]=3,["type"]=[[anqi]],["value"]=[[1501;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将暗器武学境界划分为五层，每一层则以掌握的暗器武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG寸尺不中NOR
WHT二层：NORHIB挥掷有声NOR
WHT三层：NORHIM镖出无影NOR
WHT四层：NORHIY飒如流星NOR
WHT五层：NORHIR针落九日NOR]],["wxtext"]=[[HIM镖出无影NOR]],["wxtexts"]=[[镖出无影落鸿雁]],["wxtstext"]=[[其中，你的暗器功夫鬼神莫测，防无可防。]]},["74"]={["id"]=74,["level"]=4,["type"]=[[anqi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将暗器武学境界划分为五层，每一层则以掌握的暗器武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG寸尺不中NOR
WHT二层：NORHIB挥掷有声NOR
WHT三层：NORHIM镖出无影NOR
WHT四层：NORHIY飒如流星NOR
WHT五层：NORHIR针落九日NOR]],["wxtext"]=[[HIY飒如流星NOR]],["wxtexts"]=[[飞刃飒沓如流星]],["wxtstext"]=[[其中，你的暗器功夫鬼神莫测，防无可防。]]},["75"]={["id"]=75,["level"]=5,["type"]=[[anqi]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将暗器武学境界划分为五层，每一层则以掌握的暗器武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG寸尺不中NOR
WHT二层：NORHIB挥掷有声NOR
WHT三层：NORHIM镖出无影NOR
WHT四层：NORHIY飒如流星NOR
WHT五层：NORHIR针落九日NOR]],["wxtext"]=[[HIR针落九日NOR]],["wxtexts"]=[[针落九日庇苍生]],["wxtstext"]=[[其中，你的暗器功夫鬼神莫测，防无可防。]]},["76"]={["id"]=76,["level"]=1,["type"]=[[bian]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将鞭法境界划分为五层，每一层则以掌握的鞭法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG牵牛赶马NOR
WHT二层：NORHIB柔中带刚NOR
WHT三层：NORHIM红袖翻江NOR
WHT四层：NORHIY卷云勾月NOR
WHT五层：NORHIR流风回雪NOR]],["wxtext"]=[[HIG牵牛赶马NOR]]},["77"]={["id"]=77,["level"]=2,["type"]=[[bian]],["value"]=[[501;1200]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将鞭法境界划分为五层，每一层则以掌握的鞭法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG牵牛赶马NOR
WHT二层：NORHIB柔中带刚NOR
WHT三层：NORHIM红袖翻江NOR
WHT四层：NORHIY卷云勾月NOR
WHT五层：NORHIR流风回雪NOR]],["wxtext"]=[[HIB柔中带刚NOR]],["wxtexts"]=[[柔若春风刚似玉]]},["78"]={["id"]=78,["level"]=3,["type"]=[[bian]],["value"]=[[1201;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将鞭法境界划分为五层，每一层则以掌握的鞭法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG牵牛赶马NOR
WHT二层：NORHIB柔中带刚NOR
WHT三层：NORHIM红袖翻江NOR
WHT四层：NORHIY卷云勾月NOR
WHT五层：NORHIR流风回雪NOR]],["wxtext"]=[[HIM红袖翻江NOR]],["wxtexts"]=[[红袖翻江江浸血]],["wxtstext"]=[[其中，你的鞭法天人共鉴，令人心驰神往。]]},["79"]={["id"]=79,["level"]=4,["type"]=[[bian]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将鞭法境界划分为五层，每一层则以掌握的鞭法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG牵牛赶马NOR
WHT二层：NORHIB柔中带刚NOR
WHT三层：NORHIM红袖翻江NOR
WHT四层：NORHIY卷云勾月NOR
WHT五层：NORHIR流风回雪NOR]],["wxtext"]=[[HIY卷云勾月NOR]],["wxtexts"]=[[旋卷流云曳残月]],["wxtstext"]=[[其中，你的鞭法天人共鉴，令人心驰神往。]]},["8"]={["id"]=8,["level"]=3,["type"]=[[qinggong]],["value"]=[[1501;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将轻功境界划分为五层，每一层则以掌握的轻功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG轻身初试NOR
WHT二层：NORHIB身轻如燕NOR
WHT三层：NORHIM草上疾飞NOR
WHT四层：NORHIY踏雪无痕NOR
WHT五层：NORHIR一苇渡江NOR]],["wxtext"]=[[HIM草上疾飞NOR]],["wxtexts"]=[[草上疾飞影无踪]],["wxtstext"]=[[其中，你的轻功已然进退随心，飘忽若神。]]},["80"]={["id"]=80,["level"]=5,["type"]=[[bian]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将鞭法境界划分为五层，每一层则以掌握的鞭法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG牵牛赶马NOR
WHT二层：NORHIB柔中带刚NOR
WHT三层：NORHIM红袖翻江NOR
WHT四层：NORHIY卷云勾月NOR
WHT五层：NORHIR流风回雪NOR]],["wxtext"]=[[HIR流风回雪NOR]],["wxtexts"]=[[缥缈流风回细雪]],["wxtstext"]=[[其中，你的鞭法天人共鉴，令人心驰神往。]]},["81"]={["id"]=81,["level"]=1,["type"]=[[qin]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将乐法境界划分为五层，每一层则以掌握的乐法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG音韵动心NOR
WHT二层：NORHIB余音绕梁NOR
WHT三层：NORHIM高山流水NOR
WHT四层：NORHIY悠扬天籁NOR
WHT五层：NORHIR声动千秋NOR]],["wxtext"]=[[HIG音韵动心NOR]]},["82"]={["id"]=82,["level"]=2,["type"]=[[qin]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将乐法境界划分为五层，每一层则以掌握的乐法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG音韵动心NOR
WHT二层：NORHIB余音绕梁NOR
WHT三层：NORHIM高山流水NOR
WHT四层：NORHIY悠扬天籁NOR
WHT五层：NORHIR声动千秋NOR]],["wxtext"]=[[HIB余音绕梁NOR]],["wxtexts"]=[[余音袅袅久绕梁]]},["83"]={["id"]=83,["level"]=3,["type"]=[[qin]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将乐法境界划分为五层，每一层则以掌握的乐法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG音韵动心NOR
WHT二层：NORHIB余音绕梁NOR
WHT三层：NORHIM高山流水NOR
WHT四层：NORHIY悠扬天籁NOR
WHT五层：NORHIR声动千秋NOR]],["wxtext"]=[[HIM高山流水NOR]],["wxtexts"]=[[高山远响流水潺]],["wxtstext"]=[[其中，你的乐法鬼神莫测，杀人于无影无形。]]},["84"]={["id"]=84,["level"]=4,["type"]=[[qin]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将乐法境界划分为五层，每一层则以掌握的乐法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG音韵动心NOR
WHT二层：NORHIB余音绕梁NOR
WHT三层：NORHIM高山流水NOR
WHT四层：NORHIY悠扬天籁NOR
WHT五层：NORHIR声动千秋NOR]],["wxtext"]=[[HIY悠扬天籁NOR]],["wxtexts"]=[[天籁之音曲悠扬]],["wxtstext"]=[[其中，你的乐法鬼神莫测，杀人于无影无形。]]},["85"]={["id"]=85,["level"]=5,["type"]=[[qin]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将乐法境界划分为五层，每一层则以掌握的乐法熟练度总和来判断。这五层分别是：
WHT一层：NORHIG音韵动心NOR
WHT二层：NORHIB余音绕梁NOR
WHT三层：NORHIM高山流水NOR
WHT四层：NORHIY悠扬天籁NOR
WHT五层：NORHIR声动千秋NOR]],["wxtext"]=[[HIR声动千秋NOR]],["wxtexts"]=[[信手一曲动千秋]],["wxtstext"]=[[其中，你的乐法鬼神莫测，杀人于无影无形。]]},["86"]={["id"]=86,["level"]=1,["type"]=[[zhaojia]],["value"]=[[0;500]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将招架境界划分为五层，每一层则以掌握的招架武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG只手卸刃NOR
WHT二层：NORHIB观境闻声NOR
WHT三层：NORHIM辨气识招NOR
WHT四层：NORHIY千刃莫及NOR
WHT五层：NORHIR御不染尘NOR]],["wxtext"]=[[HIG只手卸刃NOR]]},["87"]={["id"]=87,["level"]=2,["type"]=[[zhaojia]],["value"]=[[501;1000]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将招架境界划分为五层，每一层则以掌握的招架武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG只手卸刃NOR
WHT二层：NORHIB观境闻声NOR
WHT三层：NORHIM辨气识招NOR
WHT四层：NORHIY千刃莫及NOR
WHT五层：NORHIR御不染尘NOR]],["wxtext"]=[[HIB观境闻声NOR]],["wxtexts"]=[[眼环六路耳八方]]},["88"]={["id"]=88,["level"]=3,["type"]=[[zhaojia]],["value"]=[[1001;999999]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将招架境界划分为五层，每一层则以掌握的招架武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG只手卸刃NOR
WHT二层：NORHIB观境闻声NOR
WHT三层：NORHIM辨气识招NOR
WHT四层：NORHIY千刃莫及NOR
WHT五层：NORHIR御不染尘NOR]],["wxtext"]=[[HIM辨气识招NOR]],["wxtexts"]=[[气动惊起御白芒]],["wxtstext"]=[[其中，你的招架之法无比周全，堪称无懈可击。]]},["89"]={["id"]=89,["level"]=4,["type"]=[[zhaojia]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将招架境界划分为五层，每一层则以掌握的招架武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG只手卸刃NOR
WHT二层：NORHIB观境闻声NOR
WHT三层：NORHIM辨气识招NOR
WHT四层：NORHIY千刃莫及NOR
WHT五层：NORHIR御不染尘NOR]],["wxtext"]=[[HIY千刃莫及NOR]],["wxtexts"]=[[千刃袭身衣未破]],["wxtstext"]=[[其中，你的招架之法无比周全，堪称无懈可击。]]},["9"]={["id"]=9,["level"]=4,["type"]=[[qinggong]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将轻功境界划分为五层，每一层则以掌握的轻功武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG轻身初试NOR
WHT二层：NORHIB身轻如燕NOR
WHT三层：NORHIM草上疾飞NOR
WHT四层：NORHIY踏雪无痕NOR
WHT五层：NORHIR一苇渡江NOR]],["wxtext"]=[[HIY踏雪无痕NOR]],["wxtexts"]=[[脚踏初雪了无痕]],["wxtstext"]=[[其中，你的轻功已然进退随心，飘忽若神。]]},["90"]={["id"]=90,["level"]=5,["type"]=[[zhaojia]],["wxjftext"]=[[WHT江湖中人依据百晓生《武学图鉴总谱》所载，将招架境界划分为五层，每一层则以掌握的招架武学熟练度总和来判断。这五层分别是：
WHT一层：NORHIG只手卸刃NOR
WHT二层：NORHIB观境闻声NOR
WHT三层：NORHIM辨气识招NOR
WHT四层：NORHIY千刃莫及NOR
WHT五层：NORHIR御不染尘NOR]],["wxtext"]=[[HIR御不染尘NOR]],["wxtexts"]=[[只身守御不染尘]],["wxtstext"]=[[其中，你的招架之法无比周全，堪称无懈可击。]]}}}00000000