--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_Back
local Panel_Back = ccui.Layout:create()
Panel_Back:ignoreContentAdaptWithSize(false)
Panel_Back:setClippingEnabled(false)
Panel_Back:setBackGroundColorType(1)
Panel_Back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_Back:setBackGroundColorOpacity(204)
Panel_Back:setTouchEnabled(true);
Panel_Back:setLayoutComponentEnabled(true)
Panel_Back:setName("Panel_Back")
Panel_Back:setTag(246)
Panel_Back:setCascadeColorEnabled(true)
Panel_Back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_Back)

--Create Text_Title
local Text_Title = ccui.Text:create()
Text_Title:ignoreContentAdaptWithSize(true)
Text_Title:setTextAreaSize({width = 0, height = 0})
Text_Title:setFontName("Font/HYCFS.ttf")
Text_Title:setFontSize(100)
Text_Title:setString([[通关]])
Text_Title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_Title:setLayoutComponentEnabled(true)
Text_Title:setName("Text_Title")
Text_Title:setTag(14)
Text_Title:setCascadeColorEnabled(true)
Text_Title:setCascadeOpacityEnabled(true)
Text_Title:setPosition(520.8929, 1549.8860)
Text_Title:setTextColor({r = 214, g = 233, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Title)
layout:setPositionPercentX(0.4823)
layout:setPositionPercentY(0.8072)
layout:setPercentWidth(0.1907)
layout:setPercentHeight(0.0729)
layout:setSize({width = 206.0000, height = 140.0000})
layout:setLeftMargin(417.8929)
layout:setRightMargin(456.1071)
layout:setTopMargin(300.1138)
layout:setBottomMargin(1479.8860)
Layer:addChild(Text_Title)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(true)
Text_desc:setTextAreaSize({width = 0, height = 0})
Text_desc:setFontName("Font/HYCFS.ttf")
Text_desc:setFontSize(57)
Text_desc:setString([[第一章 金牛武馆]])
Text_desc:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(51)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(534.8000, 1409.1980)
Text_desc:setTextColor({r = 144, g = 138, b = 71})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.4952)
layout:setPositionPercentY(0.7340)
layout:setPercentWidth(0.4009)
layout:setPercentHeight(0.0349)
layout:setSize({width = 433.0000, height = 67.0000})
layout:setLeftMargin(318.3000)
layout:setRightMargin(328.7000)
layout:setTopMargin(477.3016)
layout:setBottomMargin(1375.6980)
Layer:addChild(Text_desc)

--Create Text_context
local Text_context = ccui.Text:create()
Text_context:ignoreContentAdaptWithSize(true)
Text_context:setTextAreaSize({width = 0, height = 0})
Text_context:setFontName("Font/default.ttf")
Text_context:setFontSize(50)
Text_context:setString([[路径金牛武馆，解救妇女与路旁。]])
Text_context:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_context:setLayoutComponentEnabled(true)
Text_context:setName("Text_context")
Text_context:setTag(52)
Text_context:setCascadeColorEnabled(true)
Text_context:setCascadeOpacityEnabled(true)
Text_context:setPosition(540.0014, 1257.3640)
Text_context:setTextColor({r = 207, g = 207, b = 207})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_context)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6549)
layout:setPercentWidth(0.6731)
layout:setPercentHeight(0.0344)
layout:setSize({width = 727.0000, height = 66.0000})
layout:setLeftMargin(176.5014)
layout:setRightMargin(176.4986)
layout:setTopMargin(629.6365)
layout:setBottomMargin(1224.3640)
Layer:addChild(Text_context)

--Create Button_left
local Button_left = ccui.Button:create()
Button_left:ignoreContentAdaptWithSize(false)
Button_left:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_left:setTitleFontName("Font/default.ttf")
Button_left:setTitleFontSize(48)
Button_left:setScale9Enabled(true)
Button_left:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_left:setLayoutComponentEnabled(true)
Button_left:setName("Button_left")
Button_left:setTag(212)
Button_left:setCascadeColorEnabled(true)
Button_left:setCascadeOpacityEnabled(true)
Button_left:setPosition(307.0000, 953.0634)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_left)
layout:setPositionPercentX(0.2843)
layout:setPositionPercentY(0.4964)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(145.0000)
layout:setRightMargin(611.0000)
layout:setTopMargin(907.9366)
layout:setBottomMargin(894.0634)
Layer:addChild(Button_left)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[停留]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(213)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(112.0000)
layout:setRightMargin(112.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_left:addChild(Text_buttonName)

--Create Button_right
local Button_right = ccui.Button:create()
Button_right:ignoreContentAdaptWithSize(false)
Button_right:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_right:setTitleFontName("Font/default.ttf")
Button_right:setTitleFontSize(48)
Button_right:setScale9Enabled(true)
Button_right:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_right:setLayoutComponentEnabled(true)
Button_right:setName("Button_right")
Button_right:setTag(214)
Button_right:setCascadeColorEnabled(true)
Button_right:setCascadeOpacityEnabled(true)
Button_right:setPosition(773.0000, 953.5539)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_right)
layout:setPositionPercentX(0.7157)
layout:setPositionPercentY(0.4966)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setHorizontalEdge(2)
layout:setLeftMargin(611.0000)
layout:setRightMargin(145.0000)
layout:setTopMargin(907.4461)
layout:setBottomMargin(894.5539)
Layer:addChild(Button_right)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[离开]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(215)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_right:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0