--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(244)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(297)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setTouchEnabled(true);
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(294)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0000, 1175.0000)
Image_back:setOpacity(229)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6120)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(116.0000)
layout:setBottomMargin(546.0000)
Layer:addChild(Image_back)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(48)
Text_desc:setString([[你的继承人各方面的能力已经是同辈中的佼佼者了，你确定要将衣钵传给你的继承人吗？
传承说明
传承后角色等级，潜能等属性及武功等级均变为初始状态，传承后将额外获得X点先天属性并可自行分配。
角色的颜值，福缘，金钱，江湖阅历保留。
超出的经验值将转化为潜能点返还给传承后的角色。]])
Text_desc:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(298)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(540.0000, 1248.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6500)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.5500)
layout:setSize({width = 972.0000, height = 1056.0000})
layout:setLeftMargin(54.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(144.0000)
layout:setBottomMargin(720.0000)
Layer:addChild(Text_desc)

--Create Text_desc1
local Text_desc1 = ccui.Text:create()
Text_desc1:ignoreContentAdaptWithSize(false)
Text_desc1:setFontName("Font/default.ttf")
Text_desc1:setFontSize(60)
Text_desc1:setString([[传承后你的角色属性将初始化，请慎重考虑。如果确定要传承请输入“确定”。然后点击传承按钮。]])
Text_desc1:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc1:setLayoutComponentEnabled(true)
Text_desc1:setName("Text_desc1")
Text_desc1:setTag(510)
Text_desc1:setCascadeColorEnabled(true)
Text_desc1:setCascadeOpacityEnabled(true)
Text_desc1:setVisible(false)
Text_desc1:setPosition(540.0000, 1500.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7813)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.1563)
layout:setSize({width = 972.0000, height = 300.0000})
layout:setLeftMargin(54.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(270.0000)
layout:setBottomMargin(1350.0000)
Layer:addChild(Text_desc1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontName("Font/default.ttf")
Text_1:setFontSize(60)
Text_1:setString([[请输入:]])
Text_1:setTextVerticalAlignment(1)
Text_1:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(511)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setVisible(false)
Text_1:setPosition(230.1685, 1253.3640)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.2131)
layout:setPositionPercentY(0.6528)
layout:setPercentWidth(0.1852)
layout:setPercentHeight(0.0625)
layout:setSize({width = 200.0000, height = 120.0000})
layout:setLeftMargin(130.1685)
layout:setRightMargin(749.8315)
layout:setTopMargin(606.6365)
layout:setBottomMargin(1193.3640)
Layer:addChild(Text_1)

--Create EditBox
local EditBox = ccui.ImageView:create()
EditBox:ignoreContentAdaptWithSize(false)
EditBox:loadTexture("Image/UI/PopUI/kuang.png",0)
EditBox:setLayoutComponentEnabled(true)
EditBox:setName("EditBox")
EditBox:setTag(509)
EditBox:setCascadeColorEnabled(true)
EditBox:setCascadeOpacityEnabled(true)
EditBox:setVisible(false)
EditBox:setPosition(659.6640, 1253.3640)
layout = ccui.LayoutComponent:bindLayoutComponent(EditBox)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.6108)
layout:setPositionPercentY(0.6528)
layout:setPercentWidth(0.4815)
layout:setPercentHeight(0.0625)
layout:setSize({width = 520.0000, height = 120.0000})
layout:setLeftMargin(399.6640)
layout:setRightMargin(160.3360)
layout:setTopMargin(606.6365)
layout:setBottomMargin(1193.3640)
Layer:addChild(EditBox)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_1:setTitleFontName("Font/default.ttf")
Button_1:setTitleFontSize(48)
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(299)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(540.0000, 400.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2083)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1461.0000)
layout:setBottomMargin(341.0000)
Layer:addChild(Button_1)

--Create Text_button_1_Name
local Text_button_1_Name = ccui.Text:create()
Text_button_1_Name:ignoreContentAdaptWithSize(true)
Text_button_1_Name:setTextAreaSize({width = 0, height = 0})
Text_button_1_Name:setFontName("Font/default.ttf")
Text_button_1_Name:setFontSize(48)
Text_button_1_Name:setString([[传承]])
Text_button_1_Name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_button_1_Name:setLayoutComponentEnabled(true)
Text_button_1_Name:setName("Text_button_1_Name")
Text_button_1_Name:setTag(300)
Text_button_1_Name:setCascadeColorEnabled(true)
Text_button_1_Name:setCascadeOpacityEnabled(true)
Text_button_1_Name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_button_1_Name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3210)
layout:setPercentHeight(0.5424)
layout:setSize({width = 104.0000, height = 64.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(110.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_1:addChild(Text_button_1_Name)

--Create Button_2
local Button_2 = ccui.Button:create()
Button_2:ignoreContentAdaptWithSize(false)
Button_2:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_2:setTitleFontName("Font/default.ttf")
Button_2:setTitleFontSize(48)
Button_2:setScale9Enabled(true)
Button_2:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_2:setLayoutComponentEnabled(true)
Button_2:setName("Button_2")
Button_2:setTag(301)
Button_2:setCascadeColorEnabled(true)
Button_2:setCascadeOpacityEnabled(true)
Button_2:setPosition(540.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1042)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1661.0000)
layout:setBottomMargin(141.0000)
Layer:addChild(Button_2)

--Create Text_button_1_Name
local Text_button_1_Name = ccui.Text:create()
Text_button_1_Name:ignoreContentAdaptWithSize(true)
Text_button_1_Name:setTextAreaSize({width = 0, height = 0})
Text_button_1_Name:setFontName("Font/default.ttf")
Text_button_1_Name:setFontSize(48)
Text_button_1_Name:setString([[容我三思]])
Text_button_1_Name:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_button_1_Name:setLayoutComponentEnabled(true)
Text_button_1_Name:setName("Text_button_1_Name")
Text_button_1_Name:setTag(302)
Text_button_1_Name:setCascadeColorEnabled(true)
Text_button_1_Name:setCascadeOpacityEnabled(true)
Text_button_1_Name:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_button_1_Name)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6142)
layout:setPercentHeight(0.5424)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(62.5000)
layout:setRightMargin(62.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_2:addChild(Text_button_1_Name)

--Create bg
local bg = ccui.Layout:create()
bg:ignoreContentAdaptWithSize(false)
bg:setClippingEnabled(false)
bg:setBackGroundColorType(1)
bg:setBackGroundColor({r = 0, g = 0, b = 0})
bg:setBackGroundColorOpacity(244)
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(63)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(false)
bg:setAnchorPoint(0.5000, 0.5000)
bg:setPosition(550.0440, 950.0160)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5093)
layout:setPositionPercentY(0.4948)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
layout:setLeftMargin(10.0440)
layout:setRightMargin(-10.0439)
layout:setTopMargin(9.9840)
layout:setBottomMargin(-9.9840)
Layer:addChild(bg)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00