--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setBackGroundImage("Image/UI/PopUI/shade.png",0)
Panel_back:setClippingEnabled(false)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(16)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/MeridianUI/gubenkuang.png",0)
Image_back:setTouchEnabled(true);
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(15)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setAnchorPoint(0.5000, 1.0000)
Image_back:setPosition(540.0000, 1450.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7555)
layout:setPercentWidth(0.7611)
layout:setPercentHeight(0.5109)
layout:setSize({width = 822.0000, height = 981.0000})
layout:setLeftMargin(129.0000)
layout:setRightMargin(129.0000)
layout:setTopMargin(469.5000)
layout:setBottomMargin(469.5000)
Layer:addChild(Image_back)

--Create Text_desc1
local Text_desc1 = ccui.Text:create()
Text_desc1:ignoreContentAdaptWithSize(false)
Text_desc1:setFontName("Font/default.ttf")
Text_desc1:setFontSize(48)
Text_desc1:setString([[香薰炉用于点燃特制的檀香，用于辅助调息。
香薰炉现在是冷的，没有点燃。]])
Text_desc1:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc1:setLayoutComponentEnabled(true)
Text_desc1:setName("Text_desc1")
Text_desc1:setTag(18)
Text_desc1:setCascadeColorEnabled(true)
Text_desc1:setCascadeOpacityEnabled(true)
Text_desc1:setAnchorPoint(0.0000, 1.0000)
Text_desc1:setPosition(82.2000, 830.0000)
Text_desc1:setTextColor({r = 114, g = 114, b = 95})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.1000)
layout:setPositionPercentY(0.8461)
layout:setPercentWidth(0.8000)
layout:setPercentHeight(0.2548)
layout:setSize({width = 657.6000, height = 250.0000})
layout:setLeftMargin(82.2000)
layout:setRightMargin(82.2000)
layout:setTopMargin(151.0000)
layout:setBottomMargin(580.0000)
Image_back:addChild(Text_desc1)

--Create Text_desc2
local Text_desc2 = ccui.Text:create()
Text_desc2:ignoreContentAdaptWithSize(true)
Text_desc2:setTextAreaSize({width = 0, height = 0})
Text_desc2:setFontName("Font/default.ttf")
Text_desc2:setFontSize(48)
Text_desc2:setString([[距离香薰炉熄灭还有：]])
Text_desc2:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc2:setLayoutComponentEnabled(true)
Text_desc2:setName("Text_desc2")
Text_desc2:setTag(19)
Text_desc2:setCascadeColorEnabled(true)
Text_desc2:setCascadeOpacityEnabled(true)
Text_desc2:setAnchorPoint(0.0000, 1.0000)
Text_desc2:setPosition(82.2000, 600.0000)
Text_desc2:setTextColor({r = 114, g = 114, b = 95})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.1000)
layout:setPositionPercentY(0.6116)
layout:setPercentWidth(0.5535)
layout:setPercentHeight(0.0652)
layout:setSize({width = 455.0000, height = 64.0000})
layout:setLeftMargin(82.2000)
layout:setRightMargin(284.8000)
layout:setTopMargin(381.0000)
layout:setBottomMargin(536.0000)
Image_back:addChild(Text_desc2)

--Create Text_desc3
local Text_desc3 = ccui.Text:create()
Text_desc3:ignoreContentAdaptWithSize(true)
Text_desc3:setTextAreaSize({width = 0, height = 0})
Text_desc3:setFontName("Font/default.ttf")
Text_desc3:setFontSize(48)
Text_desc3:setString([[XX小时XX分XX秒]])
Text_desc3:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_desc3:setLayoutComponentEnabled(true)
Text_desc3:setName("Text_desc3")
Text_desc3:setTag(20)
Text_desc3:setCascadeColorEnabled(true)
Text_desc3:setCascadeOpacityEnabled(true)
Text_desc3:setAnchorPoint(0.0000, 1.0000)
Text_desc3:setPosition(82.2000, 540.0000)
Text_desc3:setTextColor({r = 175, g = 145, b = 25})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.1000)
layout:setPositionPercentY(0.5505)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(0.4696)
layout:setPercentHeight(0.0652)
layout:setSize({width = 386.0000, height = 64.0000})
layout:setLeftMargin(82.2000)
layout:setRightMargin(353.8000)
layout:setTopMargin(441.0000)
layout:setBottomMargin(476.0000)
Image_back:addChild(Text_desc3)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/default.ttf")
Text_name:setFontSize(60)
Text_name:setString([[【香薰炉】]])
Text_name:setTextVerticalAlignment(1)
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(17)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(0.0000, 0.5000)
Text_name:setPosition(168.0000, 1370.0000)
Text_name:setTextColor({r = 204, g = 51, b = 204})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.1556)
layout:setPositionPercentY(0.7135)
layout:setPercentWidth(0.2491)
layout:setPercentHeight(0.0401)
layout:setSize({width = 269.0000, height = 77.0000})
layout:setLeftMargin(168.0000)
layout:setRightMargin(643.0000)
layout:setTopMargin(511.5000)
layout:setBottomMargin(1331.5000)
Layer:addChild(Text_name)

--Create Button1
local Button1 = ccui.Button:create()
Button1:ignoreContentAdaptWithSize(false)
Button1:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button1:setTitleFontSize(14)
Button1:setTitleColor({r = 65, g = 65, b = 70})
Button1:setScale9Enabled(true)
Button1:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button1:setLayoutComponentEnabled(true)
Button1:setName("Button1")
Button1:setTag(23)
Button1:setCascadeColorEnabled(true)
Button1:setCascadeOpacityEnabled(true)
Button1:setPosition(540.0000, 800.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4167)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1061.0000)
layout:setBottomMargin(741.0000)
Layer:addChild(Button1)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[添香]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(24)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3179)
layout:setPercentHeight(0.5424)
layout:setSize({width = 103.0000, height = 64.0000})
layout:setLeftMargin(110.5000)
layout:setRightMargin(110.5000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button1:addChild(Text_buttonName)

--Create Button2
local Button2 = ccui.Button:create()
Button2:ignoreContentAdaptWithSize(false)
Button2:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button2:setTitleFontSize(14)
Button2:setTitleColor({r = 65, g = 65, b = 70})
Button2:setScale9Enabled(true)
Button2:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button2:setLayoutComponentEnabled(true)
Button2:setName("Button2")
Button2:setTag(21)
Button2:setCascadeColorEnabled(true)
Button2:setCascadeOpacityEnabled(true)
Button2:setPosition(540.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3385)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(1211.0000)
layout:setBottomMargin(591.0000)
Layer:addChild(Button2)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[关闭]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(22)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(112.0000)
layout:setRightMargin(112.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button2:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0