--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(1021)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(1020)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(542.5085, 1177.5080)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5023)
layout:setPositionPercentY(0.6133)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(18.5085)
layout:setRightMargin(13.4915)
layout:setTopMargin(113.4918)
layout:setBottomMargin(548.5082)
Layer:addChild(Image_back)

--Create Text_Lv
local Text_Lv = ccui.Text:create()
Text_Lv:ignoreContentAdaptWithSize(false)
Text_Lv:setFontName("Font/default.ttf")
Text_Lv:setFontSize(42)
Text_Lv:setString([[易容术等级：
]])
Text_Lv:setTextHorizontalAlignment(1)
Text_Lv:setLayoutComponentEnabled(true)
Text_Lv:setName("Text_Lv")
Text_Lv:setTag(1026)
Text_Lv:setCascadeColorEnabled(true)
Text_Lv:setCascadeOpacityEnabled(true)
Text_Lv:setPosition(540.0000, 1606.0000)
Text_Lv:setScaleY(1.0395)
Text_Lv:setTextColor({r = 159, g = 159, b = 159})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Lv)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8365)
layout:setPercentWidth(0.7407)
layout:setPercentHeight(0.0313)
layout:setSize({width = 800.0000, height = 60.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(140.0000)
layout:setRightMargin(140.0000)
layout:setTopMargin(284.0000)
layout:setBottomMargin(1576.0000)
Layer:addChild(Text_Lv)

--Create Text_Keeptime
local Text_Keeptime = ccui.Text:create()
Text_Keeptime:ignoreContentAdaptWithSize(false)
Text_Keeptime:setFontName("Font/default.ttf")
Text_Keeptime:setFontSize(42)
Text_Keeptime:setString([[维持时间：
]])
Text_Keeptime:setTextHorizontalAlignment(1)
Text_Keeptime:setLayoutComponentEnabled(true)
Text_Keeptime:setName("Text_Keeptime")
Text_Keeptime:setTag(1025)
Text_Keeptime:setCascadeColorEnabled(true)
Text_Keeptime:setCascadeOpacityEnabled(true)
Text_Keeptime:setPosition(540.0000, 1547.0000)
Text_Keeptime:setScaleY(1.0395)
Text_Keeptime:setTextColor({r = 159, g = 159, b = 159})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Keeptime)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8057)
layout:setPercentWidth(0.7407)
layout:setPercentHeight(0.0313)
layout:setSize({width = 800.0000, height = 60.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(140.0000)
layout:setRightMargin(140.0000)
layout:setTopMargin(343.0000)
layout:setBottomMargin(1517.0000)
Layer:addChild(Text_Keeptime)

--Create Text_cdtime
local Text_cdtime = ccui.Text:create()
Text_cdtime:ignoreContentAdaptWithSize(false)
Text_cdtime:setFontName("Font/default.ttf")
Text_cdtime:setFontSize(42)
Text_cdtime:setString([[冷却时间：
]])
Text_cdtime:setTextHorizontalAlignment(1)
Text_cdtime:setLayoutComponentEnabled(true)
Text_cdtime:setName("Text_cdtime")
Text_cdtime:setTag(1024)
Text_cdtime:setCascadeColorEnabled(true)
Text_cdtime:setCascadeOpacityEnabled(true)
Text_cdtime:setPosition(540.0000, 1488.0000)
Text_cdtime:setScaleY(1.0395)
Text_cdtime:setTextColor({r = 159, g = 159, b = 159})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_cdtime)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7750)
layout:setPercentWidth(0.7407)
layout:setPercentHeight(0.0313)
layout:setSize({width = 800.0000, height = 60.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(140.0000)
layout:setRightMargin(140.0000)
layout:setTopMargin(402.0000)
layout:setBottomMargin(1458.0000)
Layer:addChild(Text_cdtime)

--Create Text_desc
local Text_desc = ccui.Text:create()
Text_desc:ignoreContentAdaptWithSize(false)
Text_desc:setFontName("Font/default.ttf")
Text_desc:setFontSize(42)
Text_desc:setString([[持续剩余时间:
]])
Text_desc:setTextHorizontalAlignment(1)
Text_desc:setLayoutComponentEnabled(true)
Text_desc:setName("Text_desc")
Text_desc:setTag(1019)
Text_desc:setCascadeColorEnabled(true)
Text_desc:setCascadeOpacityEnabled(true)
Text_desc:setPosition(560.5631, 1284.9320)
Text_desc:setScaleY(1.0395)
Text_desc:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_desc)
layout:setPositionPercentX(0.5190)
layout:setPositionPercentY(0.6692)
layout:setPercentWidth(0.7963)
layout:setPercentHeight(0.0313)
layout:setSize({width = 860.0000, height = 60.0000})
layout:setLeftMargin(130.5631)
layout:setRightMargin(89.4369)
layout:setTopMargin(605.0679)
layout:setBottomMargin(1254.9320)
Layer:addChild(Text_desc)

--Create Text_Tital
local Text_Tital = ccui.Text:create()
Text_Tital:ignoreContentAdaptWithSize(false)
Text_Tital:setFontName("Font/HYCFS.ttf")
Text_Tital:setFontSize(60)
Text_Tital:setString([[易容改貌]])
Text_Tital:setTextHorizontalAlignment(1)
Text_Tital:setTextVerticalAlignment(1)
Text_Tital:setLayoutComponentEnabled(true)
Text_Tital:setName("Text_Tital")
Text_Tital:setTag(1018)
Text_Tital:setCascadeColorEnabled(true)
Text_Tital:setCascadeOpacityEnabled(true)
Text_Tital:setPosition(540.0016, 1719.0000)
Text_Tital:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Tital)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8953)
layout:setPercentWidth(0.2778)
layout:setPercentHeight(0.0781)
layout:setSize({width = 300.0000, height = 150.0000})
layout:setLeftMargin(390.0016)
layout:setRightMargin(389.9984)
layout:setTopMargin(126.0000)
layout:setBottomMargin(1644.0000)
Layer:addChild(Text_Tital)

--Create Button_Yes
local Button_Yes = ccui.Button:create()
Button_Yes:ignoreContentAdaptWithSize(false)
Button_Yes:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_Yes:setTitleFontSize(14)
Button_Yes:setTitleColor({r = 65, g = 65, b = 70})
Button_Yes:setScale9Enabled(true)
Button_Yes:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_Yes:setLayoutComponentEnabled(true)
Button_Yes:setName("Button_Yes")
Button_Yes:setTag(1014)
Button_Yes:setCascadeColorEnabled(true)
Button_Yes:setCascadeOpacityEnabled(true)
Button_Yes:setPosition(756.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Yes)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.3385)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(624.0000)
layout:setRightMargin(192.0000)
layout:setTopMargin(1221.0000)
layout:setBottomMargin(601.0000)
Layer:addChild(Button_Yes)

--Create Text_buttonYesName
local Text_buttonYesName = ccui.Text:create()
Text_buttonYesName:ignoreContentAdaptWithSize(true)
Text_buttonYesName:setTextAreaSize({width = 0, height = 0})
Text_buttonYesName:setFontName("Font/default.ttf")
Text_buttonYesName:setFontSize(48)
Text_buttonYesName:setString([[停止易容]])
Text_buttonYesName:setTextHorizontalAlignment(1)
Text_buttonYesName:setTextVerticalAlignment(1)
Text_buttonYesName:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_buttonYesName:setLayoutComponentEnabled(true)
Text_buttonYesName:setName("Text_buttonYesName")
Text_buttonYesName:setTag(1015)
Text_buttonYesName:setCascadeColorEnabled(true)
Text_buttonYesName:setCascadeOpacityEnabled(true)
Text_buttonYesName:setPosition(132.0000, 49.0000)
Text_buttonYesName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonYesName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7538)
layout:setPercentHeight(0.6531)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(32.5000)
layout:setRightMargin(32.5000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
Button_Yes:addChild(Text_buttonYesName)

--Create Button_NO
local Button_NO = ccui.Button:create()
Button_NO:ignoreContentAdaptWithSize(false)
Button_NO:loadTextureNormal("Image/UI/MapUI/anniu05.png",0)
Button_NO:setTitleFontSize(14)
Button_NO:setTitleColor({r = 65, g = 65, b = 70})
Button_NO:setScale9Enabled(true)
Button_NO:setCapInsets({x = 15, y = 11, width = 234, height = 76})
Button_NO:setLayoutComponentEnabled(true)
Button_NO:setName("Button_NO")
Button_NO:setTag(1016)
Button_NO:setCascadeColorEnabled(true)
Button_NO:setCascadeOpacityEnabled(true)
Button_NO:setPosition(324.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_NO)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.3385)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setVerticalEdge(2)
layout:setLeftMargin(192.0000)
layout:setRightMargin(624.0000)
layout:setTopMargin(1221.0000)
layout:setBottomMargin(601.0000)
Layer:addChild(Button_NO)

--Create Text_buttonNoName
local Text_buttonNoName = ccui.Text:create()
Text_buttonNoName:ignoreContentAdaptWithSize(true)
Text_buttonNoName:setTextAreaSize({width = 0, height = 0})
Text_buttonNoName:setFontName("Font/default.ttf")
Text_buttonNoName:setFontSize(48)
Text_buttonNoName:setString([[取消]])
Text_buttonNoName:setTextHorizontalAlignment(1)
Text_buttonNoName:setTextVerticalAlignment(1)
Text_buttonNoName:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_buttonNoName:setLayoutComponentEnabled(true)
Text_buttonNoName:setName("Text_buttonNoName")
Text_buttonNoName:setTag(1017)
Text_buttonNoName:setCascadeColorEnabled(true)
Text_buttonNoName:setCascadeOpacityEnabled(true)
Text_buttonNoName:setPosition(132.0000, 49.0000)
Text_buttonNoName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonNoName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3864)
layout:setPercentHeight(0.6531)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(81.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
Button_NO:addChild(Text_buttonNoName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000