--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Sprite_background
local Sprite_background = cc.Sprite:create("Image/UI/MainUI/backgurand.jpg")
Sprite_background:setName("Sprite_background")
Sprite_background:setTag(104)
Sprite_background:setCascadeColorEnabled(true)
Sprite_background:setCascadeOpacityEnabled(true)
Sprite_background:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_background)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Sprite_background:setBlendFunc({src = 770, dst = 771})
Layer:addChild(Sprite_background)

--Create Sprite_bottom
local Sprite_bottom = cc.Sprite:create("Image/UI/MainUI/changjing01.png")
Sprite_bottom:setName("Sprite_bottom")
Sprite_bottom:setTag(105)
Sprite_bottom:setCascadeColorEnabled(true)
Sprite_bottom:setCascadeOpacityEnabled(true)
Sprite_bottom:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_bottom)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3224)
layout:setSize({width = 1080.0000, height = 619.0000})
layout:setTopMargin(1301.0000)
Sprite_bottom:setBlendFunc({src = 770, dst = 771})
Layer:addChild(Sprite_bottom)

--Create Panel_webview
local Panel_webview = ccui.Layout:create()
Panel_webview:ignoreContentAdaptWithSize(false)
Panel_webview:setClippingEnabled(true)
Panel_webview:setBackGroundColorType(1)
Panel_webview:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_webview:setBackGroundColorOpacity(0)
Panel_webview:setTouchEnabled(true);
Panel_webview:setLayoutComponentEnabled(true)
Panel_webview:setName("Panel_webview")
Panel_webview:setTag(106)
Panel_webview:setCascadeColorEnabled(true)
Panel_webview:setCascadeOpacityEnabled(true)
Panel_webview:setAnchorPoint(0.5000, 0.5000)
Panel_webview:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_webview)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_webview)

--Create Text_center
local Text_center = ccui.Text:create()
Text_center:ignoreContentAdaptWithSize(true)
Text_center:setTextAreaSize({width = 0, height = 0})
Text_center:setFontName("Font/default.ttf")
Text_center:setFontSize(64)
Text_center:setString([[帮助中心]])
Text_center:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_center:setLayoutComponentEnabled(true)
Text_center:setName("Text_center")
Text_center:setTag(107)
Text_center:setCascadeColorEnabled(true)
Text_center:setCascadeOpacityEnabled(true)
Text_center:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_center)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2435)
layout:setPercentHeight(0.0427)
layout:setSize({width = 263.0000, height = 82.0000})
layout:setLeftMargin(408.5000)
layout:setRightMargin(408.5000)
layout:setTopMargin(919.0000)
layout:setBottomMargin(919.0000)
Panel_webview:addChild(Text_center)

--Create Image_titleBack
local Image_titleBack = ccui.ImageView:create()
Image_titleBack:ignoreContentAdaptWithSize(false)
Image_titleBack:loadTexture("Image/UI/MainUI/kuangup.png",0)
Image_titleBack:setScale9Enabled(true)
Image_titleBack:setCapInsets({x = 356, y = 35, width = 368, height = 38})
Image_titleBack:setLayoutComponentEnabled(true)
Image_titleBack:setName("Image_titleBack")
Image_titleBack:setTag(108)
Image_titleBack:setCascadeColorEnabled(true)
Image_titleBack:setCascadeOpacityEnabled(true)
Image_titleBack:setAnchorPoint(0.5000, 1.0000)
Image_titleBack:setPosition(540.0000, 1920.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_titleBack)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0562)
layout:setSize({width = 1080.0000, height = 108.0000})
layout:setBottomMargin(1812.0000)
Layer:addChild(Image_titleBack)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/HYCFS.ttf")
Text_title:setFontSize(60)
Text_title:setString([[小树林]])
Text_title:setTextHorizontalAlignment(1)
Text_title:setTextVerticalAlignment(1)
Text_title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(109)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(540.0000, 52.6907)
Text_title:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4879)
layout:setPercentWidth(0.1713)
layout:setPercentHeight(0.6481)
layout:setSize({width = 185.0000, height = 70.0000})
layout:setLeftMargin(447.5000)
layout:setRightMargin(447.5000)
layout:setTopMargin(20.3093)
layout:setBottomMargin(17.6907)
Image_titleBack:addChild(Text_title)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontName("Font/HYCFS.ttf")
Text_name:setFontSize(48)
Text_name:setString([[   返回   ]])
Text_name:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(111)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setVisible(false)
Text_name:setPosition(100.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.0926)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.2000)
layout:setPercentHeight(0.5370)
layout:setSize({width = 216.0000, height = 58.0000})
layout:setLeftMargin(-8.0000)
layout:setRightMargin(872.0000)
layout:setTopMargin(29.0000)
layout:setBottomMargin(21.0000)
Image_titleBack:addChild(Text_name)

--Create Button_back
local Button_back = ccui.Button:create()
Button_back:ignoreContentAdaptWithSize(false)
Button_back:loadTextureNormal("Image/UI/MenuUI/back.png",0)
Button_back:loadTexturePressed("Image/UI/MenuUI/back2.png",0)
Button_back:setTitleFontSize(48)
Button_back:setTitleColor({r = 208, g = 208, b = 208})
Button_back:setLayoutComponentEnabled(true)
Button_back:setName("Button_back")
Button_back:setTag(110)
Button_back:setCascadeColorEnabled(true)
Button_back:setCascadeOpacityEnabled(true)
Button_back:setPosition(100.0000, 54.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_back)
layout:setPositionPercentX(0.0926)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1759)
layout:setPercentHeight(0.8333)
layout:setSize({width = 190.0000, height = 90.0000})
layout:setLeftMargin(5.0000)
layout:setRightMargin(885.0000)
layout:setTopMargin(9.0000)
layout:setBottomMargin(9.0000)
Image_titleBack:addChild(Button_back)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000