--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Btn_Task_Item
local Btn_Task_Item = ccui.Button:create()
Btn_Task_Item:ignoreContentAdaptWithSize(false)
Btn_Task_Item:loadTextureNormal("Image/UI/SkinUI/Skin_2/listBtnBg.png",0)
Btn_Task_Item:setTitleFontSize(14)
Btn_Task_Item:setTitleColor({r = 65, g = 65, b = 70})
Btn_Task_Item:setScale9Enabled(true)
Btn_Task_Item:setCapInsets({x = 77, y = 50, width = 812, height = 115})
Btn_Task_Item:setLayoutComponentEnabled(true)
Btn_Task_Item:setName("Btn_Task_Item")
Btn_Task_Item:setTag(136)
Btn_Task_Item:setCascadeColorEnabled(true)
Btn_Task_Item:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Task_Item)
layout:setSize({width = 966.0000, height = 215.0000})
layout:setLeftMargin(-483.0000)
layout:setRightMargin(-483.0000)
layout:setTopMargin(-107.5000)
layout:setBottomMargin(-107.5000)
Node:addChild(Btn_Task_Item)

--Create Img_PrgBg
local Img_PrgBg = ccui.ImageView:create()
Img_PrgBg:ignoreContentAdaptWithSize(false)
Img_PrgBg:loadTexture("Image/UI/SkinUI/Skin_2/loadingBarBg.png",0)
Img_PrgBg:setLayoutComponentEnabled(true)
Img_PrgBg:setName("Img_PrgBg")
Img_PrgBg:setTag(137)
Img_PrgBg:setCascadeColorEnabled(true)
Img_PrgBg:setCascadeOpacityEnabled(true)
Img_PrgBg:setPosition(291.6201, 103.6730)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_PrgBg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3019)
layout:setPositionPercentY(0.4822)
layout:setPercentWidth(0.5528)
layout:setPercentHeight(0.3581)
layout:setSize({width = 534.0000, height = 77.0000})
layout:setLeftMargin(24.6201)
layout:setRightMargin(407.3799)
layout:setTopMargin(72.8270)
layout:setBottomMargin(65.1730)
Btn_Task_Item:addChild(Img_PrgBg)

--Create Prg_CD
local Prg_CD = ccui.LoadingBar:create()
Prg_CD:loadTexture("Image/UI/TaskUI/prg-brushBlack.png",0)
Prg_CD:ignoreContentAdaptWithSize(false)
Prg_CD:setLayoutComponentEnabled(true)
Prg_CD:setName("Prg_CD")
Prg_CD:setTag(138)
Prg_CD:setCascadeColorEnabled(true)
Prg_CD:setCascadeOpacityEnabled(true)
Prg_CD:setPosition(291.6200, 103.6730)
layout = ccui.LayoutComponent:bindLayoutComponent(Prg_CD)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3019)
layout:setPositionPercentY(0.4822)
layout:setPercentWidth(0.5549)
layout:setPercentHeight(0.3581)
layout:setSize({width = 536.0000, height = 77.0000})
layout:setLeftMargin(23.6200)
layout:setRightMargin(406.3800)
layout:setTopMargin(72.8270)
layout:setBottomMargin(65.1730)
Btn_Task_Item:addChild(Prg_CD)

--Create Pnl_Disable
local Pnl_Disable = ccui.Layout:create()
Pnl_Disable:ignoreContentAdaptWithSize(false)
Pnl_Disable:setClippingEnabled(false)
Pnl_Disable:setBackGroundColorType(1)
Pnl_Disable:setBackGroundColor({r = 26, g = 26, b = 26})
Pnl_Disable:setBackGroundColorOpacity(204)
Pnl_Disable:setTouchEnabled(true);
Pnl_Disable:setLayoutComponentEnabled(true)
Pnl_Disable:setName("Pnl_Disable")
Pnl_Disable:setTag(139)
Pnl_Disable:setCascadeColorEnabled(true)
Pnl_Disable:setCascadeOpacityEnabled(true)
Pnl_Disable:setAnchorPoint(0.5000, 0.5000)
Pnl_Disable:setPosition(483.0000, 107.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pnl_Disable)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9757)
layout:setPercentHeight(0.9107)
layout:setSize({width = 942.5313, height = 195.7966})
layout:setLeftMargin(11.7343)
layout:setRightMargin(11.7344)
layout:setTopMargin(9.6017)
layout:setBottomMargin(9.6017)
Btn_Task_Item:addChild(Pnl_Disable)

--Create Txt_Disable1
local Txt_Disable1 = ccui.Text:create()
Txt_Disable1:ignoreContentAdaptWithSize(true)
Txt_Disable1:setTextAreaSize({width = 0, height = 0})
Txt_Disable1:setFontName("Font/HYCFS.ttf")
Txt_Disable1:setFontSize(36)
Txt_Disable1:setString([[需通关章节XXXXXXXXX]])
Txt_Disable1:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Txt_Disable1:setLayoutComponentEnabled(true)
Txt_Disable1:setName("Txt_Disable1")
Txt_Disable1:setTag(140)
Txt_Disable1:setCascadeColorEnabled(true)
Txt_Disable1:setCascadeOpacityEnabled(true)
Txt_Disable1:setAnchorPoint(0.0000, 0.5000)
Txt_Disable1:setPosition(61.5473, 97.8983)
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_Disable1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0653)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4573)
layout:setPercentHeight(0.2503)
layout:setSize({width = 431.0000, height = 49.0000})
layout:setLeftMargin(61.5473)
layout:setRightMargin(449.9840)
layout:setTopMargin(73.3983)
layout:setBottomMargin(73.3983)
Pnl_Disable:addChild(Txt_Disable1)

--Create Txt_Disable2
local Txt_Disable2 = ccui.Text:create()
Txt_Disable2:ignoreContentAdaptWithSize(true)
Txt_Disable2:setTextAreaSize({width = 0, height = 0})
Txt_Disable2:setFontName("Font/HYCFS.ttf")
Txt_Disable2:setFontSize(36)
Txt_Disable2:setString([[经验 > 111111]])
Txt_Disable2:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Txt_Disable2:setLayoutComponentEnabled(true)
Txt_Disable2:setName("Txt_Disable2")
Txt_Disable2:setTag(141)
Txt_Disable2:setCascadeColorEnabled(true)
Txt_Disable2:setCascadeOpacityEnabled(true)
Txt_Disable2:setAnchorPoint(0.0000, 0.5000)
Txt_Disable2:setPosition(560.0000, 87.2700)
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_Disable2)
layout:setPositionPercentX(0.5941)
layout:setPositionPercentY(0.4457)
layout:setPercentWidth(0.2366)
layout:setPercentHeight(0.2503)
layout:setSize({width = 223.0000, height = 49.0000})
layout:setLeftMargin(560.0000)
layout:setRightMargin(159.5313)
layout:setTopMargin(84.0266)
layout:setBottomMargin(62.7700)
Pnl_Disable:addChild(Txt_Disable2)

--Create Pnl_Enable
local Pnl_Enable = ccui.Layout:create()
Pnl_Enable:ignoreContentAdaptWithSize(false)
Pnl_Enable:setClippingEnabled(false)
Pnl_Enable:setBackGroundColorOpacity(102)
Pnl_Enable:setLayoutComponentEnabled(true)
Pnl_Enable:setName("Pnl_Enable")
Pnl_Enable:setTag(142)
Pnl_Enable:setCascadeColorEnabled(true)
Pnl_Enable:setCascadeOpacityEnabled(true)
Pnl_Enable:setAnchorPoint(0.5000, 0.5000)
Pnl_Enable:setPosition(483.0000, 107.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pnl_Enable)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9793)
layout:setPercentHeight(0.8279)
layout:setSize({width = 946.0000, height = 178.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(18.5000)
layout:setBottomMargin(18.5000)
Btn_Task_Item:addChild(Pnl_Enable)

--Create Btn_Start
local Btn_Start = ccui.Button:create()
Btn_Start:ignoreContentAdaptWithSize(false)
Btn_Start:loadTextureNormal("Image/UI/SkinUI/Skin_2/listBtn.png",0)
Btn_Start:setTitleFontSize(14)
Btn_Start:setTitleColor({r = 65, g = 65, b = 70})
Btn_Start:setScale9Enabled(true)
Btn_Start:setCapInsets({x = 15, y = 11, width = 10, height = 18})
Btn_Start:setLayoutComponentEnabled(true)
Btn_Start:setName("Btn_Start")
Btn_Start:setTag(143)
Btn_Start:setCascadeColorEnabled(true)
Btn_Start:setCascadeOpacityEnabled(true)
Btn_Start:setPosition(752.1400, 86.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Start)
layout:setPositionPercentX(0.7951)
layout:setPositionPercentY(0.4831)
layout:setPercentWidth(0.3023)
layout:setPercentHeight(0.4888)
layout:setSize({width = 286.0000, height = 87.0000})
layout:setLeftMargin(609.1400)
layout:setRightMargin(50.8600)
layout:setTopMargin(48.5000)
layout:setBottomMargin(42.5000)
Pnl_Enable:addChild(Btn_Start)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(36)
Text_buttonName:setString([[进行中]])
Text_buttonName:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(144)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(143.0000, 43.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3951)
layout:setPercentHeight(0.5747)
layout:setSize({width = 113.0000, height = 50.0000})
layout:setLeftMargin(86.5000)
layout:setRightMargin(86.5000)
layout:setTopMargin(18.5000)
layout:setBottomMargin(18.5000)
Btn_Start:addChild(Text_buttonName)

--Create Txt_Status
local Txt_Status = ccui.Text:create()
Txt_Status:ignoreContentAdaptWithSize(false)
Txt_Status:setFontName("Font/default.ttf")
Txt_Status:setFontSize(36)
Txt_Status:setString([[任务冷却中
999小时]])
Txt_Status:setTextHorizontalAlignment(1)
Txt_Status:setTextVerticalAlignment(1)
Txt_Status:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Txt_Status:setLayoutComponentEnabled(true)
Txt_Status:setName("Txt_Status")
Txt_Status:setTag(145)
Txt_Status:setCascadeColorEnabled(true)
Txt_Status:setCascadeOpacityEnabled(true)
Txt_Status:setPosition(755.6110, 90.1570)
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_Status)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7987)
layout:setPositionPercentY(0.5065)
layout:setPercentWidth(0.3171)
layout:setPercentHeight(0.9098)
layout:setSize({width = 300.0000, height = 161.9493})
layout:setLeftMargin(605.6110)
layout:setRightMargin(40.3890)
layout:setTopMargin(6.8683)
layout:setBottomMargin(9.1824)
Pnl_Enable:addChild(Txt_Status)

--Create Txt_TaskName
local Txt_TaskName = ccui.Text:create()
Txt_TaskName:ignoreContentAdaptWithSize(true)
Txt_TaskName:setTextAreaSize({width = 0, height = 0})
Txt_TaskName:setFontName("Font/HYCFS.ttf")
Txt_TaskName:setFontSize(48)
Txt_TaskName:setString([[任务名称最多九个字]])
Txt_TaskName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Txt_TaskName:setLayoutComponentEnabled(true)
Txt_TaskName:setName("Txt_TaskName")
Txt_TaskName:setTag(146)
Txt_TaskName:setCascadeColorEnabled(true)
Txt_TaskName:setCascadeOpacityEnabled(true)
Txt_TaskName:setPosition(279.7500, 85.8316)
Txt_TaskName:setTextColor({r = 2, g = 214, b = 2})
layout = ccui.LayoutComponent:bindLayoutComponent(Txt_TaskName)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2957)
layout:setPositionPercentY(0.4822)
layout:setPercentWidth(0.4609)
layout:setPercentHeight(0.3483)
layout:setSize({width = 436.0000, height = 62.0000})
layout:setLeftMargin(61.7500)
layout:setRightMargin(448.2500)
layout:setTopMargin(61.1684)
layout:setBottomMargin(54.8316)
Pnl_Enable:addChild(Txt_TaskName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

00