--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(84)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(60)
Text_title:setString([[任务说明]])
Text_title:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(82)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(554.2765, 1866.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5132)
layout:setPositionPercentY(0.9721)
layout:setPercentWidth(0.2241)
layout:setPercentHeight(0.0401)
layout:setSize({width = 242.0000, height = 77.0000})
layout:setLeftMargin(433.2765)
layout:setRightMargin(404.7235)
layout:setTopMargin(15.0000)
layout:setBottomMargin(1828.0000)
Layer:addChild(Text_title)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(81)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(539.9998, 1103.2010)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5746)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(15.9998)
layout:setRightMargin(16.0002)
layout:setTopMargin(187.7993)
layout:setBottomMargin(474.2007)
Layer:addChild(Image_1)

--Create Panel_print
local Panel_print = ccui.Layout:create()
Panel_print:ignoreContentAdaptWithSize(false)
Panel_print:setClippingEnabled(false)
Panel_print:setBackGroundColorOpacity(102)
Panel_print:setTouchEnabled(true);
Panel_print:setLayoutComponentEnabled(true)
Panel_print:setName("Panel_print")
Panel_print:setTag(45)
Panel_print:setCascadeColorEnabled(true)
Panel_print:setCascadeOpacityEnabled(true)
Panel_print:setAnchorPoint(0.5000, 0.5000)
Panel_print:setPosition(539.9996, 1120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_print)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5833)
layout:setPercentWidth(0.8796)
layout:setPercentHeight(0.5208)
layout:setSize({width = 950.0000, height = 1000.0000})
layout:setLeftMargin(64.9996)
layout:setRightMargin(65.0004)
layout:setTopMargin(300.0000)
layout:setBottomMargin(620.0000)
Layer:addChild(Panel_print)

--Create Button_Accept
local Button_Accept = ccui.Button:create()
Button_Accept:ignoreContentAdaptWithSize(false)
Button_Accept:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_Accept:loadTexturePressed("Image/UI/TaskUI/anniu.png",0)
Button_Accept:setTitleFontSize(14)
Button_Accept:setTitleColor({r = 65, g = 65, b = 70})
Button_Accept:setScale9Enabled(true)
Button_Accept:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_Accept:setLayoutComponentEnabled(true)
Button_Accept:setName("Button_Accept")
Button_Accept:setTag(70)
Button_Accept:setCascadeColorEnabled(true)
Button_Accept:setCascadeOpacityEnabled(true)
Button_Accept:setPosition(523.0048, 379.2839)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Accept)
layout:setPositionPercentX(0.4843)
layout:setPositionPercentY(0.1975)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(361.0048)
layout:setRightMargin(394.9952)
layout:setTopMargin(1481.7160)
layout:setBottomMargin(320.2839)
Layer:addChild(Button_Accept)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[接受]])
Text_buttonName:setTextHorizontalAlignment(1)
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(71)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_Accept:addChild(Text_buttonName)

--Create Button_cancel
local Button_cancel = ccui.Button:create()
Button_cancel:ignoreContentAdaptWithSize(false)
Button_cancel:loadTextureNormal("Image/UI/TaskUI/anniu.png",0)
Button_cancel:loadTexturePressed("Image/UI/TaskUI/anniu.png",0)
Button_cancel:setTitleFontSize(14)
Button_cancel:setTitleColor({r = 65, g = 65, b = 70})
Button_cancel:setScale9Enabled(true)
Button_cancel:setCapInsets({x = 15, y = 4, width = 294, height = 110})
Button_cancel:setLayoutComponentEnabled(true)
Button_cancel:setName("Button_cancel")
Button_cancel:setTag(72)
Button_cancel:setCascadeColorEnabled(true)
Button_cancel:setCascadeOpacityEnabled(true)
Button_cancel:setPosition(525.6156, 188.6974)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_cancel)
layout:setPositionPercentX(0.4867)
layout:setPositionPercentY(0.0983)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(363.6156)
layout:setRightMargin(392.3844)
layout:setTopMargin(1672.3030)
layout:setBottomMargin(129.6974)
Layer:addChild(Button_cancel)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[离开]])
Text_buttonName:setTextHorizontalAlignment(1)
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(73)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3148)
layout:setPercentHeight(0.5424)
layout:setSize({width = 102.0000, height = 64.0000})
layout:setLeftMargin(111.0000)
layout:setRightMargin(111.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_cancel:addChild(Text_buttonName)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000000