--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Image_TitleBack
local Image_TitleBack = ccui.ImageView:create()
Image_TitleBack:ignoreContentAdaptWithSize(false)
Image_TitleBack:loadTexture("Default/ImageFile.png",0)
Image_TitleBack:setLayoutComponentEnabled(true)
Image_TitleBack:setName("Image_TitleBack")
Image_TitleBack:setTag(183)
Image_TitleBack:setCascadeColorEnabled(true)
Image_TitleBack:setCascadeOpacityEnabled(true)
Image_TitleBack:setAnchorPoint(0.0000, 1.0000)
Image_TitleBack:setPosition(0.0000, 1920.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_TitleBack)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(0.0426)
layout:setPercentHeight(0.0240)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setRightMargin(1034.0000)
layout:setBottomMargin(1874.0000)
Layer:addChild(Image_TitleBack)

--Create Image_MapBack
local Image_MapBack = ccui.ImageView:create()
Image_MapBack:ignoreContentAdaptWithSize(false)
Image_MapBack:loadTexture("Image/UI/MapUI/beijing.png",0)
Image_MapBack:setLayoutComponentEnabled(true)
Image_MapBack:setName("Image_MapBack")
Image_MapBack:setTag(317)
Image_MapBack:setCascadeColorEnabled(true)
Image_MapBack:setCascadeOpacityEnabled(true)
Image_MapBack:setAnchorPoint(0.0000, 0.0000)
Image_MapBack:setPosition(0.0000, -0.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_MapBack)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.8773)
layout:setSize({width = 1080.0000, height = 1684.4980})
layout:setTopMargin(235.5020)
layout:setBottomMargin(-0.0002)
Layer:addChild(Image_MapBack)

--Create Text_Title
local Text_Title = ccui.Text:create()
Text_Title:ignoreContentAdaptWithSize(true)
Text_Title:setTextAreaSize({width = 0, height = 0})
Text_Title:setFontName("Font/HYCFS.ttf")
Text_Title:setFontSize(72)
Text_Title:setString([[高山远水]])
Text_Title:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_Title:setLayoutComponentEnabled(true)
Text_Title:setName("Text_Title")
Text_Title:setTag(185)
Text_Title:setCascadeColorEnabled(true)
Text_Title:setCascadeOpacityEnabled(true)
Text_Title:setPosition(539.9999, 1801.3810)
Text_Title:setTextColor({r = 197, g = 197, b = 197})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9382)
layout:setPercentWidth(0.2731)
layout:setPercentHeight(0.0490)
layout:setSize({width = 300.0000, height = 104.0000})
layout:setLeftMargin(392.4999)
layout:setRightMargin(392.5001)
layout:setTopMargin(71.6187)
layout:setBottomMargin(1754.3810)
Layer:addChild(Text_Title)

--Create ScrollView_map
local ScrollView_map = ccui.ScrollView:create()
ScrollView_map:setDirection(3)
ScrollView_map:setInnerContainerSize({width = 1080, height = 1249})
ScrollView_map:ignoreContentAdaptWithSize(false)
ScrollView_map:setClippingEnabled(true)
ScrollView_map:setBackGroundColorOpacity(102)
ScrollView_map:setLayoutComponentEnabled(true)
ScrollView_map:setName("ScrollView_map")
ScrollView_map:setTag(321)
ScrollView_map:setCascadeColorEnabled(true)
ScrollView_map:setCascadeOpacityEnabled(true)
ScrollView_map:setAnchorPoint(0.0000, 0.5000)
ScrollView_map:setPosition(27.9999, 1052.9790)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_map)
layout:setPositionPercentX(0.0259)
layout:setPositionPercentY(0.5484)
layout:setPercentWidth(0.9481)
layout:setPercentHeight(0.6505)
layout:setSize({width = 1024.0000, height = 1249.0000})
layout:setLeftMargin(27.9999)
layout:setRightMargin(28.0001)
layout:setTopMargin(242.5210)
layout:setBottomMargin(428.4790)
Layer:addChild(ScrollView_map)

--Create Button_OK
local Button_OK = ccui.Button:create()
Button_OK:ignoreContentAdaptWithSize(false)
Button_OK:loadTextureNormal("Image/UI/PopUI/anniu.png",0)
Button_OK:setTitleFontSize(14)
Button_OK:setTitleText("Button")
Button_OK:setTitleColor({r = 65, g = 65, b = 70})
Button_OK:setScale9Enabled(true)
Button_OK:setCapInsets({x = 15, y = 11, width = 294, height = 96})
Button_OK:setLayoutComponentEnabled(true)
Button_OK:setName("Button_OK")
Button_OK:setTag(303)
Button_OK:setCascadeColorEnabled(true)
Button_OK:setCascadeOpacityEnabled(true)
Button_OK:setPosition(832.7444, 263.0431)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_OK)
layout:setPositionPercentX(0.7711)
layout:setPositionPercentY(0.1370)
layout:setPercentWidth(0.3000)
layout:setPercentHeight(0.0615)
layout:setSize({width = 324.0000, height = 118.0000})
layout:setLeftMargin(670.7444)
layout:setRightMargin(85.2556)
layout:setTopMargin(1597.9570)
layout:setBottomMargin(204.0431)
Layer:addChild(Button_OK)

--Create Text_34
local Text_34 = ccui.Text:create()
Text_34:ignoreContentAdaptWithSize(true)
Text_34:setTextAreaSize({width = 0, height = 0})
Text_34:setFontName("Font/default.ttf")
Text_34:setFontSize(48)
Text_34:setString([[关闭]])
Text_34:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_34:setLayoutComponentEnabled(true)
Text_34:setName("Text_34")
Text_34:setTag(304)
Text_34:setCascadeColorEnabled(true)
Text_34:setCascadeOpacityEnabled(true)
Text_34:setPosition(162.0000, 59.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_34)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3086)
layout:setPercentHeight(0.5424)
layout:setSize({width = 100.0000, height = 64.0000})
layout:setLeftMargin(112.0000)
layout:setRightMargin(112.0000)
layout:setTopMargin(27.0000)
layout:setBottomMargin(27.0000)
Button_OK:addChild(Text_34)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000