--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setBackGroundColorOpacity(229)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(116)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("Font/default.ttf")
Text_title:setFontSize(60)
Text_title:setString([[个人信息框]])
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(140)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setPosition(539.9995, 1782.6770)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9285)
layout:setPercentWidth(0.2787)
layout:setPercentHeight(0.0349)
layout:setSize({width = 301.0000, height = 67.0000})
layout:setLeftMargin(389.4995)
layout:setRightMargin(389.5005)
layout:setTopMargin(103.8230)
layout:setBottomMargin(1749.1770)
Layer:addChild(Text_title)

--Create Image_back
local Image_back = ccui.ImageView:create()
Image_back:ignoreContentAdaptWithSize(false)
Image_back:loadTexture("Image/UI/RoleUI/RoeBack.png",0)
Image_back:setLayoutComponentEnabled(true)
Image_back:setName("Image_back")
Image_back:setTag(115)
Image_back:setCascadeColorEnabled(true)
Image_back:setCascadeOpacityEnabled(true)
Image_back:setPosition(540.0001, 1062.0100)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5531)
layout:setPercentWidth(0.9704)
layout:setPercentHeight(0.6552)
layout:setSize({width = 1048.0000, height = 1258.0000})
layout:setLeftMargin(16.0001)
layout:setRightMargin(16.0000)
layout:setTopMargin(228.9897)
layout:setBottomMargin(433.0103)
Layer:addChild(Image_back)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000