--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorOpacity(102)
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(122)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 1.0000)
Panel_back:setPosition(540.0000, 1750.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9115)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9438)
layout:setSize({width = 1080.0000, height = 1812.0000})
layout:setTopMargin(170.0000)
layout:setBottomMargin(-62.0000)
Layer:addChild(Panel_back)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setItemsMargin(5)
ListView_1:setDirection(1)
ListView_1:setGravity(1)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setBackGroundImage("Image/UI/AttrUI/cangku.png",0)
ListView_1:setClippingEnabled(true)
ListView_1:setBackGroundImageCapInsets({x = 151, y = 267, width = 158, height = 276})
ListView_1:setBackGroundColorOpacity(102)
ListView_1:setBackGroundImageScale9Enabled(true)
ListView_1:setTouchEnabled(false);
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(123)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setAnchorPoint(0.5000, 0.5000)
ListView_1:setPosition(329.9974, 928.9948)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.3056)
layout:setPositionPercentY(0.4839)
layout:setPercentWidth(0.4259)
layout:setPercentHeight(0.3250)
layout:setSize({width = 460.0000, height = 624.0000})
layout:setLeftMargin(99.9974)
layout:setRightMargin(520.0026)
layout:setTopMargin(679.0052)
layout:setBottomMargin(616.9948)
Layer:addChild(ListView_1)

--Create Text_time
local Text_time = ccui.Text:create()
Text_time:ignoreContentAdaptWithSize(true)
Text_time:setTextAreaSize({width = 0, height = 0})
Text_time:setFontName("Font/default.ttf")
Text_time:setFontSize(48)
Text_time:setString([[【剩余时间】60s]])
Text_time:setTextHorizontalAlignment(1)
Text_time:setTextVerticalAlignment(1)
Text_time:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_time:setLayoutComponentEnabled(true)
Text_time:setName("Text_time")
Text_time:setTag(183)
Text_time:setCascadeColorEnabled(true)
Text_time:setCascadeOpacityEnabled(true)
Text_time:setVisible(false)
Text_time:setAnchorPoint(0.0000, 0.5000)
Text_time:setPosition(537.9899, 1336.9950)
Text_time:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_time)
layout:setPositionPercentX(0.4981)
layout:setPositionPercentY(0.6964)
layout:setPercentWidth(0.3491)
layout:setPercentHeight(0.0333)
layout:setSize({width = 377.0000, height = 64.0000})
layout:setLeftMargin(537.9899)
layout:setRightMargin(165.0101)
layout:setTopMargin(551.0054)
layout:setBottomMargin(1304.9950)
Layer:addChild(Text_time)

--Create Text_state
local Text_state = ccui.Text:create()
Text_state:ignoreContentAdaptWithSize(true)
Text_state:setTextAreaSize({width = 0, height = 0})
Text_state:setFontName("Font/default.ttf")
Text_state:setFontSize(48)
Text_state:setString([[【煅烧程度】良好]])
Text_state:setTextHorizontalAlignment(1)
Text_state:setTextVerticalAlignment(1)
Text_state:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_state:setLayoutComponentEnabled(true)
Text_state:setName("Text_state")
Text_state:setTag(184)
Text_state:setCascadeColorEnabled(true)
Text_state:setCascadeOpacityEnabled(true)
Text_state:setVisible(false)
Text_state:setAnchorPoint(0.0000, 0.5000)
Text_state:setPosition(28.0000, 1336.9950)
Text_state:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_state)
layout:setPositionPercentX(0.0259)
layout:setPositionPercentY(0.6964)
layout:setPercentWidth(0.3620)
layout:setPercentHeight(0.0333)
layout:setSize({width = 391.0000, height = 64.0000})
layout:setLeftMargin(28.0000)
layout:setRightMargin(661.0000)
layout:setTopMargin(551.0054)
layout:setBottomMargin(1304.9950)
Layer:addChild(Text_state)

--Create Button_ranliao
local Button_ranliao = ccui.Button:create()
Button_ranliao:ignoreContentAdaptWithSize(false)
Button_ranliao:loadTextureNormal("Image/UI/TeacherUI/anniu01.png",0)
Button_ranliao:loadTexturePressed("Image/UI/TeacherUI/anniu01.png",0)
Button_ranliao:loadTextureDisabled("Image/UI/TaskUI/anniu.png",0)
Button_ranliao:setTitleFontSize(14)
Button_ranliao:setTitleColor({r = 65, g = 65, b = 70})
Button_ranliao:setScale9Enabled(true)
Button_ranliao:setCapInsets({x = 15, y = 4, width = 234, height = 90})
Button_ranliao:setLayoutComponentEnabled(true)
Button_ranliao:setName("Button_ranliao")
Button_ranliao:setTag(201)
Button_ranliao:setCascadeColorEnabled(true)
Button_ranliao:setCascadeOpacityEnabled(true)
Button_ranliao:setAnchorPoint(0.5000, 1.0000)
Button_ranliao:setPosition(811.9965, 1062.9950)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_ranliao)
layout:setPositionPercentX(0.7518)
layout:setPositionPercentY(0.5536)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(679.9965)
layout:setRightMargin(136.0035)
layout:setTopMargin(857.0049)
layout:setBottomMargin(964.9951)
Layer:addChild(Button_ranliao)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[添加燃料]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(202)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(132.0000, 49.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7538)
layout:setPercentHeight(0.6531)
layout:setSize({width = 199.0000, height = 64.0000})
layout:setLeftMargin(32.5000)
layout:setRightMargin(32.5000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
Button_ranliao:addChild(Text_buttonName)

--Create Button_neili
local Button_neili = ccui.Button:create()
Button_neili:ignoreContentAdaptWithSize(false)
Button_neili:loadTextureNormal("Image/UI/TeacherUI/anniu01.png",0)
Button_neili:loadTexturePressed("Image/UI/TaskUI/anniu.png",0)
Button_neili:loadTextureDisabled("Image/UI/TaskUI/anniu.png",0)
Button_neili:setTitleFontSize(14)
Button_neili:setTitleColor({r = 65, g = 65, b = 70})
Button_neili:setScale9Enabled(true)
Button_neili:setCapInsets({x = 15, y = 4, width = 234, height = 90})
Button_neili:setLayoutComponentEnabled(true)
Button_neili:setName("Button_neili")
Button_neili:setTag(203)
Button_neili:setCascadeColorEnabled(true)
Button_neili:setCascadeOpacityEnabled(true)
Button_neili:setAnchorPoint(0.5000, 1.0000)
Button_neili:setPosition(811.9965, 932.9949)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_neili)
layout:setPositionPercentX(0.7518)
layout:setPositionPercentY(0.4859)
layout:setPercentWidth(0.2444)
layout:setPercentHeight(0.0510)
layout:setSize({width = 264.0000, height = 98.0000})
layout:setLeftMargin(679.9965)
layout:setRightMargin(136.0035)
layout:setTopMargin(987.0051)
layout:setBottomMargin(834.9949)
Layer:addChild(Button_neili)

--Create Text_buttonName
local Text_buttonName = ccui.Text:create()
Text_buttonName:ignoreContentAdaptWithSize(true)
Text_buttonName:setTextAreaSize({width = 0, height = 0})
Text_buttonName:setFontName("Font/default.ttf")
Text_buttonName:setFontSize(48)
Text_buttonName:setString([[注入内力]])
Text_buttonName:enableOutline({r = 0, g = 0, b = 0, a = 255}, 5)
Text_buttonName:setLayoutComponentEnabled(true)
Text_buttonName:setName("Text_buttonName")
Text_buttonName:setTag(204)
Text_buttonName:setCascadeColorEnabled(true)
Text_buttonName:setCascadeOpacityEnabled(true)
Text_buttonName:setPosition(132.0000, 49.0000)
Text_buttonName:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_buttonName)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7348)
layout:setPercentHeight(0.6531)
layout:setSize({width = 194.0000, height = 64.0000})
layout:setLeftMargin(35.0000)
layout:setRightMargin(35.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
Button_neili:addChild(Text_buttonName)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 127, g = 127, b = 127})
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(130)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(330.0001, 927.9984)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.3056)
layout:setPositionPercentY(0.4833)
layout:setPercentWidth(0.4259)
layout:setPercentHeight(0.3250)
layout:setSize({width = 460.0000, height = 624.0000})
layout:setLeftMargin(100.0001)
layout:setRightMargin(519.9999)
layout:setTopMargin(680.0016)
layout:setBottomMargin(615.9984)
Layer:addChild(Panel_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:ignoreContentAdaptWithSize(true)
Text_2:setTextAreaSize({width = 0, height = 0})
Text_2:setFontName("Font/default.ttf")
Text_2:setFontSize(56)
Text_2:setString([[熔炼中]])
Text_2:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setTag(131)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
Text_2:setPosition(230.0000, 312.0000)
Text_2:setTextColor({r = 219, g = 57, b = 57})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3717)
layout:setPercentHeight(0.1170)
layout:setSize({width = 171.0000, height = 73.0000})
layout:setLeftMargin(144.5000)
layout:setRightMargin(144.5000)
layout:setTopMargin(275.5000)
layout:setBottomMargin(275.5000)
Panel_1:addChild(Text_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

000000000