--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Panel_back
local Panel_back = ccui.Layout:create()
Panel_back:ignoreContentAdaptWithSize(false)
Panel_back:setClippingEnabled(false)
Panel_back:setBackGroundColorType(1)
Panel_back:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_back:setTouchEnabled(true);
Panel_back:setLayoutComponentEnabled(true)
Panel_back:setName("Panel_back")
Panel_back:setTag(5)
Panel_back:setCascadeColorEnabled(true)
Panel_back:setCascadeOpacityEnabled(true)
Panel_back:setAnchorPoint(0.5000, 0.5000)
Panel_back:setPosition(540.0000, 960.0000)
Panel_back:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_back)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_back)

--Create Text
local Text = ccui.Text:create()
Text:ignoreContentAdaptWithSize(false)
Text:setFontName("Font/default.ttf")
Text:setFontSize(48)
Text:setString([[]])
Text:setTextHorizontalAlignment(1)
Text:setTextVerticalAlignment(1)
Text:enableOutline({r = 26, g = 26, b = 26, a = 255}, 5)
Text:setLayoutComponentEnabled(true)
Text:setName("Text")
Text:setTag(159)
Text:setCascadeColorEnabled(true)
Text:setCascadeOpacityEnabled(true)
Text:setPosition(540.0000, 2304.0000)
Text:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.2000)
layout:setPercentWidth(3.4722)
layout:setPercentHeight(0.1042)
layout:setSize({width = 3750.0000, height = 200.0000})
layout:setLeftMargin(-1335.0000)
layout:setRightMargin(-1335.0000)
layout:setTopMargin(-484.0000)
layout:setBottomMargin(2204.0000)
Layer:addChild(Text)

--Create Panel_hide
local Panel_hide = ccui.Layout:create()
Panel_hide:ignoreContentAdaptWithSize(false)
Panel_hide:setClippingEnabled(false)
Panel_hide:setBackGroundColorType(1)
Panel_hide:setBackGroundColor({r = 26, g = 26, b = 26})
Panel_hide:setBackGroundColorOpacity(0)
Panel_hide:setTouchEnabled(true);
Panel_hide:setLayoutComponentEnabled(true)
Panel_hide:setName("Panel_hide")
Panel_hide:setTag(68)
Panel_hide:setCascadeColorEnabled(true)
Panel_hide:setCascadeOpacityEnabled(true)
Panel_hide:setAnchorPoint(0.5000, 0.5000)
Panel_hide:setPosition(540.0000, 960.0000)
Panel_hide:setOpacity(0)
Panel_hide:setColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_hide)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1080.0000, height = 1920.0000})
Layer:addChild(Panel_hide)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

00000000