--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1080.0000, height = 1920.0000})

--Create Image_Desc
local Image_Desc = ccui.ImageView:create()
Image_Desc:ignoreContentAdaptWithSize(false)
Image_Desc:loadTexture("Image/UI/TeacherUI/DescBack.png",0)
Image_Desc:setLayoutComponentEnabled(true)
Image_Desc:setName("Image_Desc")
Image_Desc:setTag(13)
Image_Desc:setCascadeColorEnabled(true)
Image_Desc:setCascadeOpacityEnabled(true)
Image_Desc:setPosition(540.9092, 1457.6330)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_Desc)
layout:setPositionPercentX(0.5008)
layout:setPositionPercentY(0.7592)
layout:setPercentWidth(0.9426)
layout:setPercentHeight(0.1865)
layout:setSize({width = 1018.0000, height = 358.0000})
layout:setLeftMargin(31.9092)
layout:setRightMargin(30.0908)
layout:setTopMargin(283.3671)
layout:setBottomMargin(1278.6330)
Layer:addChild(Image_Desc)

--Create Text_exp
local Text_exp = ccui.Text:create()
Text_exp:ignoreContentAdaptWithSize(true)
Text_exp:setTextAreaSize({width = 0, height = 0})
Text_exp:setFontName("Font/default.ttf")
Text_exp:setFontSize(48)
Text_exp:setString([[『经验』1000]])
Text_exp:setTextVerticalAlignment(1)
Text_exp:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_exp:setLayoutComponentEnabled(true)
Text_exp:setName("Text_exp")
Text_exp:setTag(255)
Text_exp:setCascadeColorEnabled(true)
Text_exp:setCascadeOpacityEnabled(true)
Text_exp:setAnchorPoint(0.0000, 0.5000)
Text_exp:setPosition(28.9997, 1754.9860)
Text_exp:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_exp)
layout:setPositionPercentX(0.0269)
layout:setPositionPercentY(0.9141)
layout:setPercentWidth(0.2898)
layout:setPercentHeight(0.0333)
layout:setSize({width = 313.0000, height = 64.0000})
layout:setLeftMargin(28.9997)
layout:setRightMargin(738.0002)
layout:setTopMargin(133.0140)
layout:setBottomMargin(1722.9860)
Layer:addChild(Text_exp)

--Create Text_pot
local Text_pot = ccui.Text:create()
Text_pot:ignoreContentAdaptWithSize(true)
Text_pot:setTextAreaSize({width = 0, height = 0})
Text_pot:setFontName("Font/default.ttf")
Text_pot:setFontSize(48)
Text_pot:setString([[『潜能』1100]])
Text_pot:setTextVerticalAlignment(1)
Text_pot:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_pot:setLayoutComponentEnabled(true)
Text_pot:setName("Text_pot")
Text_pot:setTag(256)
Text_pot:setCascadeColorEnabled(true)
Text_pot:setCascadeOpacityEnabled(true)
Text_pot:setAnchorPoint(0.0000, 0.5000)
Text_pot:setPosition(538.9992, 1754.9830)
Text_pot:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_pot)
layout:setPositionPercentX(0.4991)
layout:setPositionPercentY(0.9141)
layout:setPercentWidth(0.2898)
layout:setPercentHeight(0.0333)
layout:setSize({width = 313.0000, height = 64.0000})
layout:setLeftMargin(538.9992)
layout:setRightMargin(228.0008)
layout:setTopMargin(133.0175)
layout:setBottomMargin(1722.9830)
Layer:addChild(Text_pot)

--Create Text_topDsc
local Text_topDsc = ccui.Text:create()
Text_topDsc:ignoreContentAdaptWithSize(false)
Text_topDsc:setFontName("Font/default.ttf")
Text_topDsc:setFontSize(48)
Text_topDsc:setString([[你到了武当山最为宏大的紫霄宫。殿宇依山而筑，高低错落有致。周围古木森林，翠竹成林，景色清幽。这里是武当师徒的主要活动场所。]])
Text_topDsc:enableOutline({r = 79, g = 93, b = 93, a = 255}, 5)
Text_topDsc:setLayoutComponentEnabled(true)
Text_topDsc:setName("Text_topDsc")
Text_topDsc:setTag(29)
Text_topDsc:setCascadeColorEnabled(true)
Text_topDsc:setCascadeOpacityEnabled(true)
Text_topDsc:setAnchorPoint(0.5000, 1.0000)
Text_topDsc:setPosition(537.9995, 1610.9790)
Text_topDsc:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_topDsc)
layout:setPositionPercentX(0.4981)
layout:setPositionPercentY(0.8391)
layout:setPercentWidth(0.8599)
layout:setPercentHeight(0.2169)
layout:setSize({width = 928.7307, height = 416.5277})
layout:setLeftMargin(73.6342)
layout:setRightMargin(77.6351)
layout:setTopMargin(309.0206)
layout:setBottomMargin(1194.4520)
Layer:addChild(Text_topDsc)

--Create Panel_bottomButtonArea
local Panel_bottomButtonArea = ccui.Layout:create()
Panel_bottomButtonArea:ignoreContentAdaptWithSize(false)
Panel_bottomButtonArea:setClippingEnabled(false)
Panel_bottomButtonArea:setBackGroundColorOpacity(102)
Panel_bottomButtonArea:setTouchEnabled(true);
Panel_bottomButtonArea:setLayoutComponentEnabled(true)
Panel_bottomButtonArea:setName("Panel_bottomButtonArea")
Panel_bottomButtonArea:setTag(27)
Panel_bottomButtonArea:setCascadeColorEnabled(true)
Panel_bottomButtonArea:setCascadeOpacityEnabled(true)
Panel_bottomButtonArea:setPosition(13.0178, 584.0563)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_bottomButtonArea)
layout:setPositionPercentX(0.0121)
layout:setPositionPercentY(0.3042)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1302)
layout:setSize({width = 1080.0000, height = 250.0000})
layout:setLeftMargin(13.0178)
layout:setRightMargin(-13.0178)
layout:setTopMargin(1085.9440)
layout:setBottomMargin(584.0563)
Layer:addChild(Panel_bottomButtonArea)

--Create Panel_centerNpcArea
local Panel_centerNpcArea = ccui.Layout:create()
Panel_centerNpcArea:ignoreContentAdaptWithSize(false)
Panel_centerNpcArea:setClippingEnabled(false)
Panel_centerNpcArea:setBackGroundColorOpacity(102)
Panel_centerNpcArea:setTouchEnabled(true);
Panel_centerNpcArea:setLayoutComponentEnabled(true)
Panel_centerNpcArea:setName("Panel_centerNpcArea")
Panel_centerNpcArea:setTag(28)
Panel_centerNpcArea:setCascadeColorEnabled(true)
Panel_centerNpcArea:setCascadeOpacityEnabled(true)
Panel_centerNpcArea:setPosition(0.0000, 835.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_centerNpcArea)
layout:setPositionPercentY(0.4349)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2344)
layout:setSize({width = 1080.0000, height = 450.0000})
layout:setTopMargin(634.9999)
layout:setBottomMargin(835.0001)
Layer:addChild(Panel_centerNpcArea)

--Create Text_gongxian
local Text_gongxian = ccui.Text:create()
Text_gongxian:ignoreContentAdaptWithSize(true)
Text_gongxian:setTextAreaSize({width = 0, height = 0})
Text_gongxian:setFontName("Font/default.ttf")
Text_gongxian:setFontSize(48)
Text_gongxian:setString([[『经验』1000]])
Text_gongxian:setTextVerticalAlignment(1)
Text_gongxian:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_gongxian:setLayoutComponentEnabled(true)
Text_gongxian:setName("Text_gongxian")
Text_gongxian:setTag(63)
Text_gongxian:setCascadeColorEnabled(true)
Text_gongxian:setCascadeOpacityEnabled(true)
Text_gongxian:setAnchorPoint(0.0000, 0.5000)
Text_gongxian:setPosition(28.9997, 1680.9810)
Text_gongxian:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_gongxian)
layout:setPositionPercentX(0.0269)
layout:setPositionPercentY(0.8755)
layout:setPercentWidth(0.2898)
layout:setPercentHeight(0.0333)
layout:setSize({width = 313.0000, height = 64.0000})
layout:setLeftMargin(28.9997)
layout:setRightMargin(738.0002)
layout:setTopMargin(207.0190)
layout:setBottomMargin(1648.9810)
Layer:addChild(Text_gongxian)

--Create Text_prestige
local Text_prestige = ccui.Text:create()
Text_prestige:ignoreContentAdaptWithSize(true)
Text_prestige:setTextAreaSize({width = 0, height = 0})
Text_prestige:setFontName("Font/default.ttf")
Text_prestige:setFontSize(48)
Text_prestige:setString([[『经验』1000]])
Text_prestige:setTextVerticalAlignment(1)
Text_prestige:enableOutline({r = 17, g = 18, b = 18, a = 255}, 5)
Text_prestige:setLayoutComponentEnabled(true)
Text_prestige:setName("Text_prestige")
Text_prestige:setTag(11)
Text_prestige:setCascadeColorEnabled(true)
Text_prestige:setCascadeOpacityEnabled(true)
Text_prestige:setAnchorPoint(0.0000, 0.5000)
Text_prestige:setPosition(538.9992, 1680.9810)
Text_prestige:setTextColor({r = 208, g = 208, b = 208})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_prestige)
layout:setPositionPercentX(0.4991)
layout:setPositionPercentY(0.8755)
layout:setPercentWidth(0.2898)
layout:setPercentHeight(0.0333)
layout:setSize({width = 313.0000, height = 64.0000})
layout:setLeftMargin(538.9992)
layout:setRightMargin(228.0008)
layout:setTopMargin(207.0190)
layout:setBottomMargin(1648.9810)
Layer:addChild(Text_prestige)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

0000000000